<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_ECFA</name>
   <tag></tag>
   <elementGuidId>7597d300-1e3a-4b66-8e9a-fe0096c69736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;ECFA&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/footer/div/div[2]/div[1]/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ed6e525-deb6-4acb-a5a7-2dffaf664589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://missionworks.global/wordpress/wp-content/uploads/2023/05/ECFA-100px.png</value>
      <webElementGuid>28e45aab-8391-41f7-9000-213e4e262895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ECFA</value>
      <webElementGuid>0fb17d0d-e818-4f67-afd5-66de0db96af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js&quot;]/body[@class=&quot;home wp-singular page-template-default page page-id-41 wp-custom-logo wp-theme-missiontrip elementor-default elementor-kit-5923 elementor-page elementor-page-41 aa-prefix-missi e--ua-firefox e--ua-mac&quot;]/footer[@class=&quot;footer&quot;]/div[@class=&quot;footer-container&quot;]/div[@class=&quot;footer-bottom&quot;]/div[@class=&quot;footer-badges&quot;]/img[2]</value>
      <webElementGuid>32654af4-0541-4f24-911b-26b0cf8b89b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ECFA']</value>
      <webElementGuid>5a5364fd-a71d-42b0-a14d-4713ad5ec5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img[2]</value>
      <webElementGuid>507dbe78-c830-437f-948c-ade1978e57f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://missionworks.global/wordpress/wp-content/uploads/2023/05/ECFA-100px.png' and @alt = 'ECFA']</value>
      <webElementGuid>9a5a8f1a-14c2-4359-86c6-b0e26e715ed1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
