<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MissionConnexion</name>
   <tag></tag>
   <elementGuidId>aee9f0f2-a239-467e-954c-6ee16b96d477</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='MissionConnexion']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.elementor-sub-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1e5f88e-4d13-4532-a6bb-a56e7a64a8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionconnexion.global/</value>
      <webElementGuid>f4b1cbcf-70d5-44bd-b762-e292c5e37f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-sub-item</value>
      <webElementGuid>4df4f18b-b529-4aa4-8793-8ab9c109e101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MissionConnexion</value>
      <webElementGuid>b360b518-7671-4a02-acbe-38459bedd0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17799005104324214-2&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-77187&quot;]/a[@class=&quot;elementor-sub-item&quot;]</value>
      <webElementGuid>e7e63287-6fe7-4004-a359-4538af183f42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-17799005104324214-2']/li/a</value>
      <webElementGuid>95b93905-15eb-4773-8c91-2fce0741a00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MissionConnexion')]</value>
      <webElementGuid>24c085c5-255e-4042-a2a8-3a0db3f28efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to content'])[1]/following::a[3]</value>
      <webElementGuid>a339f8b3-d77b-4163-bd86-5f385d455eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MIssionNext'])[1]/preceding::a[1]</value>
      <webElementGuid>1c57ecaf-f1ad-446d-b5ae-48e93e7d31be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionGuide'])[1]/preceding::a[2]</value>
      <webElementGuid>f64f6bf9-16ed-4f22-99c0-737ac838617f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MissionConnexion']/parent::*</value>
      <webElementGuid>e3ada051-8c9a-4bf1-87e7-07183f4e767e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://missionconnexion.global/')]</value>
      <webElementGuid>cf8c80d6-8e2d-4add-8252-198e66c1bdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>ec5dd63b-2f26-4e04-a98e-0a1134cfa662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionconnexion.global/' and (text() = 'MissionConnexion' or . = 'MissionConnexion')]</value>
      <webElementGuid>f863cf79-8aaa-4fca-b077-09750dd6a38e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
