<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Matches 1</name>
   <tag></tag>
   <elementGuidId>46f02c4d-7813-4b7a-9ec7-d755954ec1f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(8) > a[title=&quot;View Job Matches&quot;] > input[name=&quot;view_matches&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[9]/a/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83a421e2-61ac-49d7-9111-bad3e37664e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d4e8487-8f9b-4cd0-b148-d6237b39fb79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_primary</value>
      <webElementGuid>a43e2b77-9523-4740-b0ef-2b20df53c840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>view_matches</value>
      <webElementGuid>819f1e0e-824e-4a39-af23-c3b018940fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Matches</value>
      <webElementGuid>a60e17f0-9119-4774-842c-adaaf001983a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/table[1]/tbody[1]/tr[4]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/span[@class=&quot;body&quot;]/form[1]/table[1]/tbody[1]/tr[4]/td[8]/a[1]/input[@class=&quot;button_primary&quot;]</value>
      <webElementGuid>d38c03c2-ef8c-46eb-b601-2dd33e3d8a03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='view_matches'])[2]</value>
      <webElementGuid>a51dc8f7-9c71-4a09-8d9c-3018e36a44d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[8]/a/input</value>
      <webElementGuid>bbecef1b-013f-47d5-a05d-5bb2633aa203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'view_matches']</value>
      <webElementGuid>d29e88ee-8b31-4dbf-bca9-dc8700956111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
