<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_All Countries</name>
   <tag></tag>
   <elementGuidId>d028d689-94e8-43ee-85d2-bce128d06a2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1744301635.194_recruit_countries'])[229]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>483d5bb1-48e8-432b-8d11-1ee072e6ba85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1744301635.194_recruit_countries</value>
      <webElementGuid>91f45ef8-60d4-495b-a32f-b43a95b5505d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>696396fa-9197-4a5a-8028-f7eada110130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1744301635.194][recruit_countries][]</value>
      <webElementGuid>ccc35276-cecc-4b57-b5af-78a222558897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(!) All</value>
      <webElementGuid>41dac9f4-211b-47eb-ae4f-4aa2595e07a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1744301635.194&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1744301635.194_recruit_countries&quot;]</value>
      <webElementGuid>7c325fdd-9e3a-477a-8061-0a41bfb9f247</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1744301635.194_recruit_countries'])[229]</value>
      <webElementGuid>3d4150e2-85a5-4651-a0d1-677d2554e3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1744301635.194']/div/div[3]/div[63]/div/input</value>
      <webElementGuid>0cedf070-b577-4cb0-82c5-054fb7630be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[63]/div/input</value>
      <webElementGuid>f2ac8577-ac16-4ad7-a89c-f57c25844504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1744301635.194_recruit_countries' and @type = 'checkbox' and @name = 'profile[group-1744301635.194][recruit_countries][]']</value>
      <webElementGuid>17f8ab07-227a-462a-8eac-075447a1b79c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
