<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Journey</name>
   <tag></tag>
   <elementGuidId>ad7358d9-497b-4677-be8d-aca3fc3134f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;main&quot;]/div/div/div/div[2]/div[2]/div/table/tr[2]/td[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7dcd012f-6f03-4599-8355-1a62f0911bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Journey</value>
      <webElementGuid>6540ccd0-6521-4c98-aa7e-01178883fcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;dashboard-applications&quot;]/div[@class=&quot;col-md-12&quot;]/table[@class=&quot;subscriptions-table&quot;]/tr[2]/td[1]</value>
      <webElementGuid>191e20e8-11a9-4a5c-9a59-df7d2879a214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div[2]/div[2]/div/table/tr[2]/td</value>
      <webElementGuid>8b5425cc-a96d-4f74-aaec-f8389838b2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Education'])[3]/following::td[2]</value>
      <webElementGuid>fb3dfdd6-1f86-4e51-9c85-8fac639120a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, cktest04ec Kosieracki'])[1]/following::td[3]</value>
      <webElementGuid>ffbffa4d-cb0e-494e-af18-16ba3841a9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Opportunities'])[1]/preceding::td[1]</value>
      <webElementGuid>e5f7ff68-20c3-4fd3-9d0e-f2e6765321f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>ccf0c26d-9a38-470a-bcbe-b2dce3928107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Journey' or . = 'Journey')]</value>
      <webElementGuid>9010ffa7-7a6a-4ea2-864e-384bfecd1b74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
