<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_MissionWorks logo</name>
   <tag></tag>
   <elementGuidId>485ce3b8-bf6a-4299-850c-a295c8b19f0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-77319</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/section[1]/div/div[1]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>73609bb4-32f4-4322-b4f3-5d2f61315f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>fcd25a59-d4fc-4b0c-a028-b24e8bae5b8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>37bc4f9c-8095-4976-be23-a599f09e43c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>160</value>
      <webElementGuid>77514949-466e-493c-9129-7d18e50626cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://missionnext.org/wp-content/uploads/2026/05/MissionWorks.Logo_.Rev_.Horiz_-1024x160.png</value>
      <webElementGuid>02b8a849-0837-418b-8cda-adf2a3595de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-77319</value>
      <webElementGuid>01a8ac09-0fe5-45a2-9e1d-7b329d3479cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://missionnext.org/wp-content/uploads/2026/05/MissionWorks.Logo_.Rev_.Horiz_-1024x160.png 1024w, https://missionnext.org/wp-content/uploads/2026/05/MissionWorks.Logo_.Rev_.Horiz_-300x47.png 300w, https://missionnext.org/wp-content/uploads/2026/05/MissionWorks.Logo_.Rev_.Horiz_-768x120.png 768w, https://missionnext.org/wp-content/uploads/2026/05/MissionWorks.Logo_.Rev_.Horiz_.png 1357w</value>
      <webElementGuid>d526941e-f7b2-430f-86ce-d1b69fab9c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>74ddb5c1-6ee8-407e-be62-16b6dc35d8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home wp-singular page-template-default page page-id-55120 page-parent wp-custom-logo wp-embed-responsive wp-theme-generatepress no-sidebar nav-below-header one-container fluid-header active-footer-widgets-3 header-aligned-left dropdown-hover full-width-content elementor-default elementor-template-full-width elementor-kit-22 elementor-page elementor-page-55120 e--ua-firefox e--ua-mac&quot;]/header[@class=&quot;elementor elementor-55735 elementor-location-header&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-29a48fa9 elementor-section-full_width elementor-section-height-default elementor-section-height-default wpr-column-slider-no wpr-equal-height-no&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-2ea560f5&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-61340449 elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/a[1]/img[@class=&quot;attachment-large size-large wp-image-77319&quot;]</value>
      <webElementGuid>3777fd7f-da8a-45e0-a01e-cf0272e5a6ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://missionnext.org/wp-content/uploads/2026/05/MissionWorks.Logo_.Rev_.Horiz_-1024x160.png')]</value>
      <webElementGuid>5cd4effa-4336-4a8d-8ef8-b405ed136b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>98c6bc8e-0f96-467a-a911-65e9f55f17af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://missionnext.org/wp-content/uploads/2026/05/MissionWorks.Logo_.Rev_.Horiz_-1024x160.png']</value>
      <webElementGuid>ef86dc4c-8c6a-41ae-9bc7-7dcb5e60da14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
