<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bible Training</name>
   <tag></tag>
   <elementGuidId>ea8f6498-98f2-44bf-a424-b820d8ceb7aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1446521801.898_bible_school_training']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>275a51d7-490e-438e-a843-5abf56996259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446521801.898_bible_school_training</value>
      <webElementGuid>5f85a135-fff7-45d9-9c7e-9ba62b9708fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>59f920c6-bf18-4774-b696-9e82cfc73368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446521801.898][bible_school_training][]</value>
      <webElementGuid>4a6eff8a-a199-4ab5-a794-cc6d78d51791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Minimal Bible training</value>
      <webElementGuid>af72c73a-a13e-43df-a6a3-8aa464731a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1446521801.898&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1446521801.898_bible_school_training&quot;]</value>
      <webElementGuid>d735e73b-0376-4975-b045-5eb493033ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1446521801.898_bible_school_training']</value>
      <webElementGuid>2dc15cd1-2d1c-4cef-8bfc-a4418f1a10c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446521801.898']/div[3]/div[2]/div/div/input</value>
      <webElementGuid>83dc81b6-ad0c-437e-84a3-a8d6e5afdfef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>61ea4a89-a54e-4134-8ca8-538a4dd3c132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1446521801.898_bible_school_training' and @type = 'checkbox' and @name = 'profile[group-1446521801.898][bible_school_training][]']</value>
      <webElementGuid>b40fd7a4-437a-415a-b28d-6cabd196a03b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
