<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Business</name>
   <tag></tag>
   <elementGuidId>4cdf4cbe-c887-439b-882f-3b215a31febb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1623987608.435_ministry_preferences'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ba475542-664f-4db3-a7b2-c38d53bf6451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623987608.435_ministry_preferences</value>
      <webElementGuid>638826ac-eee4-4b8c-9918-9c9b497f68de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b3705342-50d7-4646-add9-249f0be7ae06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623987608.435][ministry_preferences][]</value>
      <webElementGuid>629ced6a-0ae0-4d98-a974-06bf5833b4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Business</value>
      <webElementGuid>6b3c00ca-a2e4-4121-b64e-f1c2bb9761eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1623987608.435&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[3]/input[@id=&quot;profile_group-1623987608.435_ministry_preferences&quot;]</value>
      <webElementGuid>5008f522-f851-4afa-9088-0f85e5334ea2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1623987608.435_ministry_preferences'])[3]</value>
      <webElementGuid>b84cf4ea-3e84-4017-bd7c-2d3264b576be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623987608.435']/div[2]/div[3]/div/div[3]/input</value>
      <webElementGuid>0219054a-5d26-4014-88f0-c7aed0b2dea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[3]/div/div[3]/input</value>
      <webElementGuid>d5e6c17c-9068-4e18-8bd9-428e0bbecb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1623987608.435_ministry_preferences' and @type = 'checkbox' and @name = 'profile[group-1623987608.435][ministry_preferences][]']</value>
      <webElementGuid>63272263-5456-427a-8bb5-9571dd18d1c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
