<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Other People Group</name>
   <tag></tag>
   <elementGuidId>b56518a6-969a-4917-a231-f8337094faa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='profile_group-1623987608.435_other_people_group']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5f123e05-db95-49d2-a9a4-3d9fd1a45012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>other_people_group</value>
      <webElementGuid>7c3cbdd8-4dc6-4980-8e62-c07040d0fc3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>392</value>
      <webElementGuid>1b7ecb7f-47db-4a74-a29a-5fb21900b880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-medium-field</value>
      <webElementGuid>a22ec54a-91ac-48bd-9097-48d720d6e8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623987608.435][other_people_group]</value>
      <webElementGuid>7e34968c-d7a3-43bd-98f7-37eeb6faecb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623987608.435_other_people_group</value>
      <webElementGuid>d45dfd4d-268c-484d-8762-2fa38e18df9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1623987608.435_other_people_group&quot;)</value>
      <webElementGuid>4dca21c4-8aff-4477-9ae2-9a83f0dbb810</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='profile_group-1623987608.435_other_people_group']</value>
      <webElementGuid>1e161c15-1e92-46a5-bfc1-031c396ce462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623987608.435']/div[3]/div[3]/textarea</value>
      <webElementGuid>c143fb7e-7d61-4d47-8840-8e819b6ec39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/textarea</value>
      <webElementGuid>0a0a8205-9137-48e0-b9eb-6a246008c184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'profile[group-1623987608.435][other_people_group]' and @id = 'profile_group-1623987608.435_other_people_group']</value>
      <webElementGuid>5a9e297b-1478-42d9-b82e-fa805089d10d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
