<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Team and Board</name>
   <tag></tag>
   <elementGuidId>6ac833a1-092b-49e2-8fe2-e2a0c2b93659</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-3639 > a.elementor-sub-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/section[1]/div/div[2]/div/div/div/nav[1]/ul/li[3]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>27b91c27-52b2-4cfc-9fcb-021d9b9697ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionworks.global/team-and-board/</value>
      <webElementGuid>dad84b38-9aa1-41b7-8e9a-9702cc5e9594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-sub-item</value>
      <webElementGuid>3e6bca8e-3536-4b82-beb0-852c4998069e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Team and Board</value>
      <webElementGuid>91132b1a-c347-4b8a-b596-6f73d8e09c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17805825914181145-6&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-3639&quot;]/a[@class=&quot;elementor-sub-item&quot;]</value>
      <webElementGuid>0223e2cd-b8e1-4764-8acf-24ed169e9595</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-17805825914181145-6']/li[3]/a</value>
      <webElementGuid>3e7554ed-9e1c-48ae-8e19-459e4dcb5fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Team and Board')]</value>
      <webElementGuid>4113b6d3-3a0e-4363-a113-1fc11ddf9d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statement of Faith'])[1]/following::a[1]</value>
      <webElementGuid>f59d162e-ee30-4387-9e4a-06bd974b434f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[2]/following::a[2]</value>
      <webElementGuid>b4caa0f9-ccda-4142-a5d1-d315b0968c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[1]/preceding::a[1]</value>
      <webElementGuid>9bc0051e-a7c8-4279-8f1c-6137c6c653a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[2]</value>
      <webElementGuid>a65da594-4717-462b-83fa-5da7f1806776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Team and Board']/parent::*</value>
      <webElementGuid>b957cf9d-25fa-4ac5-b288-62bba9abe726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://missionworks.global/team-and-board/')]</value>
      <webElementGuid>d18472be-2b85-47bf-8b83-238cbc681750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[3]/a</value>
      <webElementGuid>2ade0dd8-b7a6-425b-be2e-b38a8e6156ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionworks.global/team-and-board/' and (text() = 'Team and Board' or . = 'Team and Board')]</value>
      <webElementGuid>9ecbbf4d-328a-426b-9f4e-694bd48c230d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
