<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Available Positions administrator</name>
   <tag></tag>
   <elementGuidId>4a024daf-fdee-4779-8405-c3741c7c5a6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'profile_group-1456436124.683_educational_positions' and @type = 'checkbox' and @name = 'profile[group-1456436124.683][educational_positions][]' and @value = 'Administrator']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div[1]/div/div/div/div[2]/div[2]/form/div[2]/div[5]/div[1]/div[3]/div[1]/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e8c2042-5d95-4a1e-93dc-34ff65f2a815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1456436124.683_educational_positions</value>
      <webElementGuid>8fb2cf2e-f1f6-4caf-bb08-52d48ea240c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e8e67ba1-de33-42a4-9a6d-3b5bfcabc700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1456436124.683][educational_positions][]</value>
      <webElementGuid>ebb0cbba-73d8-41b8-900d-8fba37986f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Administrator</value>
      <webElementGuid>35aca53f-d13b-44f1-8067-ac1ba468e941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1456436124.683&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[2]/input[@id=&quot;profile_group-1456436124.683_educational_positions&quot;]</value>
      <webElementGuid>4aad4951-26d0-4477-9662-96baacf2fa73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1456436124.683_educational_positions'])[2]</value>
      <webElementGuid>de0fe755-40b6-4bd2-b6dc-a7983d055010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1456436124.683']/div/div[3]/div/div[2]/input</value>
      <webElementGuid>994d3833-bd80-4e48-86de-12e6f1f6dd94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>ad6a8c07-920c-4328-a430-c6202ade224c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1456436124.683_educational_positions' and @type = 'checkbox' and @name = 'profile[group-1456436124.683][educational_positions][]']</value>
      <webElementGuid>f9a1fb64-b768-4d47-88c6-e394be6dd359</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
