<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_School Term open</name>
   <tag></tag>
   <elementGuidId>d94fe144-db7d-4428-8251-caefba83258f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1456436314.404_school_term_available'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ebc6856-9f19-47de-a7f3-3772f8aca611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1456436314.404_school_term_available</value>
      <webElementGuid>8d091e38-fc4b-4fc5-80c7-aaafdf3c59a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4a210ac1-fa1d-4f32-ba27-bedcf548d84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1456436314.404][school_term_available][]</value>
      <webElementGuid>e979b1f1-3977-4d72-818b-40fd52016739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(!) Open</value>
      <webElementGuid>fc24ae00-677a-4b92-81af-44fcded8612a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1456436314.404&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[2]/input[@id=&quot;profile_group-1456436314.404_school_term_available&quot;]</value>
      <webElementGuid>c797351d-d4f7-44c7-9479-3e8aced313d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1456436314.404_school_term_available'])[5]</value>
      <webElementGuid>4b41391d-48b0-4858-8f71-27596fea2c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1456436314.404']/div[3]/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>bf80dd1c-c543-42d2-af5e-35d6e7236370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>b02607e8-9251-4a1a-bc25-c609a9f500fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1456436314.404_school_term_available' and @type = 'checkbox' and @name = 'profile[group-1456436314.404][school_term_available][]']</value>
      <webElementGuid>adac8a3e-04b6-4b9c-be36-b613b87363c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
