<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Formal Teaching Credential yes</name>
   <tag></tag>
   <elementGuidId>af8c9124-97b2-49d0-bab7-0ec3ba9fe625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1456436956.575_has_teaching_credentials'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24f6858e-82d5-4e4a-9684-1a05f949786e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1456436956.575_has_teaching_credentials</value>
      <webElementGuid>3607c88f-1ce7-4324-b1b2-59e387b98bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>38b93d43-2349-4d4c-9884-3f3a645498a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1456436956.575][has_teaching_credentials][]</value>
      <webElementGuid>97d8d9a7-3dba-47e9-b0f7-5c12eb172b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>ad371125-021f-48c5-b21b-1bdc38f0ab1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1456436956.575&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-small-checkbox&quot;]/div[2]/input[@id=&quot;profile_group-1456436956.575_has_teaching_credentials&quot;]</value>
      <webElementGuid>5f281b7e-9248-490b-a1ed-3bd8306cedd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1456436956.575_has_teaching_credentials'])[2]</value>
      <webElementGuid>bd1f7124-758f-4da5-8192-5ec9880881c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1456436956.575']/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>fa374e5d-1b3e-43f8-964a-253e3c799c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/div[2]/div/div[2]/input</value>
      <webElementGuid>ff505c0d-80b3-4af5-91bf-c8bcead8ea9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1456436956.575_has_teaching_credentials' and @type = 'checkbox' and @name = 'profile[group-1456436956.575][has_teaching_credentials][]']</value>
      <webElementGuid>ba9e8348-ce51-4253-9114-89efab8cae9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
