<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Conferences Attended</name>
   <tag></tag>
   <elementGuidId>8965f1ec-23d3-42de-b07a-74e9681b57f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1445373964.535_conferences_attended']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f1ff888d-54fa-4aa0-8e12-e5512c4eeb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1445373964.535_conferences_attended</value>
      <webElementGuid>6d0223d1-7642-418b-99f6-94d84e7b8b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>94fc3140-235a-4865-8e01-5b736e32010f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1445373964.535][conferences_attended][]</value>
      <webElementGuid>ae0b72d6-722b-423d-a533-63dfa31b3b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ICOM (The International Conference on Missions)</value>
      <webElementGuid>bde985cd-78b1-4380-997d-bd92d0bf6e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1445373964.535&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1445373964.535_conferences_attended&quot;]</value>
      <webElementGuid>f863db29-f557-4c82-9a3c-a9c70729f40f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1445373964.535_conferences_attended']</value>
      <webElementGuid>e9cf4647-2833-4c0c-9690-46b35df91a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1445373964.535']/div[6]/div[2]/div/div/input</value>
      <webElementGuid>61fc6286-2271-4951-9c59-170b9bd814e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[6]/div[2]/div/div/input</value>
      <webElementGuid>65a753ac-56ec-4987-838a-363f48a2de14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1445373964.535_conferences_attended' and @type = 'checkbox' and @name = 'profile[group-1445373964.535][conferences_attended][]']</value>
      <webElementGuid>fd142886-27d0-4aa8-87aa-16042e7eac81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
