<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Need Candidates for Short-Term Assignments</name>
   <tag></tag>
   <elementGuidId>79561dad-341c-429c-8de0-9f2914a16824</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1446521622.636_need_positions_in_short-term_specifically']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>84f47a1f-bffd-43a4-b93b-515be88f4e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependant</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>df8d3084-ce09-4b85-a6ae-178a8cf02729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>need_positions_in_short-term_specifically</value>
      <webElementGuid>1b34fe2e-2816-486d-bfa5-b3eeb17366c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>174</value>
      <webElementGuid>ef1842d7-dd81-409b-ab7a-ce5c0741ebd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446521622.636][need_positions_in_short-term_specifically]</value>
      <webElementGuid>40ce109b-e6c6-44e4-afec-8815ca8181ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446521622.636_need_positions_in_short-term_specifically</value>
      <webElementGuid>8d4ee03e-2f72-46f5-bcbe-563d1e1711ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3facf502-0139-4e2b-a561-105f33ead60c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0382fb24-dd6b-4e2b-bd39-76b80dd97611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1446521622.636_need_positions_in_short-term_specifically&quot;)</value>
      <webElementGuid>fb865e2e-3607-4d4a-96b8-c1f342290fe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1446521622.636_need_positions_in_short-term_specifically']</value>
      <webElementGuid>7c80a5b1-1012-451d-babf-5d2ca1889d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446521622.636']/div[9]/div[2]/input[2]</value>
      <webElementGuid>34130d6e-44ce-4d73-9708-c5cae6dd7d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input[2]</value>
      <webElementGuid>f3682a43-d8b6-4f13-be5d-482b7137104c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'profile[group-1446521622.636][need_positions_in_short-term_specifically]' and @id = 'profile_group-1446521622.636_need_positions_in_short-term_specifically' and @type = 'checkbox']</value>
      <webElementGuid>ff404012-6e45-4a4a-a1d4-ca40871ec7bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
