<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Short-Term Trip Lengths</name>
   <tag></tag>
   <elementGuidId>264e2e30-466a-469a-8fef-2514e56badaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1694885436.586_trip_lengths']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a49f087-35cb-46e3-880c-419162421ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1694885436.586_trip_lengths</value>
      <webElementGuid>328fa0c1-dbb5-4468-8e62-6b0625cbb796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>27f91b91-109e-4649-bb19-66f4d98a6075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1694885436.586][trip_lengths][]</value>
      <webElementGuid>8685bb3e-22fd-4926-8178-03a54e6d6dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>One Week</value>
      <webElementGuid>1d1dc39d-34b2-4e52-a148-ece168eb9e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1446521622.636&quot;)/div[@class=&quot;subgroup dependent-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1694885436.586_trip_lengths&quot;]</value>
      <webElementGuid>f78c9d7f-823f-462e-84a2-f92974d4384c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1694885436.586_trip_lengths']</value>
      <webElementGuid>b5220009-268e-4e1a-ab08-1dd04ee5804f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446521622.636']/div[10]/div/div/div/div/input</value>
      <webElementGuid>4c7b4825-bbe2-46ea-bd60-8fe9d4840aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[10]/div/div/div/div/input</value>
      <webElementGuid>64673aa4-90d7-474d-b9b7-1e0c084d4e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1694885436.586_trip_lengths' and @type = 'checkbox' and @name = 'profile[group-1694885436.586][trip_lengths][]']</value>
      <webElementGuid>9fa0eb46-66cf-476b-a49b-7b42969be974</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
