<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Short-Term Objective</name>
   <tag></tag>
   <elementGuidId>873be255-a128-46fd-b108-53f1837da083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1694885436.586_short-term_objective']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7be9a06-87c8-4f2a-80db-055546a4f3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1694885436.586_short-term_objective</value>
      <webElementGuid>4b71f7cb-8d8c-43cc-9e5b-60425667060e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>86c71583-4b70-4a63-90a3-910b1d93eb33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1694885436.586][short-term_objective][]</value>
      <webElementGuid>a0118935-c976-4d8a-b778-79550bcafaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Discover next steps in the global missions enterprise</value>
      <webElementGuid>50565304-a81a-4916-a4b8-a123ecada055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1446521622.636&quot;)/div[@class=&quot;subgroup dependent-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1694885436.586_short-term_objective&quot;]</value>
      <webElementGuid>cb8cd6fa-5773-4894-aaaa-7e8ea7843093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1694885436.586_short-term_objective']</value>
      <webElementGuid>ee05ff4d-efd1-461f-aecd-9b8048230e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446521622.636']/div[10]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>13527f20-8232-4d78-9e06-1142d07deb6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>77a20b1d-7663-4039-b683-962264943232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1694885436.586_short-term_objective' and @type = 'checkbox' and @name = 'profile[group-1694885436.586][short-term_objective][]']</value>
      <webElementGuid>77f1a873-d532-4911-a036-6eecdae142de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
