<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_About Us</name>
   <tag></tag>
   <elementGuidId>bd115296-d018-48a8-a680-253f8be28481</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='menu-1-3e91e851']/li[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'https://missionworks.global/homepage/about-us/' and @aria-haspopup = 'true' and (text() = 'About Us' or . = 'About Us')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sm-17799228667428916-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>982dbcc2-7b7c-4712-a942-010e7e0010a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionworks.global/homepage/about-us/</value>
      <webElementGuid>841eb3d4-2c41-4e2a-b772-dbb25b990e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-item has-submenu highlighted</value>
      <webElementGuid>ec7e949d-f0b6-4c99-9e2e-7956b09881bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sm-17799228667428916-5</value>
      <webElementGuid>cb52d37a-34a8-40a1-b35e-31219fc7455d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>395a5edc-2764-4bdb-a5de-60badea8a1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sm-17799228667428916-6</value>
      <webElementGuid>73e52095-15c6-4b03-b3f4-995a8dc07b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>163fbff4-05ad-4e19-b4e5-49a4f5c9f2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About Us</value>
      <webElementGuid>74230ded-6025-490e-b506-1b9c61a65acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17799228667428916-5&quot;)</value>
      <webElementGuid>c779c00d-f0ac-46b3-8547-26158d929851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sm-17799228667428916-5']</value>
      <webElementGuid>9353b818-199d-4b46-934d-0edcbd7ba0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-1-3e91e851']/li[3]/a</value>
      <webElementGuid>fb7ae984-a948-4130-8a2a-cb932e0fd74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'About Us')]</value>
      <webElementGuid>28179316-3ddf-451a-8920-122413e1e41a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionExcellence'])[1]/following::a[1]</value>
      <webElementGuid>0593aece-adb2-42cc-801d-d1fa85d72b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionArmor'])[1]/following::a[2]</value>
      <webElementGuid>5b4dddf0-022b-4ae7-a4f1-4625c54a2667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Statement of Faith'])[1]/preceding::a[1]</value>
      <webElementGuid>50ab3fea-5c95-4ee4-a51e-e67f103a0455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team and Board'])[1]/preceding::a[2]</value>
      <webElementGuid>85af7c7b-ef5b-45fb-bdd2-7784f08d853b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='About Us']/parent::*</value>
      <webElementGuid>6b1d1bfe-3b6a-41dc-a629-a4bb24b4e91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://missionworks.global/homepage/about-us/')]</value>
      <webElementGuid>fa2cdc5c-20d1-4689-8488-378b03f4cc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a</value>
      <webElementGuid>752ea853-020c-4318-b415-c1999017540e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionworks.global/homepage/about-us/' and @id = 'sm-17799228667428916-5' and (text() = 'About Us' or . = 'About Us')]</value>
      <webElementGuid>78d06b9f-b373-494c-83d4-29a0e0a1da06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
