<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Donate</name>
   <tag></tag>
   <elementGuidId>b6b192fc-e320-40f5-9acf-362ce6fe1cbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.mc-donate-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/div/nav/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81d1cae0-fe15-455c-9edf-ca339205ef44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionworks.app.neoncrm.com/forms/missionworks-giving</value>
      <webElementGuid>9bde16b2-7cad-4f8d-8f1f-c49ec8f0b60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mc-donate-btn</value>
      <webElementGuid>68dedbb9-c397-452f-917b-227bb2b52369</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Donate</value>
      <webElementGuid>7ce808e3-3bee-4ea2-b67e-76bb2487e9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mc-nav&quot;)/a[@class=&quot;mc-donate-btn&quot;]</value>
      <webElementGuid>3f6d28ff-1d16-4b4a-b53b-0e47a4294e32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mc-nav']/a</value>
      <webElementGuid>07398ad1-d6bb-472a-997d-3c41df0f105a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Donate')]</value>
      <webElementGuid>f0152c12-9c60-4edf-9359-ab61febb95c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::a[1]</value>
      <webElementGuid>0cb7e760-62fd-419c-b43d-d6418a4c8130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Careers'])[1]/following::a[2]</value>
      <webElementGuid>06786e56-839b-473a-9487-f45f6cf72ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPONSORSHIP'])[1]/preceding::a[2]</value>
      <webElementGuid>ce1fcdf1-f4cd-4137-8fdf-c916fcf9dcbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT US'])[1]/preceding::a[3]</value>
      <webElementGuid>4e1a7ab1-f61d-4edf-9244-8f16b316e7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Donate']/parent::*</value>
      <webElementGuid>d92ff17d-58c6-4e26-a860-92e6481fafec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://missionworks.app.neoncrm.com/forms/missionworks-giving')]</value>
      <webElementGuid>32c5ce38-7eec-4e09-98ce-ec86d85e9f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a</value>
      <webElementGuid>46fea6ab-796e-4a02-98cd-49ba61d098a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionworks.app.neoncrm.com/forms/missionworks-giving' and (text() = 'Donate' or . = 'Donate')]</value>
      <webElementGuid>649dd700-c476-4b6d-b3f4-8329a9947f1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
