<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Male</name>
   <tag></tag>
   <elementGuidId>272e5546-847f-4613-ac94-73c7df15da42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='profile[group-1443546232.861][gender]'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(2) > input[name=&quot;profile[group-1443546232.861][gender]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>948c9eec-c3f8-4a6e-81b3-815100d479b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>44b126b9-4a56-4127-9411-d4b107b17f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>8b04d3e0-c056-48d1-89e8-cbee545e8e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>99b5fa72-7a14-4097-8ba0-48aec1bd1f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1443546232.861][gender]</value>
      <webElementGuid>84aa66d6-af2e-427a-bf62-7aec17e7723a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>eb8852f8-2431-4e8c-b97f-628dcfd211df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1443546232.861&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[2]/input[1]</value>
      <webElementGuid>60ebba9e-49f5-4a0e-ab66-7b76b42b9d6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='profile[group-1443546232.861][gender]'])[2]</value>
      <webElementGuid>86a3c398-02ec-4f8c-9e3a-fc7533035203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1443546232.861']/div[3]/div[2]/div[2]/input</value>
      <webElementGuid>37d1512e-333d-4a0d-a6b0-1da9ae45592c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/input</value>
      <webElementGuid>aef73b32-ef1c-4b6a-8895-04b777614320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'profile[group-1443546232.861][gender]']</value>
      <webElementGuid>c02de586-02c4-4749-9bb2-1c6d58fe9295</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
