<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Resources</name>
   <tag></tag>
   <elementGuidId>45f6840e-cc34-495c-9912-701e53eb629b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[2]/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-main-menu-1 > li.dropdown-button.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-895 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f7742008-4be0-404e-aadb-69ae8d06ee0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionexcellence.global/resources/</value>
      <webElementGuid>d80f1d00-235d-417a-bf0b-8a32eae442bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resources </value>
      <webElementGuid>12c06ffa-c966-4f6a-8c50-01bf72fec04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-main-menu-1&quot;)/li[@class=&quot;dropdown-button menu-item menu-item-type-custom menu-item-object-custom menu-item-895&quot;]/a[1]</value>
      <webElementGuid>924d3ca6-1f8a-4f4a-afb8-52f73bc4ce1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-main-menu-1']/li[5]/a</value>
      <webElementGuid>d2199873-2497-4bbb-81f3-48e5b2ab150a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Resources')])[2]</value>
      <webElementGuid>09070cd8-30d1-47a3-9980-cd0b31d3b608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Membership'])[2]/following::a[1]</value>
      <webElementGuid>b1f186cb-869e-4744-80ff-8e9252c58ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sponsorship'])[2]/following::a[2]</value>
      <webElementGuid>709db6ae-35dd-435c-a158-f0b7aabab4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[2]/preceding::a[1]</value>
      <webElementGuid>35c419a3-5f82-41b7-9cc1-c68f04a8e623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Today'])[2]/preceding::a[2]</value>
      <webElementGuid>8ac05a13-1bcc-4010-9112-c64127a73b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://missionexcellence.global/resources/')])[2]</value>
      <webElementGuid>d839bace-75e4-46a3-834a-bf51ec760ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav[2]/ul/li[5]/a</value>
      <webElementGuid>fb3f9915-f79b-4672-b7d7-d03f1bca3ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionexcellence.global/resources/' and (text() = 'Resources ' or . = 'Resources ')]</value>
      <webElementGuid>e203dd38-f9d8-4ca5-ab53-43978ac8bf4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
