<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Supporter_sub-arrow</name>
   <tag></tag>
   <elementGuidId>e380bd1e-6647-4c76-a150-0f0d6292d71b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/section[2]/div[2]/div/div/div/div/nav[1]/ul/li[5]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sm-1786036766985268-9 > span.sub-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1ffe3531-e9c4-4513-8470-331cdd153782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-arrow</value>
      <webElementGuid>450381df-21f3-4015-ba5d-f9b4854bdc38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-1786036766985268-9&quot;)/span[@class=&quot;sub-arrow&quot;]</value>
      <webElementGuid>9b6ddf4b-0205-4cce-a5ec-e71da45200d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sm-1786036766985268-9']/span</value>
      <webElementGuid>0eed6551-2249-4465-b5f0-4a18f5fa035c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supporter'])[1]//span[1]</value>
      <webElementGuid>fb747bc5-3eb1-4343-8493-a81c3a1ed31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resources'])[2]/following::span[1]</value>
      <webElementGuid>aee62d33-1a08-4a6f-a250-91b64fd77f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supporter'])[2]/preceding::span[1]</value>
      <webElementGuid>b2187d52-41bd-4ea3-949a-0619ec89b7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobilizer'])[1]/preceding::span[1]</value>
      <webElementGuid>7d134e69-6787-433a-98a5-2fbc8e80fec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>f996b4e6-b553-4812-9e7e-b0f98287b0fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
