<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Accord Network</name>
   <tag></tag>
   <elementGuidId>3796ad57-c6b9-425b-bec0-d39d4cd83aaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='registration_group-1464701251.989_memberships'])[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55e8eb9b-4482-4e89-8049-4746d6dc49ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1464701251.989_memberships</value>
      <webElementGuid>bcc58fab-8348-4a9b-a51a-4a9a44b21b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b7ac6785-4520-4ddc-9e74-ef2e0e48959c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1464701251.989][memberships][]</value>
      <webElementGuid>9c00726f-8d1e-4c4a-aa60-37496f7ab826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ACCORD Network/AERDO</value>
      <webElementGuid>4c53c3e5-838c-4842-8ecd-68cefb47d2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1464701251.989&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-checkbox mn-medium-checkbox&quot;]/div[4]/input[@id=&quot;registration_group-1464701251.989_memberships&quot;]</value>
      <webElementGuid>69b292dc-792d-472d-b44e-48a0c0858ce1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='registration_group-1464701251.989_memberships'])[4]</value>
      <webElementGuid>83e917ae-b78b-4390-9c77-03f3353cc707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1464701251.989']/div[5]/div[2]/div/div[4]/input</value>
      <webElementGuid>daceb85a-91c1-449f-9ef7-9696962e6388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>c94d707e-ebef-42c4-803c-04c4dc9b63f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group-1464701251.989_memberships' and @type = 'checkbox' and @name = 'registration[group-1464701251.989][memberships][]']</value>
      <webElementGuid>9606fc54-d4f0-4e59-b825-9bce5f5d3d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
