<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Partnership Agreement_registrationgro_ccbf5d</name>
   <tag></tag>
   <elementGuidId>cc5f52b3-b4e6-436c-9938-5a7c88660aa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_group-1464701251.989_partnership_agreement']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>237a44b0-ec23-47e7-8ee7-c44eae3918f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-boolean </value>
      <webElementGuid>46ede407-1527-44d3-86cf-00a9c27b31c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>partnership_agreement</value>
      <webElementGuid>842f6fbf-5883-41c0-836b-b2c0c87de8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>53</value>
      <webElementGuid>8f8eb09c-86c9-4eaf-bf84-72ac10e1a2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1464701251.989][partnership_agreement]</value>
      <webElementGuid>d846977d-6277-4ac8-84a5-55a140834823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1464701251.989_partnership_agreement</value>
      <webElementGuid>cac8ef38-187b-42b5-bdea-116da5477d67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f5fc231e-3b82-419a-b000-d1db0658df38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e525e1f2-a3af-4b19-916f-aa43189f18d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group-1464701251.989_partnership_agreement&quot;)</value>
      <webElementGuid>eae39524-cfdd-4938-8dce-1838a7e01c4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_group-1464701251.989_partnership_agreement']</value>
      <webElementGuid>12629439-1558-495f-abc8-05823dae4a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1464701251.989']/div[9]/div[3]/input</value>
      <webElementGuid>9e64e422-a465-4409-9cae-7e2625af88d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[3]/input</value>
      <webElementGuid>c13e00db-01b6-49a2-8e71-c6d611d782a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'registration[group-1464701251.989][partnership_agreement]' and @id = 'registration_group-1464701251.989_partnership_agreement' and @type = 'checkbox']</value>
      <webElementGuid>b4b06502-2cdd-4602-9858-259f3d638c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
