<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accounting</name>
   <tag></tag>
   <elementGuidId>627343d3-2b68-4f0e-a5f0-4906383dba6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1623989119.621_spouse_ministry_preferences'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a775fbab-575f-4cc1-b2e4-c991a633d73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623989119.621_spouse_ministry_preferences</value>
      <webElementGuid>21b0d143-ffc8-437f-a8f7-14d59239d213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>827212ef-8708-4ca8-a3b7-ac144016fe05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623989119.621][spouse_ministry_preferences][]</value>
      <webElementGuid>abb73de6-d051-4ea6-ba1b-a59080618543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Agriculture</value>
      <webElementGuid>ee22bdee-7198-4942-b16d-0a8f6acfc98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1623989119.621&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[2]/input[@id=&quot;profile_group-1623989119.621_spouse_ministry_preferences&quot;]</value>
      <webElementGuid>65a0c4c6-e3c4-49ed-957e-bc06137afa2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1623989119.621_spouse_ministry_preferences'])[2]</value>
      <webElementGuid>6fc58070-c592-4d3d-b4fe-06d380c50ffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623989119.621']/div/div[2]/div/div[2]/input</value>
      <webElementGuid>94c86532-4024-460a-8b5b-cc11b110721e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]/div/div[2]/input</value>
      <webElementGuid>cf734b03-ef7b-4698-801e-6fe8c7b0ef5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1623989119.621_spouse_ministry_preferences' and @type = 'checkbox' and @name = 'profile[group-1623989119.621][spouse_ministry_preferences][]']</value>
      <webElementGuid>363cd26d-3dcd-4b53-b9b4-63da95dd2abd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
