<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Preferences Comment</name>
   <tag></tag>
   <elementGuidId>82757fb0-14fb-4675-8fd7-08d049042387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='profile_group-1623989119.621_preferences_comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>14cc552a-5e4f-4a7e-ba64-737145b9669b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>preferences_comment</value>
      <webElementGuid>a907808f-87a6-41bd-a75d-a145005e0be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>67</value>
      <webElementGuid>7689e32d-c21e-4cc0-85d2-e2d8f4361b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-small-field</value>
      <webElementGuid>3ad4a360-4c9a-42a6-95ad-d8aa99a6bc51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623989119.621][preferences_comment]</value>
      <webElementGuid>f2d8f814-ee22-4476-adf2-4c91c9e183bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623989119.621_preferences_comment</value>
      <webElementGuid>659c9db6-0d4a-4412-a38a-a9127700f82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1623989119.621_preferences_comment&quot;)</value>
      <webElementGuid>1ec6e324-e4f3-41f5-b86c-1a23bb8f851c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='profile_group-1623989119.621_preferences_comment']</value>
      <webElementGuid>dec3948a-edec-48f7-a1ff-57feb3e54554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623989119.621']/div[2]/div[2]/textarea</value>
      <webElementGuid>fc38e344-0756-466f-99ab-29dd983b1336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/textarea</value>
      <webElementGuid>778c7a6a-e9b2-48d2-a7c2-22e832ebda87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'profile[group-1623989119.621][preferences_comment]' and @id = 'profile_group-1623989119.621_preferences_comment']</value>
      <webElementGuid>0736b2ea-73b3-4d21-b094-70579e403935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
