<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxes_- SUPPORT HELPS</name>
   <tag></tag>
   <elementGuidId>f6d06015-a271-4614-8483-5287c1b1bfee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_group-1613487293.775_subset_support_helps']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9360abc4-62b3-4303-ad69-a1096b5c9160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_group-1613487293.775_subset_support_helps</value>
      <webElementGuid>4e3d83fd-47f4-43e0-945b-d6b54159f177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9c678b1b-5252-4155-ad74-19b9d14ffd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job[group-1613487293.775][subset_support_helps][]</value>
      <webElementGuid>08b5a9fe-05f4-4bc5-af12-2f33d1cefaaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Administrative Assistant</value>
      <webElementGuid>c2fa6623-e186-49f5-8f25-dfaf41f60f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group1&quot;)/div[@class=&quot;subgroup dependent-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;job_group-1613487293.775_subset_support_helps&quot;]</value>
      <webElementGuid>b533c763-179e-406e-992c-e38f2186c422</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_group-1613487293.775_subset_support_helps']</value>
      <webElementGuid>94c80668-7874-4331-b7a5-885632ee8142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[11]/div/div/div/div/input</value>
      <webElementGuid>f3c1205d-3efd-48f0-9e95-da0c04b5fb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/input</value>
      <webElementGuid>b3f3beba-a7fb-45bc-b9e0-35b7a069233f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'job_group-1613487293.775_subset_support_helps' and @type = 'checkbox' and @name = 'job[group-1613487293.775][subset_support_helps][]']</value>
      <webElementGuid>3e8385f3-b525-4e39-8d6d-37a18372d6b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
