<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxes_- DISCIPLE YOUTH</name>
   <tag></tag>
   <elementGuidId>d7f18ee2-59c2-447a-b6fd-c5d2e1ecfe4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_group-1613487089.233_subset_disciple_youth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55d1987e-3346-4b7e-a32e-8d8ee6c4ec9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_group-1613487089.233_subset_disciple_youth</value>
      <webElementGuid>b223d68d-0672-4a4e-b642-54d19a4f92bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>244d2009-5f5f-4dc3-965f-366332666135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job[group-1613487089.233][subset_disciple_youth][]</value>
      <webElementGuid>e1a7afc3-da64-448d-82cb-3816a1565708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Pre-School/Toddlers</value>
      <webElementGuid>1c5034dc-0557-4ca4-aba5-5c33c4ed7659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group1&quot;)/div[@class=&quot;subgroup dependent-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[1]/input[@id=&quot;job_group-1613487089.233_subset_disciple_youth&quot;]</value>
      <webElementGuid>73144d3d-8343-44a6-a46c-71769649e33c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_group-1613487089.233_subset_disciple_youth']</value>
      <webElementGuid>1a983fee-51a9-4d63-873b-640e7e93ab4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[20]/div/div/div/div/input</value>
      <webElementGuid>b05cac63-c9cf-4f5d-8244-a4622af2f53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div/div/div/input</value>
      <webElementGuid>f79d6e40-de66-46c6-97d6-228b556e826c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'job_group-1613487089.233_subset_disciple_youth' and @type = 'checkbox' and @name = 'job[group-1613487089.233][subset_disciple_youth][]']</value>
      <webElementGuid>41089940-4dcf-4f26-89b4-8084f488d030</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
