<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxes_- RELIEF AND DEVELOPMENT</name>
   <tag></tag>
   <elementGuidId>f0347e5d-a27c-4518-9b35-852864f9db13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_group-1613487334.329_subset_relief_and_development']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a51eb6ea-521a-4e62-b28a-6ee49b6c5e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_group-1613487334.329_subset_relief_and_development</value>
      <webElementGuid>191a9a8b-9ca8-4a4b-bd8c-2c36bef836ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c9dd7473-7f67-4cd6-a907-c7965df3bf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job[group-1613487334.329][subset_relief_and_development][]</value>
      <webElementGuid>9fedd441-fb69-4438-8fd6-d7b25a7a8fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Agriculture/Horticulture</value>
      <webElementGuid>8812272d-ea1b-440c-b71c-cb46f63c2557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group1&quot;)/div[@class=&quot;subgroup dependent-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;job_group-1613487334.329_subset_relief_and_development&quot;]</value>
      <webElementGuid>4f3dfe9b-acb3-457f-97e4-ffb7815edb85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_group-1613487334.329_subset_relief_and_development']</value>
      <webElementGuid>f8e2966e-f3a9-4be1-b223-b0a1decf6ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[19]/div/div/div/div/input</value>
      <webElementGuid>4a3f6bb9-2a58-4fc2-9c2e-f1f580ec30fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div/div/div/input</value>
      <webElementGuid>2155c34a-d1ac-4b1c-bb93-2398aff5aaa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'job_group-1613487334.329_subset_relief_and_development' and @type = 'checkbox' and @name = 'job[group-1613487334.329][subset_relief_and_development][]']</value>
      <webElementGuid>ffbb0de9-36fe-4726-97cc-a33b301a9230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
