<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxes_- EDUCATION</name>
   <tag></tag>
   <elementGuidId>bb7353ce-73fa-4b8c-bb6d-17b84be81b23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_group-1613487111.532_subset_education']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e309188-7c4d-49e8-a0a0-0aa1b0952034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_group-1613487111.532_subset_education</value>
      <webElementGuid>51453f1d-e907-4d8c-a581-c641f0adf609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b04c4236-ee80-40f5-97b3-c5b17fd0787a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job[group-1613487111.532][subset_education][]</value>
      <webElementGuid>ccedc9bf-0eb3-4dbe-80d1-3467b156f1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Elementary Education</value>
      <webElementGuid>04e62aa4-44ad-48ec-8a91-acae46aa591d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group1&quot;)/div[@class=&quot;subgroup dependent-group&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;job_group-1613487111.532_subset_education&quot;]</value>
      <webElementGuid>5e84f137-5a10-463e-9bc0-b8e0fa115e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_group-1613487111.532_subset_education']</value>
      <webElementGuid>36fe1e54-8e93-4729-b2bc-68916b01131b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[6]/div/div/div/div/input</value>
      <webElementGuid>feedea3f-25f9-497e-831d-6a810ebaf4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/input</value>
      <webElementGuid>5ca1d3b2-e928-4f92-86e9-a9a35205b66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'job_group-1613487111.532_subset_education' and @type = 'checkbox' and @name = 'job[group-1613487111.532][subset_education][]']</value>
      <webElementGuid>123d4d9a-68c4-44e6-812a-dd9823d56ea4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
