<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No Preference</name>
   <tag></tag>
   <elementGuidId>0bab0e2b-beed-472c-8187-f0d62342ba25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@value = '(!) No Preference']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='choice_[14][20]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;choice_[14][20]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ec53a8f-5ecf-4c26-8f73-5ddf09b4963b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f9aaadf3-3858-49ad-b7f8-ffec9706a213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>choice_[14][20]</value>
      <webElementGuid>8e4f1899-f624-48a4-bf8e-fc9a6a3ba2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(!) No Preference</value>
      <webElementGuid>82e39e76-3a21-4fb7-bf14-9a4e7b30d3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/table[1]/tbody[1]/tr[4]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/span[@class=&quot;body&quot;]/form[1]/table[1]/tbody[1]/tr[53]/td[3]/input[1]</value>
      <webElementGuid>2baca624-5c75-4528-aa35-5558ef1003ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='choice_[14][20]']</value>
      <webElementGuid>2ffce3d6-e4f2-4561-83ec-26198b35fb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[53]/td[3]/input</value>
      <webElementGuid>f8f96d74-7fe3-409b-8230-633be28f265f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'choice_[14][20]']</value>
      <webElementGuid>490e9ad6-83cd-46f6-9b08-438d89af0c33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
