<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Organization_field-tooltip</name>
   <tag></tag>
   <elementGuidId>9217a32f-f6ce-48fa-9c3c-22c7fc0d9046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;group1&quot;]/div[1]/div[1]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#group1 > div.form-group > div.col-sm-3 > img.field-tooltip</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2ac13a48-18d1-4c98-888d-9023519482fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://journey.missionnext.org/wp-content/plugins/MissionNext/resources/images/tooltip.png</value>
      <webElementGuid>3bd84c51-53ed-4aac-a886-a1dcf76d2e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field-tooltip</value>
      <webElementGuid>553c04a8-1398-4cf3-b612-7cbaa508a924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>e6a6fb00-b0b8-4294-8105-0a96a09fc3ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Name of your Organization.(Shorten, if too long to fit in field)</value>
      <webElementGuid>c0d4d9bd-7d68-4ac5-91fd-5aed22d46737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group1&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-3&quot;]/img[@class=&quot;field-tooltip&quot;]</value>
      <webElementGuid>bdc76efd-f2c5-47f1-8394-c40658cf7ffa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id=&quot;group1&quot;]/div[1]/div[1]/img</value>
      <webElementGuid>51b358d1-dfa3-4eec-88d2-d7aa3b5502a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='tooltip'])[3]</value>
      <webElementGuid>ee60d260-fe40-46f9-afa5-22b7fd8f1507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img</value>
      <webElementGuid>94664b53-d95b-450e-9970-774cde7b568b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://journey.missionnext.org/wp-content/plugins/MissionNext/resources/images/tooltip.png' and @alt = 'tooltip']</value>
      <webElementGuid>349061b6-3d65-4af9-a81f-7e04ffd48ef5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
