<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Board of Directors</name>
   <tag></tag>
   <elementGuidId>44c5563f-3b51-4155-8d43-4431b4964544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_group-1446560994.446_board_of_directors']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f83f05a-21a8-4750-8f1d-e4d0e08d2e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-input mn-large-field</value>
      <webElementGuid>8d1e1d38-94c2-48b7-80c9-fa0a3674c16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>board_of_directors</value>
      <webElementGuid>afa99135-95a8-4d91-92bc-c7bfc79745ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>85</value>
      <webElementGuid>193b3600-ae32-4fc8-b5a6-bcfab1a6a8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1446560994.446_board_of_directors</value>
      <webElementGuid>14bba94f-b6c9-4a98-9c31-fa559c39f91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1446560994.446][board_of_directors]</value>
      <webElementGuid>d2824083-d4fd-4906-a0e1-737805eae62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7990676a-15e0-4bb8-8472-a55dcdadadbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3011013-8b27-48a5-8cbd-1189c71582e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Appropriate webpage address here or enter &quot;Will submit by email&quot;</value>
      <webElementGuid>0057f3c1-c593-4b81-bc8a-de55d9deda1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group-1446560994.446_board_of_directors&quot;)</value>
      <webElementGuid>5e42925a-09ce-482b-836e-6508d5ecdf4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_group-1446560994.446_board_of_directors']</value>
      <webElementGuid>007a5c6b-1a91-4333-b79d-aa72464e52d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446560994.446']/div[11]/div[2]/input</value>
      <webElementGuid>bf5a714f-efa5-4108-a781-120e3ab34b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/input</value>
      <webElementGuid>9a396bee-f0ba-4dd8-abaf-15a5223488b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group-1446560994.446_board_of_directors' and @name = 'registration[group-1446560994.446][board_of_directors]' and @type = 'input' and @placeholder = 'Appropriate webpage address here or enter &quot;Will submit by email&quot;']</value>
      <webElementGuid>52da24c3-bcfd-4dba-9ac7-cee299c817eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
