<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Mission experience served</name>
   <tag></tag>
   <elementGuidId>a015cd22-6542-42df-8d90-0f68b5a926c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1445373964.535_missions_exposure'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a47740d-1e91-4b75-8d83-bb4da4b234ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1445373964.535_missions_exposure</value>
      <webElementGuid>d816d725-e88a-41a0-9b17-f26725f0eb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b3f0cf1a-8b24-4891-ae2a-14aceb3d1aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1445373964.535][missions_exposure][]</value>
      <webElementGuid>6f2e0099-81ff-49fa-b1ef-afd873f8346e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I have served in ministry or missions full time</value>
      <webElementGuid>984ea142-67d9-4254-b132-f7bbd0c9d3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1445373964.535&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-small-checkbox&quot;]/div[3]/input[@id=&quot;profile_group-1445373964.535_missions_exposure&quot;]</value>
      <webElementGuid>9be41430-7ce7-49e5-a148-3351d495a85e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1445373964.535_missions_exposure'])[3]</value>
      <webElementGuid>0443414b-f2d0-4319-8c45-421f5fc0d171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1445373964.535']/div[5]/div[2]/div/div[3]/input</value>
      <webElementGuid>1ac3ce9d-b0eb-4966-8fcb-2e1a1c1b26e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[5]/div[2]/div/div[3]/input</value>
      <webElementGuid>6dd35108-cf2e-417e-bfbd-5d3f43df4dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1445373964.535_missions_exposure' and @type = 'checkbox' and @name = 'profile[group-1445373964.535][missions_exposure][]']</value>
      <webElementGuid>286c52b3-006a-478b-9f72-c8592af048ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
