<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Affiliated with a church No</name>
   <tag></tag>
   <elementGuidId>1d86eac3-8c5e-4269-8c3d-ee47d31aca15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='profile[group-1445373964.535][affiliated_with_church]'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59d7ba33-90c4-4069-a50e-13f30fa1746a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6b8241be-207f-4570-9c00-12a44fe9fc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custom-field</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>678dce46-c5a4-4c35-ae90-19c426ff189f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependant</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>31fdb063-6016-43ce-b666-43fc40d1ce96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>affiliated_with_church</value>
      <webElementGuid>012eab39-f03c-40b8-ab6a-253d7fe43b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>307</value>
      <webElementGuid>c0ad276c-0db3-4c03-bea0-8fcd089941b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1445373964.535][affiliated_with_church]</value>
      <webElementGuid>aa4b23cc-f692-4b7f-ab40-8f653bdab5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>No</value>
      <webElementGuid>0290d921-3a1b-4bcf-944a-e8758ec14586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1445373964.535&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[1]/input[2]</value>
      <webElementGuid>cd95aae0-2615-4e76-83d7-d9892a9f6ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='profile[group-1445373964.535][affiliated_with_church]'])[2]</value>
      <webElementGuid>ced23ddf-73a5-45cb-8606-d681100d25b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1445373964.535']/div[7]/div[2]/div/input[2]</value>
      <webElementGuid>950f3b50-aec7-4e6d-a2d3-bb3153a2c84c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input[2]</value>
      <webElementGuid>45bdf354-feb2-4d51-a18b-4af94c410d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'profile[group-1445373964.535][affiliated_with_church]']</value>
      <webElementGuid>6522e80c-6e41-423f-80b8-7c4550ffe150</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
