<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ministry Preferences</name>
   <tag></tag>
   <elementGuidId>2b980b3b-5b38-46a5-baa8-f3547629fd05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1446522088.64_ministry_preferences']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a0c9a12-d940-477a-b62a-0a2525001fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446522088.64_ministry_preferences</value>
      <webElementGuid>877b77eb-7c6b-421b-889e-b9216a889bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>943469ca-81ee-4d41-8422-0f8d5eb34745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446522088.64][ministry_preferences][]</value>
      <webElementGuid>f8562611-bef8-4e52-960a-211c7df6f35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Adult Men</value>
      <webElementGuid>5856c9ca-2383-46e7-a085-2fbb0334c0d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1446522088.64&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1446522088.64_ministry_preferences&quot;]</value>
      <webElementGuid>0c624e96-7ed7-4a6c-8ebe-07fa3a687a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1446522088.64_ministry_preferences']</value>
      <webElementGuid>9abbc8ca-f60b-433f-8c3e-f5b59a5a91a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446522088.64']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>28ec976d-b785-40c8-9779-d3d87153f138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>672e4b18-ef6d-4f72-90f9-c12508d9ad75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1446522088.64_ministry_preferences' and @type = 'checkbox' and @name = 'profile[group-1446522088.64][ministry_preferences][]']</value>
      <webElementGuid>fefc284b-a708-41fd-93f9-25ca7f398e90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
