<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Need Specific IT Positions</name>
   <tag></tag>
   <elementGuidId>752b0465-cea3-4207-a27d-4eecce33572d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1446522088.64_need_specific_it_positions?']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19b71243-5454-4842-981f-4a15216d87e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependant</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a868bff6-8ff0-475a-9d88-5e9add6f86a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>need_specific_it_positions?</value>
      <webElementGuid>e910970f-3cd6-42d7-9bef-f60322b0844d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>175</value>
      <webElementGuid>abfd8488-8475-4856-ac1e-4166a5fe160f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446522088.64][need_specific_it_positions?]</value>
      <webElementGuid>c62497ba-6e2d-4ec2-bfd4-5f7b6d5b7baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446522088.64_need_specific_it_positions?</value>
      <webElementGuid>96cff7c4-1cef-4e30-b619-b00ed7bb8473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e60c29eb-1957-4dba-920b-e9a5be2b4df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5faac763-6f04-4283-aa69-b43ef2f9eb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1446522088.64_need_specific_it_positions?&quot;)</value>
      <webElementGuid>e764a7e4-158b-47d2-8bc6-ccbcf3143129</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1446522088.64_need_specific_it_positions?']</value>
      <webElementGuid>54edce69-5cf9-4f18-97c8-a19654d19946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446522088.64']/div/div[3]/input[2]</value>
      <webElementGuid>7213aa2b-412e-4338-9874-976d1443d6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>778df7b9-1e4e-482b-8cc0-014f1d232915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'profile[group-1446522088.64][need_specific_it_positions?]' and @id = 'profile_group-1446522088.64_need_specific_it_positions?' and @type = 'checkbox']</value>
      <webElementGuid>bc26ae1b-54a1-4c56-b05c-8e927d419e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
