<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Other People Group</name>
   <tag></tag>
   <elementGuidId>9c779a3d-cd34-450d-920b-890a13a610ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='profile_group-1446522088.64_other_people_group']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>14cca931-894f-419a-ab9f-c8a8ad631e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>other_people_group</value>
      <webElementGuid>4c6f524d-4601-4197-b04d-e811bfa5ae55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>176</value>
      <webElementGuid>255bf316-013b-4523-8ac0-ffc3f3c9f60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-medium-field</value>
      <webElementGuid>62aa98f3-d9fd-4cc5-b29e-f7ba2ab2098c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446522088.64][other_people_group]</value>
      <webElementGuid>33b85b05-543c-4fa2-a31d-691d2050a09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446522088.64_other_people_group</value>
      <webElementGuid>e469bdf1-47b1-4676-b832-972c7e525f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1446522088.64_other_people_group&quot;)</value>
      <webElementGuid>913dcab6-cb7e-4670-9e46-8b2e0e0e8fb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='profile_group-1446522088.64_other_people_group']</value>
      <webElementGuid>32a3ffd4-b75e-4210-a977-ecab18067e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446522088.64']/div[3]/div[3]/textarea</value>
      <webElementGuid>5307292d-ddb5-4d09-b1dd-64263a48969d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/textarea</value>
      <webElementGuid>58295100-2b81-42cf-b883-b71f94ce3252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'profile[group-1446522088.64][other_people_group]' and @id = 'profile_group-1446522088.64_other_people_group']</value>
      <webElementGuid>102e1b8e-23a6-4499-a7f8-33902c4612d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
