<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Within 12 months</name>
   <tag></tag>
   <elementGuidId>f5cd78af-6118-417c-b2b3-d79a3ceb37fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1456436314.404_available_start_options'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0405d242-a307-4a5e-bebc-bb4899dbbb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1456436314.404_available_start_options</value>
      <webElementGuid>d2d97d06-99e5-49e0-8cfb-7a009dee6e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3d016ee9-1790-453b-9e0d-f7b934446f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1456436314.404][available_start_options][]</value>
      <webElementGuid>3331ba0a-9b8c-4f80-af71-3b3767fd2c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Within 12 months</value>
      <webElementGuid>3d5416c8-0fb6-4459-8b4d-b441ceae77fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1456436314.404&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[2]/input[@id=&quot;profile_group-1456436314.404_available_start_options&quot;]</value>
      <webElementGuid>4e09bcc8-3a42-4700-a68c-7cd721b7427e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1456436314.404_available_start_options'])[2]</value>
      <webElementGuid>277fc1fb-4061-4eb5-be8d-89632149fd38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1456436314.404']/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>9c21e150-5bf1-42ee-be8a-8c4a1cca872b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>96262e34-b740-4f53-b58b-f26a9c8c720f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1456436314.404_available_start_options' and @type = 'checkbox' and @name = 'profile[group-1456436314.404][available_start_options][]']</value>
      <webElementGuid>a65bbe2b-6919-4e8d-8ff0-cd1932b31fbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
