<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spring Semester</name>
   <tag></tag>
   <elementGuidId>d770fb25-b9ed-484e-9a3f-b5ef79f4ad31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1456436314.404_school_term_available'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e82f628c-5e7c-4c27-9ac0-4d974129fc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1456436314.404_school_term_available</value>
      <webElementGuid>96a94737-8127-4727-89aa-2a728288def5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b28401ed-5f44-4036-b904-9d18d3799cbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1456436314.404][school_term_available][]</value>
      <webElementGuid>a77865e6-f731-4319-a1a3-793fc2079a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Spring Semester</value>
      <webElementGuid>9328003f-62ef-4f94-a0e7-555478391802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1456436314.404&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[2]/input[@id=&quot;profile_group-1456436314.404_school_term_available&quot;]</value>
      <webElementGuid>1acd63d9-0580-45e5-9ed1-b9fcc5220e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1456436314.404_school_term_available'])[2]</value>
      <webElementGuid>06a80c37-ce1f-40ac-b175-024a53ca450a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1456436314.404']/div[3]/div[3]/div/div[2]/input</value>
      <webElementGuid>9c873806-ac23-4d2a-bc1b-3060e1548996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div[2]/input</value>
      <webElementGuid>14199d69-0e89-443e-899f-39c6da7d0d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1456436314.404_school_term_available' and @type = 'checkbox' and @name = 'profile[group-1456436314.404][school_term_available][]']</value>
      <webElementGuid>8e547aa8-4125-4285-8796-39b7bd47cbd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
