<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Abbreviation</name>
   <tag></tag>
   <elementGuidId>d75a9827-f7ef-4f6c-a7a2-18ce3f518584</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1455511671.32_abbreviation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b519b8e0-76fb-451f-a153-a5b3cbafd960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>abbreviation</value>
      <webElementGuid>28b68522-d97f-4cce-9268-5363e1803078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ef8bf53c-7ba0-4850-a04c-de5759b14f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1455511671.32_abbreviation</value>
      <webElementGuid>3d153203-2138-4d29-951a-8bf7b66ff6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1455511671.32][abbreviation]</value>
      <webElementGuid>f96045e9-093f-4263-9bb2-fc1086087213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b46c96f-7a5c-4c25-a7e4-9daeecbe2d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff65ae5a-38d8-41c8-94ea-1fac06b46ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>cktest03ja</value>
      <webElementGuid>84d35481-29de-476b-97dc-58c8bc506e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1455511671.32_abbreviation&quot;)</value>
      <webElementGuid>6be3977a-9bae-48d3-9389-ead4786c1f1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1455511671.32_abbreviation']</value>
      <webElementGuid>eaf08b1e-4c7a-4b9e-8929-c7fa4010b5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1455511671.32']/div[2]/div[2]/input</value>
      <webElementGuid>30d65cff-6f7e-4b28-a705-8a378bb6ab3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/input</value>
      <webElementGuid>9a5e7e6c-e1d8-4e0a-87ae-273865e250bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1455511671.32_abbreviation' and @name = 'profile[group-1455511671.32][abbreviation]' and @type = 'input']</value>
      <webElementGuid>a0314991-c73b-4acc-a365-77f1aaea1a1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
