<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privacy</name>
   <tag></tag>
   <elementGuidId>e010a88b-b8eb-401f-aa0c-4a3b6ddd3332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-77204 > a.elementor-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/footer/div/nav/a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d69d60db-231a-441a-933c-75ef66c74acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionworks.global/privacy-policy/</value>
      <webElementGuid>5f40178e-3249-4074-b015-388cc8b12446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-item</value>
      <webElementGuid>c14dfd9a-beb3-4f50-ab3b-4e5f7ccb8353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privacy</value>
      <webElementGuid>0904e096-1681-499c-9ccc-7a7af16e0dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-1-a814b52&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-77204&quot;]/a[@class=&quot;elementor-item&quot;]</value>
      <webElementGuid>a272414e-30e1-4e25-8a4a-45eac25b2ac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='menu-1-a814b52']/li[4]/a</value>
      <webElementGuid>ce5a6149-e310-499a-9d5e-01fa7876ecda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Privacy')])[2]</value>
      <webElementGuid>f7f8f46b-9179-4ae8-894b-9c952ede5e01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::a[1]</value>
      <webElementGuid>4befbe3b-19c2-4049-bd49-6a8cc751c1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sponsorship'])[1]/following::a[2]</value>
      <webElementGuid>f3a20eb0-88f8-47c6-8904-d43e1e44b9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donate'])[5]/preceding::a[1]</value>
      <webElementGuid>cd912e70-7bad-4490-9c45-1b3f76733108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[3]/preceding::a[2]</value>
      <webElementGuid>2aaac102-c9e1-4586-9e98-725cca099b16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Privacy']/parent::*</value>
      <webElementGuid>690b9549-da68-4ecb-9149-cb62cf1027b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://missionworks.global/privacy-policy/')]</value>
      <webElementGuid>a2f77576-4466-4978-b2e3-daf6906943ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div/div/nav/ul/li[4]/a</value>
      <webElementGuid>ae51c508-8380-44f9-9c79-780d229333b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionworks.global/privacy-policy/' and (text() = 'Privacy' or . = 'Privacy')]</value>
      <webElementGuid>6dfe3326-462c-4d99-90c5-5e192411f635</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
