<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Gold Transparency</name>
   <tag></tag>
   <elementGuidId>ea678dac-85d8-47a2-8c6c-0442fb91d62a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-77219</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[5]/div/div[1]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3b276b5e-f9c3-4cfb-aeb5-dfc4277180ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>ccb1580d-fcd9-45aa-b34f-d557bb5c1bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>97212eb4-f12e-42a1-9727-ae40ef19eb19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://missionnext.org/wp-content/uploads/2026/05/gold-xPARENCY-1-1-1.svg</value>
      <webElementGuid>4364e8ad-6584-427c-a6ec-7a614ba35de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-77219</value>
      <webElementGuid>aab931dc-aafe-48de-be81-88772a56b65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home wp-singular page-template-default page page-id-55120 page-parent wp-custom-logo wp-embed-responsive wp-theme-generatepress no-sidebar nav-below-header one-container fluid-header active-footer-widgets-3 header-aligned-left dropdown-hover full-width-content elementor-default elementor-template-full-width elementor-kit-22 elementor-page elementor-page-55120 e--ua-firefox e--ua-mac&quot;]/div[@class=&quot;site-footer&quot;]/footer[@class=&quot;elementor elementor-75762 elementor-location-footer&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-34b18e58 elementor-section-boxed elementor-section-height-default elementor-section-height-default wpr-column-slider-no wpr-equal-height-no&quot;]/div[@class=&quot;elementor-container elementor-column-gap-default&quot;]/div[@class=&quot;elementor-column elementor-col-25 elementor-top-column elementor-element elementor-element-747766a3&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-205f589b elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-large size-large wp-image-77219&quot;]</value>
      <webElementGuid>796a27a0-e641-417b-9ff5-0c58011e5abc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://missionnext.org/wp-content/uploads/2026/05/gold-xPARENCY-1-1-1.svg')]</value>
      <webElementGuid>a0886913-42fa-4419-9432-c13066b4e25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[5]/div/div/div/div/div/img</value>
      <webElementGuid>b85e6c31-cfc6-466c-80a1-026b383afc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://missionnext.org/wp-content/uploads/2026/05/gold-xPARENCY-1-1-1.svg']</value>
      <webElementGuid>b39048b3-649f-4972-af96-073030838ed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
