<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_26</name>
   <tag></tag>
   <elementGuidId>01176187-5ea8-4599-81d6-0626c8a41913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_2_26_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_2_26_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6bd7068-95d9-4a63-9338-ed39bc51c159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_26</value>
      <webElementGuid>a9acaa47-4679-4140-a453-1e248833a87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e4154d0d-b422-47a0-9847-81aa4d40e9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gquiz265011b216</value>
      <webElementGuid>e5f383a5-002e-4850-908f-15694bfb78f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_2_26_0</value>
      <webElementGuid>cc0c8e31-7b26-48b7-9e49-da69d0f09935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_2_26_0&quot;)</value>
      <webElementGuid>3bcd1ee5-7140-4bbc-a616-173cac71978a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_2_26_0']</value>
      <webElementGuid>0a0c4cce-ee67-47ad-9328-ea0fefa44b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_2_26']/li/input</value>
      <webElementGuid>77e5a759-5d8b-4351-839c-ceeb3ca44398</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li[2]/div/ul/li/input</value>
      <webElementGuid>1a7d117e-655a-4e8e-84df-bf255c7c6ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_26' and @type = 'radio' and @id = 'choice_2_26_0']</value>
      <webElementGuid>7da4bdf0-8923-462e-9ade-8c9dc5434dca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
