<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_8</name>
   <tag></tag>
   <elementGuidId>53a05cbc-7c77-4e8d-b896-d1af88813961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_2_8_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_2_8_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4fcd4c13-253f-4bd8-bc0f-571f7398d2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_8</value>
      <webElementGuid>b2c4e9ab-9fcb-4937-8901-2debd255c9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d8e6745c-e829-4b7b-a9a3-eedcd91506e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gquiz890ae5957</value>
      <webElementGuid>cf6ee423-dcb0-4108-bbe5-9280bdd5542c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_2_8_0</value>
      <webElementGuid>b828f841-1407-49cb-bd75-74428c78cea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_2_8_0&quot;)</value>
      <webElementGuid>752ee935-1d37-4c31-a7cd-55fc7ca003e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_2_8_0']</value>
      <webElementGuid>eacac326-035b-4f6e-b181-065bbf44ae06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_2_8']/li/input</value>
      <webElementGuid>d1a8d94f-792e-42a1-87e2-69445ca5b1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/input</value>
      <webElementGuid>034a4979-1a70-4d93-83bb-dca2580cd5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_8' and @type = 'radio' and @id = 'choice_2_8_0']</value>
      <webElementGuid>c7aae3b7-f452-42e7-893c-22a7556c8503</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
