<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Very flexible_input_10</name>
   <tag></tag>
   <elementGuidId>dc7c6f1f-6bb2-44c3-84b4-dd26253d781d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_2_10_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_2_10_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>525c6f0f-bcb8-4dfc-b8b8-1f989a7c67a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_10</value>
      <webElementGuid>d1d52975-1c4a-442b-a9f3-ee790cab0b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a6867429-956f-4840-b4bb-ec1eed9eb30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gquiz10e18325ba</value>
      <webElementGuid>503454df-6e96-487a-9701-c08b0ca1cfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_2_10_1</value>
      <webElementGuid>4f2ebc7d-d286-4cc3-9d88-a10701bf8012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_2_10_1&quot;)</value>
      <webElementGuid>034e76f6-e13d-437c-9594-20c08c1654f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_2_10_1']</value>
      <webElementGuid>ddcef3f7-0037-4200-8aa3-eab71167c8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_2_10']/li[2]/input</value>
      <webElementGuid>c3d6e709-ca31-4efa-9bfd-269511d3d5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[4]/div/ul/li[2]/input</value>
      <webElementGuid>6c53b2d6-8142-45a9-b927-ba32b6b688ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_10' and @type = 'radio' and @id = 'choice_2_10_1']</value>
      <webElementGuid>dcf87852-9cb0-4dea-91e9-2974616b3b7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
