<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_27</name>
   <tag></tag>
   <elementGuidId>7686dd2a-1432-45f0-a018-27604e42c913</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_2_27_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_2_27_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b20b2bdd-1710-4811-8810-3b21d1d3c59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_27</value>
      <webElementGuid>fe4b2240-f1e9-4023-845a-2d4551a01217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>edd42bc3-1e41-480b-958e-fbc8d997624b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gquiz2772faa3eb</value>
      <webElementGuid>867dc68d-2fda-4c68-88d4-85e90126cb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_2_27_0</value>
      <webElementGuid>86c51a18-7d96-4a46-805a-9339d69c56de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_2_27_0&quot;)</value>
      <webElementGuid>39363900-5024-4e90-a309-ee1ae410e321</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_2_27_0']</value>
      <webElementGuid>6111138d-bcaf-4566-90fe-2929aad87c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_2_27']/li/input</value>
      <webElementGuid>af55e905-aa6c-44b1-807c-79138bac0bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li[3]/div/ul/li/input</value>
      <webElementGuid>e8414bbb-77df-4593-945e-99ee765f99bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_27' and @type = 'radio' and @id = 'choice_2_27_0']</value>
      <webElementGuid>7b0bd389-3731-41ea-a087-c4e1061d1c71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
