<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I love to learn new things_input_5</name>
   <tag></tag>
   <elementGuidId>559b0f5c-22d6-47a3-bb3c-74aa39640a63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_2_5_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_2_5_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ea99a86e-9ad6-4387-b98e-b5aa3a7b95af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_5</value>
      <webElementGuid>8c34d506-4015-4cc9-835c-4e882a12aeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1fca3a51-a9b1-47c1-805f-d4755dabf6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gquiz50b199b4f</value>
      <webElementGuid>b0a44610-b5b9-4b76-99f9-a558607e7d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_2_5_1</value>
      <webElementGuid>71b1bfd1-c4cd-4f31-9655-5023590f1be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_2_5_1&quot;)</value>
      <webElementGuid>11e0bb80-a6ac-41b0-9b3f-0df3516338a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_2_5_1']</value>
      <webElementGuid>a95fedff-b305-4fa2-b1e1-da65ccd99cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_2_5']/li[2]/input</value>
      <webElementGuid>015d7e52-275a-4bda-bf58-18d5e0c96f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/ul/li[2]/input</value>
      <webElementGuid>e66e8a65-f1ba-4d13-b5df-7aa4dbe3b65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_5' and @type = 'radio' and @id = 'choice_2_5_1']</value>
      <webElementGuid>b5373eea-89a5-42d0-8ed6-8bc87d097697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
