<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lies come easily to help me stay out _fe88f5</name>
   <tag></tag>
   <elementGuidId>db063c67-ca1c-4de5-a7bf-4ceba761d97a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gform_next_button_2_19</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gform_next_button_2_19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>913f5d2a-f5a4-4f17-a8b8-82ee3745602d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25a2dc90-efec-48a4-acfb-c40c24ded6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gform_next_button_2_19</value>
      <webElementGuid>d05950cb-742a-4631-a8b6-82e6b5d6ee27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gform_next_button gform-theme-button button</value>
      <webElementGuid>b67d836d-6979-4abe-9e7a-be0eb3e93f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>b82b24c5-ee83-4e90-b690-7aadb01a9e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery(&quot;#gform_target_page_number_2&quot;).val(&quot;4&quot;);  jQuery(&quot;#gform_2&quot;).trigger(&quot;submit&quot;,[true]); </value>
      <webElementGuid>39b11bad-b161-4620-af46-72734001532b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if( event.keyCode == 13 ){ jQuery(&quot;#gform_target_page_number_2&quot;).val(&quot;4&quot;);  jQuery(&quot;#gform_2&quot;).trigger(&quot;submit&quot;,[true]); } </value>
      <webElementGuid>e053147a-5328-4b6b-8f3b-f974be287862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gform_next_button_2_19&quot;)</value>
      <webElementGuid>05724ce9-57cb-40a7-b2e8-b3b88ecb87ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gform_next_button_2_19']</value>
      <webElementGuid>2a8e7d06-9ca1-45ed-a822-e5bad7a9b540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gform_page_2_3']/div[2]/input[2]</value>
      <webElementGuid>1b3da572-3844-4f00-ba95-68b9315872ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input[2]</value>
      <webElementGuid>2ae839e5-0f1a-4732-8cd2-9d417e3d7cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'gform_next_button_2_19']</value>
      <webElementGuid>30a5f30a-1fe6-43e1-b83f-326a25164721</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
