<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I sometimes share the gospel with the_aabfbd</name>
   <tag></tag>
   <elementGuidId>53bc56ea-cc12-43ee-aabf-e690395c38fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_2_3_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_2_3_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d155a9b9-2e6a-4d3a-b21a-4e34d356e446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_3</value>
      <webElementGuid>4bc8cfe7-347f-4d10-b8c9-fde913cbc9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3558a206-c114-46d5-8940-761caf63bb2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gquiz3800d03d7</value>
      <webElementGuid>0737929d-70c7-48af-8389-f9f0137b6caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_2_3_2</value>
      <webElementGuid>731a79cf-a1f0-4806-bdeb-cb07dfb485ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_2_3_2&quot;)</value>
      <webElementGuid>1ceea484-3bea-449b-b040-455651b55390</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_2_3_2']</value>
      <webElementGuid>7325e92c-6965-4133-9906-709a2e778e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_2_3']/li[3]/input</value>
      <webElementGuid>5d6588e6-8ee7-422a-86df-12be6cff5460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/ul/li[3]/input</value>
      <webElementGuid>ce8a19eb-92eb-46bb-86b0-f13744dc7383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_3' and @type = 'radio' and @id = 'choice_2_3_2']</value>
      <webElementGuid>9c6f3fb8-81bf-4778-9f5a-cebd0857f6e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
