<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_28</name>
   <tag></tag>
   <elementGuidId>ae97cbd2-797d-4c43-9389-daea09b283d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_2_28_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_2_28_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d4eb0a5-f48a-4aa6-9796-8d7372ad421c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_28</value>
      <webElementGuid>52ee929a-58fb-482b-97e6-2f8e2a2ca577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0ab6d513-e712-40aa-afbd-7bb2aa901bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gquiz28e218b90e</value>
      <webElementGuid>20191994-0625-4965-b673-659b09cb6124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_2_28_0</value>
      <webElementGuid>314d4880-c8d6-4410-af3f-44601d80a2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_2_28_0&quot;)</value>
      <webElementGuid>ae230a1e-7bb3-4074-8cce-4fcefb88f1da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_2_28_0']</value>
      <webElementGuid>625d3f39-4deb-41d9-b02a-67df5ccc3672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_2_28']/li/input</value>
      <webElementGuid>6aaca4c0-a21f-43a1-9219-32f1b4d8b46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/ul/li[4]/div/ul/li/input</value>
      <webElementGuid>9f9b1951-718f-489d-8638-773b661d53a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_28' and @type = 'radio' and @id = 'choice_2_28_0']</value>
      <webElementGuid>5657208e-78d2-424a-a3cb-9e1b78495c58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
