<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_20</name>
   <tag></tag>
   <elementGuidId>3de689c2-14aa-4936-899d-400303a0167d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choice_2_20_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='choice_2_20_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24d69ff9-a689-41fe-8a06-cb039425aa36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_20</value>
      <webElementGuid>f1cd68d3-19e8-42e7-a6ab-a604c50d8407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>5b999351-b6b5-4652-8023-fb0ad5e93ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>gquiz200239b8e5</value>
      <webElementGuid>b029b1b4-5967-453d-b088-f3b69ee53ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choice_2_20_0</value>
      <webElementGuid>60327c7d-0bc5-460c-a998-a22e9bd265af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choice_2_20_0&quot;)</value>
      <webElementGuid>57ecb853-ad44-49c8-b169-41f8c06fe151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='choice_2_20_0']</value>
      <webElementGuid>08edb744-3466-476f-9678-7b0a20ccaee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='input_2_20']/li/input</value>
      <webElementGuid>5bdaf73c-87c5-4235-9513-0b2909da9ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/ul/li[2]/div/ul/li/input</value>
      <webElementGuid>5532b428-bdd8-46f2-ac84-84cf36219b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'input_20' and @type = 'radio' and @id = 'choice_2_20_0']</value>
      <webElementGuid>d61b56e0-3a5b-4eeb-86d6-f34034c5481d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
