<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spouse Preferred Position(s)</name>
   <tag></tag>
   <elementGuidId>e4ca6956-78b3-45e9-b3ce-92fd0debc55c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1631421470.837_spouse_ministry_preferences']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f760ff6-212f-43ff-aff7-f4a66ff477b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1631421470.837_spouse_ministry_preferences</value>
      <webElementGuid>aefd1c23-16c1-43ac-a8d5-fb67a9884fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>63250ba7-72ab-41c3-adb3-0b2cacffae94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1631421470.837][spouse_ministry_preferences][]</value>
      <webElementGuid>f9793f12-dae6-4164-840b-097d551f2d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Adult Men</value>
      <webElementGuid>4d21a83e-8ac3-4d55-88b5-929791041428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1631421470.837&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1631421470.837_spouse_ministry_preferences&quot;]</value>
      <webElementGuid>cf64af03-4268-4fee-9e13-70f0706255c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1631421470.837_spouse_ministry_preferences']</value>
      <webElementGuid>eb0122ca-7907-468f-b0f0-00223ccbf9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1631421470.837']/div/div[3]/div/div/input</value>
      <webElementGuid>331f3336-8592-465a-86f6-b749b54fa1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[3]/div/div/input</value>
      <webElementGuid>323c3549-4925-4337-9ef7-63a24ae57d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1631421470.837_spouse_ministry_preferences' and @type = 'checkbox' and @name = 'profile[group-1631421470.837][spouse_ministry_preferences][]']</value>
      <webElementGuid>f50b764d-d8fc-48db-bad5-f33234532bf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
