<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Preferred Position(s)-parm</name>
   <tag></tag>
   <elementGuidId>ac2bbdde-d005-49c5-a5f3-e0e3cae9fe83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1623987608.435_ministry_preferences']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'profile_group-1623987608.435_ministry_preferences' and @type = 'checkbox' and @name = 'profile[group-1623987608.435][ministry_preferences][]' and @value = '${position}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be6e0905-23c9-4902-b0ec-2653d7f0c7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623987608.435_ministry_preferences</value>
      <webElementGuid>d025cde5-ad2e-405b-862c-7855a6124df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>507fd6b1-f54c-4ad0-a12d-fd86441ccbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623987608.435][ministry_preferences][]</value>
      <webElementGuid>120b9f88-04d5-4c36-9c3b-98c653196163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>${position}</value>
      <webElementGuid>ac8659a9-3667-4192-9952-14c2e2f446ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1623987608.435&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1623987608.435_ministry_preferences&quot;]</value>
      <webElementGuid>76b4fd5e-6c49-45ab-952d-335256acbd0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1623987608.435_ministry_preferences']</value>
      <webElementGuid>7407f5b8-008e-4a51-87be-92be91d18a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623987608.435']/div[2]/div[3]/div/div/input</value>
      <webElementGuid>8ce74b3b-8df5-45e1-b1e3-9695e5f8c921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[3]/div/div/input</value>
      <webElementGuid>9915b667-6ae4-4824-96c6-5d5470b9e5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1623987608.435_ministry_preferences' and @type = 'checkbox' and @name = 'profile[group-1623987608.435][ministry_preferences][]' and @checked = 'checked']</value>
      <webElementGuid>da85ad80-f92a-461b-97b1-138ee34a2449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
