<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Match Percent Rate</name>
   <tag></tag>
   <elementGuidId>24887dc4-ff93-4c78-9368-d7797ef9f22b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='profile_group-1446521957.744_match_rate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c13b370b-660a-4456-98f1-6f8bc83f973f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>match_rate</value>
      <webElementGuid>c966b158-a00b-4c92-a708-70415058b811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>161</value>
      <webElementGuid>dbbc3565-388b-45ca-b19a-a3f76a5fdb75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446521957.744][match_rate]</value>
      <webElementGuid>a0255511-c4ed-40da-933d-cd98e9136d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446521957.744_match_rate</value>
      <webElementGuid>13d405e6-f33c-49f1-9e70-1d02fb5e0ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
10
20
30
40
50
60
70
80
90
</value>
      <webElementGuid>94155256-c4e8-435b-b6ae-0d7787550a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1446521957.744_match_rate&quot;)</value>
      <webElementGuid>0b09ab34-50db-4119-b3fe-d4ff947d3772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='profile_group-1446521957.744_match_rate']</value>
      <webElementGuid>010e85e4-749f-4705-8516-49352e5009ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446521957.744']/div[3]/div[2]/select</value>
      <webElementGuid>d991e2d9-9d7d-4d5a-b464-89b214845e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Match Percent Rate'])[1]/following::select[1]</value>
      <webElementGuid>7c3e7c4a-c7a7-4de1-bb4f-5ba10e4023c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The financial support field is required.'])[1]/following::select[1]</value>
      <webElementGuid>fe5fe443-9402-4f44-8c99-6f91a7aed9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Years'])[1]/preceding::select[1]</value>
      <webElementGuid>753d9dc3-e747-4b70-a84c-2fe63f7b750d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::select[1]</value>
      <webElementGuid>9ce01fc5-183f-4b12-bb22-ddbc093ac049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>5eee0d46-bed3-43a4-a839-4f4a4e4aad1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'profile[group-1446521957.744][match_rate]' and @id = 'profile_group-1446521957.744_match_rate' and (text() = '
10
20
30
40
50
60
70
80
90
' or . = '
10
20
30
40
50
60
70
80
90
')]</value>
      <webElementGuid>cc7b7d52-d61c-48ea-9487-f569676141a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
