<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_IT Skills and Interest TAB</name>
   <tag></tag>
   <elementGuidId>55b0af1c-f61f-4d5d-9b50-05d216ff04dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c90565a0-ea85-4f7f-891e-0c3ca95aecf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#group-1694660169.099</value>
      <webElementGuid>fb950bf8-b2ff-4a32-bcb5-fcd7eb4cb942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dependent-group ui-tabs-anchor</value>
      <webElementGuid>be059b64-e8b9-494d-a203-73caee41f53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>group-1694660169.099</value>
      <webElementGuid>a6fa6483-ab06-4a72-86ec-6d633e4b271c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-depends-on</name>
      <type>Main</type>
      <value>interested_in_it</value>
      <webElementGuid>a049827c-520f-4ae1-b6b4-41a927ddfe02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>97d00135-766a-4430-b18e-a11ab077508c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-7</value>
      <webElementGuid>b23d7546-a85d-4a49-89ca-8fb226061a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IT Skills and Interest</value>
      <webElementGuid>272b8096-fe69-4be9-86d9-51ca1f6a1557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-7&quot;)</value>
      <webElementGuid>6227d72d-2196-4369-aa9c-103337a23c7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-7']</value>
      <webElementGuid>2b49e4e4-c73a-4a11-95c0-74e701295a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/ul/li[7]/a</value>
      <webElementGuid>7ab650f7-d40d-4851-b222-7e3d0ce6d59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'IT Skills and Interest')]</value>
      <webElementGuid>8175f1b7-b208-48a9-ae28-986dd092a6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Ministry Prefs'])[1]/following::a[1]</value>
      <webElementGuid>f9146c14-0e92-473b-acaf-d8008f90e680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service/Comment'])[1]/following::a[2]</value>
      <webElementGuid>8a31a9af-1429-4bcd-bae2-2dae71b8d62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Info'])[1]/preceding::a[1]</value>
      <webElementGuid>c5c42949-e8a1-4372-8580-c6a0443727ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Experience'])[1]/preceding::a[2]</value>
      <webElementGuid>55d8525a-c5e3-4771-b089-afd405a671d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IT Skills and Interest']/parent::*</value>
      <webElementGuid>43bc106d-f639-4da7-9460-37d05a61cacb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#group-1694660169.099')]</value>
      <webElementGuid>4f5a38e6-305c-4a87-9c80-0622eb7d3ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[7]/a</value>
      <webElementGuid>303e3d3c-91d9-40b2-bbca-865acf70c447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#group-1694660169.099' and @id = 'ui-id-7' and (text() = 'IT Skills and Interest' or . = 'IT Skills and Interest')]</value>
      <webElementGuid>e686fdf6-f36f-4fab-be2f-9a9ed8b0b992</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
