<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name</name>
   <tag></tag>
   <elementGuidId>a7439a11-551e-4d77-8718-2e7e570e0750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration_group1_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_group1_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e536eead-f74c-43b7-94a0-b8b07dd32ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-input mn-medium-field</value>
      <webElementGuid>00857d99-d6a4-4175-9af7-6380ff07e407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>5a256652-e51d-46fc-a0e1-4788164bf3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>6a23df66-4cc8-421a-afad-3ae07b7fefe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group1_last_name</value>
      <webElementGuid>c4b3eb2b-ffcf-40a5-a54f-48490ed5608e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group1][last_name]</value>
      <webElementGuid>488379dc-15f2-4fd8-b03b-d447dedeedc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd2bb337-92f6-4511-838e-d8a27757424a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7be7e5ce-0d33-4e24-ac15-b2ae2e170f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group1_last_name&quot;)</value>
      <webElementGuid>65f637d5-ab2c-4041-8645-c091fa2c3bef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_group1_last_name']</value>
      <webElementGuid>0abeefb9-54b5-4985-9974-e61cdbcc8ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[2]/div[2]/input</value>
      <webElementGuid>fb5df44c-da5c-4a09-a57e-0b033f74c935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/input</value>
      <webElementGuid>291f87f8-93ca-4509-ab18-d35da4a25030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group1_last_name' and @name = 'registration[group1][last_name]' and @type = 'input']</value>
      <webElementGuid>c7dc8546-bd62-4139-83bb-930d8b27052e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
