<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Preferred Region(s) - Parm</name>
   <tag></tag>
   <elementGuidId>ac9da62a-f1c1-42c9-b0d2-af28c91b54d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1623987079.732_region_preferences']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5add3def-ed35-4f01-8b98-ed62b63d9ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623987079.732_region_preferences</value>
      <webElementGuid>b98b50c6-eb1f-4f87-b468-95e7aca57ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dc6c00a7-f7c9-4925-a2b3-2dbe90b5e8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623987079.732][region_preferences][]</value>
      <webElementGuid>ce87a7d2-5ecd-4973-8e7d-d85ce91dcfb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Africa, North</value>
      <webElementGuid>842e909b-b332-44e5-9b3f-11a57814c336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1623987079.732&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1623987079.732_region_preferences&quot;]</value>
      <webElementGuid>dc598551-f437-4e65-a081-f7168d35a79a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1623987079.732_region_preferences']</value>
      <webElementGuid>7203d7c7-2b45-4b3f-b3dd-e9858984ce46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623987079.732']/div/div[3]/div/div/input</value>
      <webElementGuid>fef61c7a-6700-41c9-a537-fd53619daa0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[3]/div/div/input</value>
      <webElementGuid>7a03e40c-507f-463d-9d16-6f2b3590f0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1623987079.732_region_preferences' and @type = 'checkbox' and @name = 'profile[group-1623987079.732][region_preferences][]']</value>
      <webElementGuid>f998a263-cba3-4a73-8cd0-61a0c67e54ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
