<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Terms and Conditions_registrationgrou_47df81</name>
   <tag></tag>
   <elementGuidId>320e99a6-cd13-4aad-9200-edfd57925a97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration_group1_terms_and_conditions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_group1_terms_and_conditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>273426ad-3c3f-43d8-b501-4d7611c11c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-boolean </value>
      <webElementGuid>2832bbe1-b217-4b47-b970-da2790040003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>61b6f188-8f88-4bad-879a-2a90ba33ac2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>337</value>
      <webElementGuid>53f24d36-318e-4cc6-8896-7583ff17548d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group1][terms_and_conditions]</value>
      <webElementGuid>c0cb7fc7-1b7b-481d-928c-3ae102042fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group1_terms_and_conditions</value>
      <webElementGuid>01390cca-003a-4488-a023-8caa1522aebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c12de5e9-2bf3-46a1-8fcc-5f9c1c2d7f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bccc2bbb-7ade-4284-b471-db231e96105c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group1_terms_and_conditions&quot;)</value>
      <webElementGuid>4fe93077-1560-47d6-871a-27cd7fed91de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_group1_terms_and_conditions']</value>
      <webElementGuid>68cbebbb-98f0-4e9d-b9f0-a1ebeea854df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[8]/div[3]/input</value>
      <webElementGuid>a798b611-f7ea-406c-baa5-46ec0ce9bef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/input</value>
      <webElementGuid>79d034f0-ec8b-4f41-afb4-ab16d66611dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'registration[group1][terms_and_conditions]' and @id = 'registration_group1_terms_and_conditions' and @type = 'checkbox']</value>
      <webElementGuid>39466c7e-9722-49f6-99f1-b829a1cae1ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
