<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Bible training minimal</name>
   <tag></tag>
   <elementGuidId>c9ed1741-bfe8-4320-9af9-5e4ba797f77d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;profile[group-1445373964.535][bible_training]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;group-1445373964.535&quot;]/div[2]/div[2]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f56c8ab-b41a-4a83-b1b0-e1cea07a6775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c89f3533-c413-43d6-af1e-bb5ae19693fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>bible_training</value>
      <webElementGuid>6a93350b-d3eb-48dc-ae7a-aa6376f2d862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>284</value>
      <webElementGuid>a3fb6f6a-9a42-43d8-82d8-de3ea40bdfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1445373964.535][bible_training]</value>
      <webElementGuid>2fe9ee01-d6d2-4595-8936-3608fd0839e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Minimal Bible training</value>
      <webElementGuid>e3b3a429-10cc-46cf-b1eb-1f3e97fd1bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1445373964.535&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[1]/input[1]</value>
      <webElementGuid>2aef4944-770f-4b16-bbdd-16c4af12e18c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='profile[group-1445373964.535][bible_training]']</value>
      <webElementGuid>05ba69ce-58f2-4641-93ec-05c63735e69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1445373964.535']/div[2]/div[2]/div/input</value>
      <webElementGuid>5d34ce14-ecc9-477f-95aa-a043782054e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>e7648099-f311-49e7-86a3-ce23ca6b4390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//*[@id=&quot;group-1445373964.535&quot;]/div[2]/div[2]/div[1]/input</value>
      <webElementGuid>08c2a641-1d13-4e1b-85c4-17f72cb56b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
