<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Bible training degree</name>
   <tag></tag>
   <elementGuidId>d62c4fa9-0dac-4cf8-9707-dcfaa4b5bb1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(4) > input[name=&quot;profile[group-1445373964.535][bible_training]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='profile[group-1445373964.535][bible_training]'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>856779bc-7c1c-4b28-8796-55efcbf02c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>21f63807-2ae7-4856-8bd4-6aba7ca6a482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>bible_training</value>
      <webElementGuid>978217f9-8204-48a6-8e08-a71342608410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>284</value>
      <webElementGuid>68cc585e-04dc-4c24-b413-24129c501353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1445373964.535][bible_training]</value>
      <webElementGuid>2c824978-e991-4a42-b21d-f69c7532064a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Bible school degree or equivalent</value>
      <webElementGuid>7eff1b61-abe0-441f-8c19-31a13b56fba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1445373964.535&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[4]/input[1]</value>
      <webElementGuid>1ae4f739-ec93-4cc6-aeb5-dedb861d6070</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='profile[group-1445373964.535][bible_training]'])[4]</value>
      <webElementGuid>f4d5d5f1-cd81-4fe9-b73d-83774d8ee545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1445373964.535']/div[2]/div[2]/div[4]/input</value>
      <webElementGuid>900437d0-bdfd-4be8-9482-408f18fc410e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>79fcebd8-acce-466a-9b7f-fbf666795917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'profile[group-1445373964.535][bible_training]']</value>
      <webElementGuid>67998dee-f997-4daf-9d9a-6348e5826425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
