<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_Affiliated with a church Yes</name>
   <tag></tag>
   <elementGuidId>19d096ac-4bc5-4674-85d2-24f1815b4a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;profile[group-1445373964.535][affiliated_with_church]&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;group-1445373964.535&quot;]/div[7]/div[2]/div/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9263f24-1480-493d-a2cb-710457fb3920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>67de97d2-55f2-49a5-95f7-b88f4114f3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>custom-field</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8ecd7c34-9c47-4467-8608-4c00ef4d02d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependant</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>46e9e5ff-cb0f-42fc-89f5-1a0ba16d4ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>affiliated_with_church</value>
      <webElementGuid>7d0a6e28-a098-4ebc-9bb0-deb07abba733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>307</value>
      <webElementGuid>aa64d44d-54a5-41df-8e20-d616f44c5a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1445373964.535][affiliated_with_church]</value>
      <webElementGuid>56897e90-cf88-4e7f-b22b-77376f126632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>bf77bb0d-16f1-4907-a4a2-099d37222015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>bcfbb3fa-4b7d-4401-aadd-de2e2de83b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1445373964.535&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[1]/input[1]</value>
      <webElementGuid>9c8fe664-ab85-49fa-8678-2eba17b254f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='profile[group-1445373964.535][affiliated_with_church]']</value>
      <webElementGuid>de21d9c4-bf35-4fa9-83eb-8b2d7b81f5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1445373964.535']/div[7]/div[2]/div/input</value>
      <webElementGuid>4b2d43c3-5218-429f-ad19-637fcd8b172c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[7]/div[2]/div/input</value>
      <webElementGuid>9b5bac45-ba67-48a3-96d4-5074f4689fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//*[@id=&quot;group-1445373964.535&quot;]/div[7]/div[2]/div/input[1]</value>
      <webElementGuid>d0f51005-d12d-4b6b-8eb5-c3e101c71d32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
