<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Travel funding negotiated</name>
   <tag></tag>
   <elementGuidId>92429e27-641b-480a-9389-1c68ebdee7fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1623986423.799_travel_support'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1c40729-5eed-47a6-8665-f05d29b1438a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623986423.799_travel_support</value>
      <webElementGuid>1c9d312f-1223-44c4-b1cb-324973c9cdbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b8b17cc8-bb2f-4f11-b673-afa9fc47a271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623986423.799][travel_support][]</value>
      <webElementGuid>cc1aa45b-9584-4563-8ef1-8ff3d759c645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Travel funding negotiated</value>
      <webElementGuid>8387f81c-bfc5-437c-883d-211a61f2c02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1623986423.799&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-small-checkbox&quot;]/div[2]/input[@id=&quot;profile_group-1623986423.799_travel_support&quot;]</value>
      <webElementGuid>797c7637-f64a-4cbd-b4af-597fbd6e92a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1623986423.799_travel_support'])[2]</value>
      <webElementGuid>75e99733-d858-4b3b-8515-2c75dd4f8edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623986423.799']/div[7]/div[3]/div/div[2]/input</value>
      <webElementGuid>6bab11c8-75c5-4d38-ba99-e4af16a2b74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]/div/div[2]/input</value>
      <webElementGuid>78b5326d-6ad2-4754-a5e5-b90607808bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1623986423.799_travel_support' and @type = 'checkbox' and @name = 'profile[group-1623986423.799][travel_support][]']</value>
      <webElementGuid>693ec4d3-d83c-45d2-bdc4-3c0cdaf811ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
