<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_registrationgroup1last_name</name>
   <tag></tag>
   <elementGuidId>c76909d3-6ccf-451d-a42f-f8b55c82fa9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_group1_last_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#registration_group1_last_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>015045f0-efd5-4e44-b04b-7660893e3d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-input mn-medium-field</value>
      <webElementGuid>4ced3e82-b916-433f-acdf-8f62c18b2a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>a8bb479e-ce7c-44aa-91cc-2ac45a8aea37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>010a3882-8bee-4e88-ba8b-87133e87d284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group1_last_name</value>
      <webElementGuid>e1de6f38-201e-4b21-9bc9-fdc724715705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group1][last_name]</value>
      <webElementGuid>28527fbb-4504-46ac-b8dc-63cb34837347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf1cc24b-feb3-417b-8cda-20bf089a8223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c7eb31cf-4b93-42d6-b8d2-19703a71e151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group1_last_name&quot;)</value>
      <webElementGuid>f7a0f90f-e4ac-4f90-a18b-5bec2cac7a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_group1_last_name']</value>
      <webElementGuid>14f00e06-bb23-4435-b7b9-6c163d73b78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[2]/div[2]/input</value>
      <webElementGuid>1760ed45-8ca3-4db9-b8f2-62bcf889eb06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/input</value>
      <webElementGuid>cd5cee35-1fa2-4a64-aaf5-f503f95f24b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group1_last_name' and @name = 'registration[group1][last_name]' and @type = 'input']</value>
      <webElementGuid>8f14c2b0-8e53-4cea-951b-87570be94865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
