<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_IP Address</name>
   <tag></tag>
   <elementGuidId>301f414e-a89d-4e2f-8b89-1762f6b22b02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ipv4']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.the-ipv4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>434dcdec-29b6-4e65-9530-e8c06db18e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>the-ipv4</value>
      <webElementGuid>f5fcf7a3-f7d2-44d5-9e2d-f74db5f62f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>46.110.33.110</value>
      <webElementGuid>db4d7448-431d-4cfb-84f8-5d7f3060f8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ipv4&quot;)/span[@class=&quot;the-ipv4&quot;]</value>
      <webElementGuid>7430cba0-4ad0-4a1c-a12c-312bf1c1c146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='ipv4']/span</value>
      <webElementGuid>48fa9669-4657-4b07-bfb1-0845b92574fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What Is My IP?'])[2]/following::span[1]</value>
      <webElementGuid>e06fb973-3c1c-430a-9d29-6d7de57b8f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not Detected'])[1]/preceding::span[2]</value>
      <webElementGuid>5f17bbb9-92d8-4ef1-8d98-805cd92406e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='46.110.33.110']/parent::*</value>
      <webElementGuid>44bda51e-1ddc-4ae4-8143-26bbbd997a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/span</value>
      <webElementGuid>a37bbc21-8887-402f-9753-aa8fb4037854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '46.110.33.110' or . = '46.110.33.110')]</value>
      <webElementGuid>9f51c25f-6815-42b7-a26a-0becca708425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
