<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Other Experience Comment</name>
   <tag></tag>
   <elementGuidId>12a9b4ee-2a05-4505-8e9d-e4980b9da859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='profile_group-1456436124.683_other_education_experience_comment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a3a9226e-fb83-44e1-a390-ba0f9441cb49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>other_education_experience_comment</value>
      <webElementGuid>296a4aa4-5c5d-4124-8089-98ce7e3b6c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>140</value>
      <webElementGuid>014bde95-d23a-4ff2-babd-8b55e41d5a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-small-field</value>
      <webElementGuid>987d55f9-c610-4f61-a94d-d836d4191664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1456436124.683][other_education_experience_comment]</value>
      <webElementGuid>57178c53-d9f4-4b83-a2e3-8ea0f1a9f798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1456436124.683_other_education_experience_comment</value>
      <webElementGuid>a5776ddf-9d15-4733-8b0d-2cc7ec381252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1456436124.683_other_education_experience_comment&quot;)</value>
      <webElementGuid>3127a3dc-d077-4406-8392-c44fb924ba7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='profile_group-1456436124.683_other_education_experience_comment']</value>
      <webElementGuid>e32fda6c-c15c-4b2b-aea1-3e5542c65f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1456436124.683']/div[4]/div[2]/textarea</value>
      <webElementGuid>65fb2b7a-d498-4e57-85ad-c1762a61b0d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/textarea</value>
      <webElementGuid>fb2b7edb-bbbb-48bb-b82b-ebe1df1be2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'profile[group-1456436124.683][other_education_experience_comment]' and @id = 'profile_group-1456436124.683_other_education_experience_comment']</value>
      <webElementGuid>9fd40abd-12dd-4e1f-9ab7-05c025086e87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
