<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Occupation</name>
   <tag></tag>
   <elementGuidId>eb649acf-ee10-426e-af13-47b9afad4a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='profile_group-1445373524.208_occupation:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;profile_group-1445373524\.208_occupation\:&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>45fd6290-1baa-49b7-9496-04b67bd4b941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>occupation:</value>
      <webElementGuid>23603099-ff74-4bb7-9633-4f5cfafb2538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>58</value>
      <webElementGuid>f7f7f7bb-5b49-4671-a397-41d7aa7116bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-small-field</value>
      <webElementGuid>b99f6dbc-e1b2-4ea9-98c3-970c0bb83338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1445373524.208][occupation:]</value>
      <webElementGuid>18a409b8-2b95-47e3-910b-1164e33634d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1445373524.208_occupation:</value>
      <webElementGuid>5f441bce-d678-407b-b8ab-ece1a6f5126c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1445373524.208_occupation:&quot;)</value>
      <webElementGuid>46a7d9ba-4288-4c79-8828-28fdd2bf131e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='profile_group-1445373524.208_occupation:']</value>
      <webElementGuid>4cceaa34-8ec0-49ec-95cb-018e4226cc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1445373524.208']/div[3]/div[2]/textarea</value>
      <webElementGuid>649d2f7f-f421-49e2-b7f4-c917b798a4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>315cef01-d6b4-4127-bb02-b6add3669a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'profile[group-1445373524.208][occupation:]' and @id = 'profile_group-1445373524.208_occupation:']</value>
      <webElementGuid>c2fa502c-7619-48f7-95ba-fb450f8c0d77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
