<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_About</name>
   <tag></tag>
   <elementGuidId>4cbbfb74-5271-4d1e-9e1e-beee8721d601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/section[2]/div[2]/div/div/div/div/nav[1]/ul/li[2]/ul/li[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-75223 > a.elementor-sub-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>15404c27-103d-43b5-a552-0615765cc83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionnext.org/homepage/about/</value>
      <webElementGuid>6d3fda66-b037-48e5-9408-cf0b96899965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-sub-item</value>
      <webElementGuid>a7eff32a-dac8-49e0-b059-edaaa10cfc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>About</value>
      <webElementGuid>19526958-1a0b-48f6-a860-1ee681350f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17860305105687039-4&quot;)/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-75223&quot;]/a[@class=&quot;elementor-sub-item&quot;]</value>
      <webElementGuid>5297b030-3132-4a18-aa85-466a105f1514</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-17860305105687039-4']/li/a</value>
      <webElementGuid>f1026404-fba8-4f24-9c32-31d33ddcfd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'About')])[6]</value>
      <webElementGuid>b6d3ab42-8f24-411a-8786-2f469b42203d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::a[1]</value>
      <webElementGuid>de1335b6-e1ec-4fed-83a5-dfc997255eb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QuickStart'])[1]/following::a[2]</value>
      <webElementGuid>8d780cde-5539-49bc-85af-bdcfc9d27ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Us!'])[1]/preceding::a[1]</value>
      <webElementGuid>34c73eaf-f080-4824-accc-2be0596c0ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strategic and Mobilization Partners'])[1]/preceding::a[2]</value>
      <webElementGuid>794873a5-75a8-45f7-90b2-1d1d3da87514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://missionnext.org/homepage/about/')])[2]</value>
      <webElementGuid>5c07aa23-170b-4e67-a233-a564668098ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/nav/ul/li[2]/ul/li/a</value>
      <webElementGuid>034314b1-6513-472a-bc49-b79f11442fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionnext.org/homepage/about/' and (text() = 'About' or . = 'About')]</value>
      <webElementGuid>3d9427eb-bbdd-4dd3-9430-9e4d439bb0d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
