<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_About_sub-arrow</name>
   <tag></tag>
   <elementGuidId>d8cd19a1-b09c-4790-b07e-2979386f35b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/section[2]/div[2]/div/div/div/div/nav[1]/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sm-17860305105687039-3 > span.sub-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5597f7e8-58a2-48cb-bb7f-7c89ca4b4c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-arrow</value>
      <webElementGuid>ce0fbc3d-8cca-4e80-bbfc-c1132aaa0697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17860305105687039-3&quot;)/span[@class=&quot;sub-arrow&quot;]</value>
      <webElementGuid>9f5d66fc-45dd-4619-a3ed-80a1ee1adeef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sm-17860305105687039-3']/span</value>
      <webElementGuid>7c856507-741d-424b-b26b-786d3aa6cf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]//span[1]</value>
      <webElementGuid>88ea608a-e1af-4144-8095-28c756d556a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QuickStart'])[1]/following::span[1]</value>
      <webElementGuid>7ac27d5d-5dca-4f4b-8aa6-98538b233130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[2]/preceding::span[1]</value>
      <webElementGuid>fb03e039-2f58-4a89-916c-85d1feff8ec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join Us!'])[1]/preceding::span[1]</value>
      <webElementGuid>811c9f14-d2e0-41ed-9bdb-ed1715bf9ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/nav/ul/li[2]/a/span</value>
      <webElementGuid>e45b61ce-55b8-47e2-b324-d8d080cdd0b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
