<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Paid Volunteer Positions</name>
   <tag></tag>
   <elementGuidId>6e8d91be-af6b-42cc-bace-b1d574b2bd29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1623986423.799_financial_support']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dd367d7-78c2-4674-aa95-45fef6690ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623986423.799_financial_support</value>
      <webElementGuid>a354b539-08b3-4d1a-8a3a-955269ad33d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0792b81a-1d71-4695-8e90-d55e26a72019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623986423.799][financial_support][]</value>
      <webElementGuid>7e9ae6c5-c7e0-47af-a1b7-593b74274934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(!) Volunteer/self-supported position</value>
      <webElementGuid>bfa8a418-ce8f-4aba-92be-b60733a48677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1623986423.799&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1623986423.799_financial_support&quot;]</value>
      <webElementGuid>d6602756-cd6e-4af1-9f2a-8b7648e3aff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1623986423.799_financial_support']</value>
      <webElementGuid>945fdd42-3357-4e17-897b-28f4ba746241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623986423.799']/div[4]/div[2]/div/div/input</value>
      <webElementGuid>484b4ff7-6102-4ace-98fd-f96308a2e7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>7628bc48-acdd-49d5-8091-ed5c16b3e01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1623986423.799_financial_support' and @type = 'checkbox' and @name = 'profile[group-1623986423.799][financial_support][]']</value>
      <webElementGuid>f1fe38e4-9908-4669-9c63-ee27246f1089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
