<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Resume_Choose File</name>
   <tag></tag>
   <elementGuidId>de10a2d9-0d3e-4472-8877-4d2860c87266</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_resume</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_resume']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebe136ed-001d-408a-9e21-df8eab6ace8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>resume</value>
      <webElementGuid>f610f2c4-10f5-4890-a55d-45079970f151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>81</value>
      <webElementGuid>e38f00f5-d472-4a68-884b-b69b4c7b9b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_resume</value>
      <webElementGuid>efeebc6b-5682-47ca-bd9c-8c7b1e20ccbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resume</value>
      <webElementGuid>138d0286-38cc-4ad4-80c3-594265b09636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>79c70f6e-684a-436d-8dd0-2467e4806a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>pdf</value>
      <webElementGuid>27c8d720-5a92-4541-98c9-ea5677c1ccf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.pdf</value>
      <webElementGuid>98386246-9163-40de-9111-3b70c09dfa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_resume&quot;)</value>
      <webElementGuid>59e6aad4-2706-4987-ab19-e1df12c60a0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_resume']</value>
      <webElementGuid>e4595e55-35f6-4668-a09b-f11dae489580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uploaded-resume']/input</value>
      <webElementGuid>e0135f72-ad98-4c90-8a6b-fc873258bb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/input</value>
      <webElementGuid>39dc5cc0-d820-4dcd-b6ef-961f21bf2a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_resume' and @name = 'resume' and @type = 'file']</value>
      <webElementGuid>2d5ba692-06ce-4020-837f-7d5847d33d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
