<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Equipping sub-arrow</name>
   <tag></tag>
   <elementGuidId>30cfd967-1129-4e13-9a6b-97fb86d7bcba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sm-17805869842330461-3 > span.sub-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/section[1]/div/div[2]/div/div/div/nav[1]/ul/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>62ed07ad-9112-4c24-9ac1-d66f5af8c075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-arrow</value>
      <webElementGuid>e302e8be-fd70-414f-8d1e-b7a891336632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17805869842330461-3&quot;)/span[@class=&quot;sub-arrow&quot;]</value>
      <webElementGuid>48791798-c0d3-4cc2-ac57-b55f0e4d6bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='sm-17805869842330461-3']/span</value>
      <webElementGuid>6fe93970-e4f6-4cde-9d35-b7e0acd6b615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionGuide'])[1]/following::span[1]</value>
      <webElementGuid>94427723-12a8-4335-a518-32af8c2d6751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MIssionNext'])[1]/following::span[1]</value>
      <webElementGuid>48573e88-2707-4f85-a168-301e17ae9a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coaching'])[1]/preceding::span[1]</value>
      <webElementGuid>af2634bf-8a1d-44c8-926a-b78eb7521749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionLinked'])[1]/preceding::span[1]</value>
      <webElementGuid>98e84837-4de0-4cf9-b6d9-07d2e0a6ffc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/span</value>
      <webElementGuid>37cd5883-0434-4057-a2e5-b53190d18098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
