<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign Up (2)</name>
   <tag></tag>
   <elementGuidId>3e5ebf41-adf7-4d70-b76f-49a52c967551</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sign_up_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sign_up_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f1cd504b-34af-4f48-b32c-3e559258a04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-button elementor-button-link elementor-size-sm</value>
      <webElementGuid>660765ed-6255-44cc-91d2-083f4549e26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://portal.missionlinked.global/Organization/Registration/</value>
      <webElementGuid>96146e1a-3637-4eba-b9d6-e332d727bf2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>ba08852d-b18a-45fb-8d5b-801627f6525a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sign_up_2</value>
      <webElementGuid>1d8c93fd-111e-49cb-bc90-0403c6d9e3c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Sign Up  </value>
      <webElementGuid>7bf4e020-470a-4a75-841a-4a9709580841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sign_up_2&quot;)</value>
      <webElementGuid>da37bc40-2988-4431-a65a-b7fe5926cd38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sign_up_2']</value>
      <webElementGuid>c381f420-8e3e-4ab1-89c9-da083655fa62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You can sign up for FREE!'])[1]/following::a[1]</value>
      <webElementGuid>d033e819-3bf9-432a-927b-9d8c17987ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fundraising tools'])[1]/preceding::a[1]</value>
      <webElementGuid>d23ff4f8-112f-4872-8b76-7e145a7822cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://portal.missionlinked.global/Organization/Registration/')])[2]</value>
      <webElementGuid>2d64942c-c800-4573-ac26-85f8e75210b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/div/div/div[3]/div/div/a</value>
      <webElementGuid>78bcc523-ec8f-4903-928e-454d773569c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://portal.missionlinked.global/Organization/Registration/' and @id = 'sign_up_2' and (text() = '  Sign Up  ' or . = '  Sign Up  ')]</value>
      <webElementGuid>9977b853-5a8e-42f7-866c-0b51819d4b25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
