<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Spouse Experience</name>
   <tag></tag>
   <elementGuidId>8f5fc568-a314-400b-bc80-dcbe6fc92d5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tabs&quot;]/ul/li[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>42b3f08c-8340-4c51-9ed6-b897f5f30e96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#group-1623988190.243</value>
      <webElementGuid>5b499c99-001e-4d9a-beb5-10295c92682f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dependent-group ui-tabs-anchor</value>
      <webElementGuid>bde3ffc9-f3b6-4727-9cd2-f8785aab1eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>group-1623988190.243</value>
      <webElementGuid>4f1a8c70-e07e-4899-9c6a-6f60b5ba460e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-depends-on</name>
      <type>Main</type>
      <value>spouse_serving_with_you?</value>
      <webElementGuid>c8519d29-7b00-4969-b593-19706add692a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>24104614-1099-4918-aa20-757c65265640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-9</value>
      <webElementGuid>977b1092-2c75-44d8-a2b0-3f71fab565b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spouse Experience</value>
      <webElementGuid>c2ebd63d-100b-4432-b223-0707fec64535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-9&quot;)</value>
      <webElementGuid>8168de68-21ca-48e8-abdc-c4a945a5c432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-9']</value>
      <webElementGuid>da092a7a-d0f7-49f9-8b64-45464152d442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/ul/li[9]/a</value>
      <webElementGuid>1c671f0c-7403-4728-8848-4cf53410c6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Spouse Experience')]</value>
      <webElementGuid>5c7af0ee-52be-4818-9ca3-1e6a62b1893c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Info'])[1]/following::a[1]</value>
      <webElementGuid>476afff6-ed8a-452a-9c69-280a0a30e1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IT Skills and Interest'])[1]/following::a[2]</value>
      <webElementGuid>e51e0a27-8b2a-42e4-bd70-db967ce7e5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Ministry Prefs'])[1]/preceding::a[1]</value>
      <webElementGuid>55fcd95c-bd2e-4777-a29f-1918f56df91a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='required *'])[1]/preceding::a[2]</value>
      <webElementGuid>d789b937-289c-4ea2-a080-5d3ba239c73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spouse Experience']/parent::*</value>
      <webElementGuid>2138771c-9bb9-4fed-94cd-dd2b4b631fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#group-1623988190.243')]</value>
      <webElementGuid>50e7b757-b7eb-4588-928b-bc670fa02de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[9]/a</value>
      <webElementGuid>583d26ac-d50d-4622-9c93-538e44f8bf0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#group-1623988190.243' and @id = 'ui-id-9' and (text() = 'Spouse Experience' or . = 'Spouse Experience')]</value>
      <webElementGuid>827fdb67-3dce-460c-88b7-b7c6c42043ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
