<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spouse Missions Experience</name>
   <tag></tag>
   <elementGuidId>ec29014c-efce-488a-a2e8-f885a48c396b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1623988190.243_spouse_missions_exposure']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>11ccb3ab-8a55-431d-8dae-cb937451e421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623988190.243_spouse_missions_exposure</value>
      <webElementGuid>1a9ae84c-ac40-433a-a668-49cd5cdc7594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1d1139cf-649c-41af-8953-592ffa69d511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623988190.243][spouse_missions_exposure][]</value>
      <webElementGuid>2ddb6ee7-7fcf-493f-9b7e-f8f24076c89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I have attended a missions event</value>
      <webElementGuid>02c8279a-6371-4523-ac10-fe56fe29e668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1623988190.243&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-small-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1623988190.243_spouse_missions_exposure&quot;]</value>
      <webElementGuid>0660e95a-a415-49ca-b648-8a721100043c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1623988190.243_spouse_missions_exposure']</value>
      <webElementGuid>42444c0a-2e69-4855-aeb6-81b26c907ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623988190.243']/div[7]/div[2]/div/div/input</value>
      <webElementGuid>cdcd1a6e-f44b-4ae0-a186-fdce5314d2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/input</value>
      <webElementGuid>2b57ca50-f5e3-48b8-8a4d-5f792d69edac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1623988190.243_spouse_missions_exposure' and @type = 'checkbox' and @name = 'profile[group-1623988190.243][spouse_missions_exposure][]']</value>
      <webElementGuid>76aa0b2c-f50a-42d2-8fd5-03f476bd6405</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
