<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Spouse Occupation</name>
   <tag></tag>
   <elementGuidId>112621cd-2686-4daf-8234-775035f02aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='profile_group-1623988190.243_spouse_occupation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8f2288ec-4bd6-49e1-8e08-b9bc6cb7e0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>spouse_occupation</value>
      <webElementGuid>c3138f7b-c432-4620-b3cb-185377749693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>290</value>
      <webElementGuid>4bfcb56a-30cf-49c2-87f5-dcfac9aee44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-medium-field</value>
      <webElementGuid>d76d3847-171a-4726-a143-66cf9e5eee81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623988190.243][spouse_occupation]</value>
      <webElementGuid>0daba71e-9e04-4029-b604-39fdbc66fc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623988190.243_spouse_occupation</value>
      <webElementGuid>a89b8a36-2494-4968-b7f5-9346cc955f08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1623988190.243_spouse_occupation&quot;)</value>
      <webElementGuid>92b89dc8-babd-4122-8943-eec85d3a7b75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='profile_group-1623988190.243_spouse_occupation']</value>
      <webElementGuid>8baa3639-869e-4566-aa86-cb2eb2bb0aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623988190.243']/div[3]/div[2]/textarea</value>
      <webElementGuid>f14e202d-6405-4b07-84bc-f62860e1723a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[3]/div[2]/textarea</value>
      <webElementGuid>f82e0a9f-2b33-40de-a002-483a2a5acb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'profile[group-1623988190.243][spouse_occupation]' and @id = 'profile_group-1623988190.243_spouse_occupation']</value>
      <webElementGuid>ccc5ba39-54cc-4418-b7f5-ea5078c6e572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
