<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxes_Paid  Volunteer Positions</name>
   <tag></tag>
   <elementGuidId>8919850b-8b3f-4cf3-8a3c-802f21492829</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group1_financial_support']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profile_group1_financial_support</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4837409-ba09-477f-b7a7-bc395e8bfb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group1_financial_support</value>
      <webElementGuid>04a14e11-dc2a-47d6-9340-0f9b445b5935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5ba74778-2a91-480e-9a67-c660910838b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group1][financial_support][]</value>
      <webElementGuid>4900dd31-12ff-4eea-97e7-5bbbc989c53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(!) Volunteer/self-supported position</value>
      <webElementGuid>f8887161-d245-4ca4-b17c-f4ed92f8e1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group1&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[1]/input[@id=&quot;profile_group1_financial_support&quot;]</value>
      <webElementGuid>68fd5211-c5de-40ad-acd5-e88b4f15859a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group1_financial_support']</value>
      <webElementGuid>56a08890-2ce5-447e-b205-5231e43eca52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[8]/div[2]/div/div/input</value>
      <webElementGuid>a2c97476-dc30-4621-9089-48f6e2c40f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/div/input</value>
      <webElementGuid>90a51c1e-fe17-4cbe-b25d-e865a962440a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group1_financial_support' and @type = 'checkbox' and @name = 'profile[group1][financial_support][]']</value>
      <webElementGuid>a6dc83f8-cb6c-47db-a326-0ff5ede17aad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
