<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Match Rate</name>
   <tag></tag>
   <elementGuidId>453574c5-4c17-4c4e-970b-35e32d3a55cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='profile_group-1494759117.185_match_rate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9f61d22b-fe8f-4f16-8554-615858c5f6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>match_rate</value>
      <webElementGuid>b1b01790-13c1-4fa0-a996-60583c780903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>48</value>
      <webElementGuid>8caabca7-7586-489a-9552-bd5bf8a281fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1494759117.185][match_rate]</value>
      <webElementGuid>4519bb69-1dbc-45d4-937a-5896dbc88043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1494759117.185_match_rate</value>
      <webElementGuid>47781ca3-ace8-43a8-a5d5-a1a1807bdc06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
10
20
30
40
50
60
70
80
90
</value>
      <webElementGuid>ffb91b0f-cfdb-4e6c-af51-3963871ca323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1494759117.185_match_rate&quot;)</value>
      <webElementGuid>357c8f34-85e9-47b9-84b6-8f0e5ebfc888</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='profile_group-1494759117.185_match_rate']</value>
      <webElementGuid>25286370-69e7-4b71-97e9-2a5535b462e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1494759117.185']/div/div[3]/select</value>
      <webElementGuid>55f444a6-5c4d-43ea-b841-3d021fa615d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Match Rate'])[1]/following::select[1]</value>
      <webElementGuid>596dd620-65e4-4c78-9a75-ae92d2cb1831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Information on this Settings tab is not seen by candidates.'])[1]/following::select[1]</value>
      <webElementGuid>14867ef1-2906-4b80-b166-fb2494584c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Years'])[1]/preceding::select[1]</value>
      <webElementGuid>3046007a-d93a-42a0-b463-3dde83752ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[1]/preceding::select[1]</value>
      <webElementGuid>eb03789e-7149-4a56-a91c-9acb91408f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>4ee031ee-e305-4d85-998d-123599e70a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'profile[group-1494759117.185][match_rate]' and @id = 'profile_group-1494759117.185_match_rate' and (text() = '
10
20
30
40
50
60
70
80
90
' or . = '
10
20
30
40
50
60
70
80
90
')]</value>
      <webElementGuid>0604d846-3164-49df-bd5d-6a8744955377</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
