<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_ACSI</name>
   <tag></tag>
   <elementGuidId>c465514f-c1a4-4c3d-bf33-4fb752ae25aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @value = 'ACSI']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='registration_group-1462396686.719_memberships'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55fddece-5abc-471e-8bd7-f127499d1701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1462396686.719_memberships</value>
      <webElementGuid>aad06845-9f22-42ff-996b-1e2ee33bdee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2dbcc021-606f-4008-b629-71de2a7ccadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1462396686.719][memberships][]</value>
      <webElementGuid>0e04324d-762f-4f02-bb87-2d9371e82d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ACSI</value>
      <webElementGuid>057ee811-711c-46c4-a11a-cc1a62095fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1462396686.719&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-checkbox mn-medium-checkbox&quot;]/div[2]/input[@id=&quot;registration_group-1462396686.719_memberships&quot;]</value>
      <webElementGuid>e2ba8e8e-2ae1-4b78-9ab7-89b19325c769</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='registration_group-1462396686.719_memberships'])[5]</value>
      <webElementGuid>c7561231-c02e-4687-870e-b10b659926bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1462396686.719']/div[7]/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>104c3a5b-bd94-4564-af46-93ee3a719676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div[2]/div[2]/input</value>
      <webElementGuid>4fc47c21-811b-417a-9a77-4fb7acc1b270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group-1462396686.719_memberships' and @type = 'checkbox' and @name = 'registration[group-1462396686.719][memberships][]']</value>
      <webElementGuid>bddb3ffb-fbea-4cdc-b08f-2c1def9150e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
