<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MissionGuide</name>
   <tag></tag>
   <elementGuidId>1e9004ff-9533-46ff-a031-146c76207cb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-77189 > a.elementor-sub-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/section[1]/div/div[2]/div/div/div/nav[2]/ul/li[1]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0e11a00-a90c-4819-a394-6fb83cbd7eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionguide.global/</value>
      <webElementGuid>a4f04871-c30b-4b62-9d23-dff7f98575ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-sub-item</value>
      <webElementGuid>ffaff60f-bb08-4866-9b17-762e469065be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MissionGuide</value>
      <webElementGuid>2c86697a-ca7d-4780-9190-0c4ac5852ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17799005530152898-2&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-77189&quot;]/a[@class=&quot;elementor-sub-item&quot;]</value>
      <webElementGuid>373f016a-39e3-44c1-a3e3-0b5466e675b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-17799005530152898-2']/li[3]/a</value>
      <webElementGuid>93f9d837-b171-4f30-b4e5-b7e9740eeaa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MissionGuide')]</value>
      <webElementGuid>830fba09-2602-4ecf-80c1-ccb3ee382291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MIssionNext'])[1]/following::a[1]</value>
      <webElementGuid>c6b4cb5d-ecfd-460d-866c-d1dfd4567b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionConnexion'])[1]/following::a[2]</value>
      <webElementGuid>25d98cf0-ce51-4c2a-a046-f8d2e7e02a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coaching'])[1]/preceding::a[2]</value>
      <webElementGuid>1275a061-6fe2-47bc-a604-cd3c3358228f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionLinked'])[1]/preceding::a[3]</value>
      <webElementGuid>331cd93c-4dcc-4ce3-963f-f87e5bcf1faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MissionGuide']/parent::*</value>
      <webElementGuid>c6205dc6-9528-4a69-9018-d94173fd417b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://missionguide.global/')]</value>
      <webElementGuid>5dd459bf-cd07-44f7-8518-1f3c0a79f9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>354e3220-00ef-470c-9193-df233315033c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionguide.global/' and (text() = 'MissionGuide' or . = 'MissionGuide')]</value>
      <webElementGuid>a24cd77a-91bc-4ebd-8d42-88e5cb58eb45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
