<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Terms and Conditions</name>
   <tag></tag>
   <elementGuidId>d03fec8a-0c90-425f-b035-b206330463b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_group-1595728938.496_terms_and_conditions']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f39adf77-b48e-4abf-991a-7e627abbe9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-boolean </value>
      <webElementGuid>1a4b4ccb-89a2-4800-aa54-1e1a3be25965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>191ca83c-875a-4570-ad56-f02a23918fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>337</value>
      <webElementGuid>5d06b306-b42a-4778-9ddd-364bbc097416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1595728938.496][terms_and_conditions]</value>
      <webElementGuid>faf370f1-17d6-4e72-9143-0aec05d15ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1595728938.496_terms_and_conditions</value>
      <webElementGuid>cd88dd37-e09f-480a-bd72-af2c43baebf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>36b370a4-e8f0-4a58-8b5d-82e0a5c48768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2eac9ef1-4f56-4c4a-8af8-90bc6a12d878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group-1595728938.496_terms_and_conditions&quot;)</value>
      <webElementGuid>56856da6-b1c5-4af1-830b-ba4586d45de8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_group-1595728938.496_terms_and_conditions']</value>
      <webElementGuid>f909be83-1ef0-4dbd-800d-c2925157d0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1595728938.496']/div[3]/div[3]/input</value>
      <webElementGuid>dd23bb15-357e-435a-a394-9d42a115c727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div[3]/input</value>
      <webElementGuid>6ae21413-1d68-4a3e-ad7e-4f7522188155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'registration[group-1595728938.496][terms_and_conditions]' and @id = 'registration_group-1595728938.496_terms_and_conditions' and @type = 'checkbox']</value>
      <webElementGuid>21d69134-c8da-424c-a289-89a9b5959c07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
