<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PostZip Code</name>
   <tag></tag>
   <elementGuidId>62c53138-bd89-4f74-9f43-3a91e8cf2801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration_group1_zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_group1_zip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc1d723e-5761-42ec-bb76-09ad43030964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-input mn-small-field</value>
      <webElementGuid>1aa30995-18b9-4492-ad1d-7d67a5e5b2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>zip</value>
      <webElementGuid>549e4ce1-a820-429f-ae21-a7e90741898d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>ffdd8ea1-6936-4617-ad99-b21f1376e850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group1_zip</value>
      <webElementGuid>1b5b5409-1a5d-4fb6-97a8-2aab972eeb93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group1][zip]</value>
      <webElementGuid>6afc553d-6082-4520-8a6c-f00aeece74e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d623299-4476-421f-9a0b-b087c6774edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af1e3959-c94d-4b5c-b8d2-fb5bc15ec730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group1_zip&quot;)</value>
      <webElementGuid>325f9ef5-4ebc-4d34-8237-c5c33eadf707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_group1_zip']</value>
      <webElementGuid>afb58d1c-1053-4be3-849f-1c2069bb27eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[3]/div[3]/input</value>
      <webElementGuid>314a49de-9e42-4622-9dbb-629914092408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/input</value>
      <webElementGuid>2748b019-ba1d-49ad-9681-f87ead2a99b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group1_zip' and @name = 'registration[group1][zip]' and @type = 'input']</value>
      <webElementGuid>36e54338-0fed-40be-ae62-355accb85a45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
