<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Preferences</name>
   <tag></tag>
   <elementGuidId>06dedc24-60f3-4d6a-b723-590f90a6bc56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>203d0177-b24b-4996-984f-daa9474431ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#group-1449972047.293</value>
      <webElementGuid>c4ae536c-dbf7-4068-aeab-7d43af0e51c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>75b6534f-3dd1-4fcd-b8a6-1a912077fc92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-tabs-anchor</value>
      <webElementGuid>3c420b11-a4db-463e-8c4c-dd7a4f8275a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-6</value>
      <webElementGuid>4d3d2e5f-c0d3-434f-9985-cc2d05bb53c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Preferences</value>
      <webElementGuid>9bb79b34-53a1-40cb-91d6-6cba99d10cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-6&quot;)</value>
      <webElementGuid>ac295032-9cd8-4650-bb04-6957c1a6af00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-6']</value>
      <webElementGuid>1f7b9ebc-e9bf-45c2-82bf-e08b64639974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/ul/li[6]/a</value>
      <webElementGuid>558d5e71-4396-423b-89c6-4fc0123d7290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Preferences')]</value>
      <webElementGuid>df877462-6362-4f04-928e-39f5360fe51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Availability'])[1]/following::a[1]</value>
      <webElementGuid>daad4434-79dd-4759-859a-edb6b2165bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Situation'])[1]/following::a[2]</value>
      <webElementGuid>95e4ff5b-81f7-43b4-8f6e-12b5ac2946bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options/Comment'])[1]/preceding::a[1]</value>
      <webElementGuid>eb0756e9-422c-4371-8c54-fb5878740bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Info'])[1]/preceding::a[2]</value>
      <webElementGuid>eeb90fb1-9988-4396-9bfa-8d67e6988766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Preferences']/parent::*</value>
      <webElementGuid>c0736506-dd16-494c-9a48-ef1cae135265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#group-1449972047.293')]</value>
      <webElementGuid>4b216fd1-ca1e-4d26-9022-71c92cc7e370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[6]/a</value>
      <webElementGuid>226dba97-b2fb-439c-b72d-49b8b79f3941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#group-1449972047.293' and @id = 'ui-id-6' and (text() = 'Preferences' or . = 'Preferences')]</value>
      <webElementGuid>e601a019-48ad-448f-b09e-1186096f899d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
