<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Spouse Service Prefs</name>
   <tag></tag>
   <elementGuidId>1a4f47d8-cb7f-4781-af70-b5254c41c925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>40645a3c-d6c2-4fdb-8dcb-74bba191c6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#group-1631421470.837</value>
      <webElementGuid>d30f6cca-bd84-4be1-847b-ff832d073a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dependent-group ui-tabs-anchor</value>
      <webElementGuid>94c7f207-ebff-4635-ad22-cb82ef195a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>group-1631421470.837</value>
      <webElementGuid>a7307827-0083-44f7-b7b1-b09718f7ab3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-depends-on</name>
      <type>Main</type>
      <value>spouse_serving_with_you?</value>
      <webElementGuid>48bc3548-511d-4415-9ec2-555692afbb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>205eee21-6c4e-40c8-817e-bbde12f10cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-10</value>
      <webElementGuid>3141d1a1-09fd-476c-9bae-af12598f9881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Spouse Service Prefs</value>
      <webElementGuid>3c3e4db0-48f8-42bf-b9b8-0c29ec8ced7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-10&quot;)</value>
      <webElementGuid>47adcde4-e2e5-4de5-85ef-c16009ad8c60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-10']</value>
      <webElementGuid>2fbf2f6a-e0d5-4916-b5ef-5b00279f746d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/ul/li[10]/a</value>
      <webElementGuid>0ae32949-561e-4322-8e68-c00e8de07e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Spouse Service Prefs')]</value>
      <webElementGuid>4cadf187-d1fb-42bf-82ba-e995e2a5ed98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Experience'])[1]/following::a[1]</value>
      <webElementGuid>6e813502-2493-4d77-a843-308d2f02cf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Info'])[1]/following::a[2]</value>
      <webElementGuid>1950112e-6cc4-4ec4-960a-4dee62d47a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Education'])[1]/preceding::a[1]</value>
      <webElementGuid>67d02884-2d8d-45bb-b8cc-fc9c9a148d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spouse Teaching Prefs'])[1]/preceding::a[2]</value>
      <webElementGuid>3a8096fe-9ae5-41ec-9729-daab8d553102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Spouse Service Prefs']/parent::*</value>
      <webElementGuid>ada4acc7-1afd-43b7-bfa9-8fca06007429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#group-1631421470.837')]</value>
      <webElementGuid>1d986cce-3aa7-4cbe-9a0e-69c3c36d5651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>0af08940-053c-4ff7-878d-8576df3827ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#group-1631421470.837' and @id = 'ui-id-10' and (text() = 'Spouse Service Prefs' or . = 'Spouse Service Prefs')]</value>
      <webElementGuid>8301794f-2ff0-41de-be9a-d61fbfd2e074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
