<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Resources</name>
   <tag></tag>
   <elementGuidId>30f4317e-fe9c-4b49-80da-10c2ccac96ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sm-17139076272213723-6']/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-56080 > a.elementor-sub-item</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://missionnext.org/homepage/goer/resources-for-goers/' and (text() = 'Resources' or . = 'Resources')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>50be7b11-74a6-4d01-9dfc-ff77eb163055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionnext.org/homepage/goer/resources-for-goers/</value>
      <webElementGuid>5b0e2902-77e8-4d91-8b76-3a6fc6942da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-sub-item</value>
      <webElementGuid>3a2af786-dad7-44fa-a83c-3722ac494d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Resources</value>
      <webElementGuid>34303168-e1be-4455-b64c-ba464ba35db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17139076272213723-6&quot;)/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-56080&quot;]/a[@class=&quot;elementor-sub-item&quot;]</value>
      <webElementGuid>355db7b4-f7a9-44cc-8d55-108ec3800b71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-17139076272213723-6']/li[5]/a</value>
      <webElementGuid>6ef49d5f-1dbd-460d-af56-fdbe07bd5953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Resources')]</value>
      <webElementGuid>0d9ed689-3a30-4bd4-8bab-824a8c4fa5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs'])[1]/following::a[1]</value>
      <webElementGuid>0b396d68-9b64-42b9-903f-c3e2fb84079c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to Education!'])[1]/following::a[2]</value>
      <webElementGuid>07f6c698-0441-49b1-b7f0-70a6f3736c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sender'])[1]/preceding::a[1]</value>
      <webElementGuid>8697e2fc-c2cd-47b8-bc04-09fe75d1842f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organizations'])[1]/preceding::a[2]</value>
      <webElementGuid>e05258cc-bc48-4861-bc6f-d574cf327e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resources']/parent::*</value>
      <webElementGuid>f4c64e4f-df5c-4317-ad09-ff3eb956fb41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://missionnext.org/homepage/goer/resources-for-goers/')]</value>
      <webElementGuid>248295f4-f2e1-4e65-a38b-07f4b798a02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[5]/a</value>
      <webElementGuid>7aae3910-ef3a-42a6-ad36-000fc75207b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionnext.org/homepage/goer/resources-for-goers/' and (text() = 'Resources' or . = 'Resources')]</value>
      <webElementGuid>ccd3c3f5-fb3b-4fb0-a1da-d99eca56c27a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
