<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Preferred Position(s)-Generic</name>
   <tag></tag>
   <elementGuidId>8610b81d-9d4d-417e-92b8-cce1d27f3f03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1623987608.435_ministry_preferences']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'profile_group-1623987608.435_ministry_preferences']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9e4a9cc-2902-4240-b075-8d3625031b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1623987608.435_ministry_preferences</value>
      <webElementGuid>6f674978-230b-4656-9af5-84e112cde920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6292f417-a66c-46d6-8b25-8f3b08a4903d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1623987608.435][ministry_preferences][]</value>
      <webElementGuid>c1ef3de3-0f9b-410a-83ee-3c658dd05814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>128cf9f9-cd08-47c6-9cdc-3a2ff562957a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Veterinary</value>
      <webElementGuid>9d0f8d5e-5e35-4638-ae65-b2d89805a18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1623987608.435&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1623987608.435_ministry_preferences&quot;]</value>
      <webElementGuid>be3a4103-fa68-49e3-9245-24db6cd4bc4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1623987608.435_ministry_preferences']</value>
      <webElementGuid>057a9bef-22c4-4861-9c2e-c04db64ecbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1623987608.435']/div[2]/div[3]/div/div/input</value>
      <webElementGuid>24c2bcf2-ca5e-4c7d-abee-613065154227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/div[3]/div/div/input</value>
      <webElementGuid>8a7c215c-feb3-40d7-96b1-a4d2eee03cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1623987608.435_ministry_preferences' and @type = 'checkbox' and @name = 'profile[group-1623987608.435][ministry_preferences][]' and @checked = 'checked']</value>
      <webElementGuid>6937044f-998a-4069-a135-10533c50d658</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
