<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Matches Parm</name>
   <tag></tag>
   <elementGuidId>7b803a6d-8122-48dd-bf20-e1b308e3ad63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(8) > a[title=&quot;View Job Matches&quot;] > input[name=&quot;view_matches&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[${testJob}]/td[9]/a/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>464f449d-35da-46ac-bc8a-b20e9479c79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46650019-5bd4-4bf3-9dd3-f59db57752f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button_primary</value>
      <webElementGuid>0c8d0040-fd98-4743-9bb4-f797a5d72b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>view_matches</value>
      <webElementGuid>f33a6887-778f-4686-8286-f1dec0410ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Matches</value>
      <webElementGuid>7ba1483f-e2c3-4288-8722-07d9689a9607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/table[1]/tbody[1]/tr[4]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/span[@class=&quot;body&quot;]/form[1]/table[1]/tbody[1]/tr[4]/td[8]/a[1]/input[@class=&quot;button_primary&quot;]</value>
      <webElementGuid>c0208b5c-7e15-462e-8122-714d28a13808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='view_matches'])[2]</value>
      <webElementGuid>5c63f81b-2036-4b3f-be33-050bb59fb183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[8]/a/input</value>
      <webElementGuid>836c54be-f5b9-4b51-b31e-93dfd3d89330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'view_matches']</value>
      <webElementGuid>6922e86b-3f02-4787-94fa-3f1d7f72d299</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
