<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Board of Directors</name>
   <tag></tag>
   <elementGuidId>87b7bf3e-ba1f-4327-9d70-8f3c7da6df2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1446521439.133_board_of_directors']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b4e3f2d-a757-4dd7-827e-479d18f8d3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>board_of_directors</value>
      <webElementGuid>33d55714-b517-45ef-a2a5-20a3159d3d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>85</value>
      <webElementGuid>d1bbd067-a225-4795-a89e-4af0bf034fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-large-field</value>
      <webElementGuid>a7bd733e-fb00-428c-bf7f-5019a6a46270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446521439.133_board_of_directors</value>
      <webElementGuid>7d5cd5d3-23ec-4a6b-9874-ba0974a83e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446521439.133][board_of_directors]</value>
      <webElementGuid>d79bc72a-1254-4ad2-acb4-b9e02879ae72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a6f0532-3f37-46b5-93eb-0ef0eb220e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14264acd-30f0-4b62-85c2-cb314b0b9470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://missionnext.org/bod</value>
      <webElementGuid>af67ca12-62ff-4d93-8253-cafa38237189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Appropriate webpage address here or enter &quot;Will submit by email&quot;</value>
      <webElementGuid>9ce0d1df-1c04-4387-913f-860c38d0f525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1446521439.133_board_of_directors&quot;)</value>
      <webElementGuid>7b9c6d61-c8e5-4833-8215-ffcdbaa18982</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1446521439.133_board_of_directors']</value>
      <webElementGuid>a05665d0-da68-4e07-af59-162c43b8dc4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446521439.133']/div[5]/div[2]/input</value>
      <webElementGuid>8f09b0b4-9fc3-4699-bd8c-c8ad14c5089a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div[2]/input</value>
      <webElementGuid>6458d195-fff4-46ad-9295-f45a28a35e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1446521439.133_board_of_directors' and @name = 'profile[group-1446521439.133][board_of_directors]' and @type = 'input' and @placeholder = 'Appropriate webpage address here or enter &quot;Will submit by email&quot;']</value>
      <webElementGuid>bb9e4e38-8418-46d4-80d0-881f580865ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
