<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mission Statement</name>
   <tag></tag>
   <elementGuidId>30559cc2-d7d7-44b3-a100-c2e28e44ca4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1446521439.133_mission_statement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcba89bc-e3e3-4ec1-8410-edd2a6156303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>mission_statement</value>
      <webElementGuid>b853fe27-4ded-4b66-b386-811dd49909f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>84</value>
      <webElementGuid>1655338d-6bec-4861-8385-5e9e3fe90f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-large-field</value>
      <webElementGuid>6a7901c7-e601-4ffb-a289-f2a74ac8280d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446521439.133_mission_statement</value>
      <webElementGuid>5c619f49-6cca-467a-afb2-8b475a50e056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446521439.133][mission_statement]</value>
      <webElementGuid>5a52b63e-daf2-4e17-94a3-3f2e3f0c5e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4616b657-9bd8-49b8-b8e8-0aaee20e9d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36942af5-0ca5-4741-a65d-0247ea9fe590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>https://missionnext.org/mission</value>
      <webElementGuid>157772a3-48ac-4151-ab68-1d0a946b14b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Appropriate webpage address here or enter &quot;Will submit by email&quot;</value>
      <webElementGuid>b6993a98-f654-4401-b627-d340b6681ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1446521439.133_mission_statement&quot;)</value>
      <webElementGuid>fc73b3c4-b665-48fd-aa85-f540fce6b352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1446521439.133_mission_statement']</value>
      <webElementGuid>17ebe989-032d-4ed6-b572-f61b7bae1014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446521439.133']/div[3]/div[2]/input</value>
      <webElementGuid>08075802-4e59-45fe-ab31-735e4a651f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>68f16da6-2754-4afd-8e1e-c8da6bc99095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1446521439.133_mission_statement' and @name = 'profile[group-1446521439.133][mission_statement]' and @type = 'input' and @placeholder = 'Appropriate webpage address here or enter &quot;Will submit by email&quot;']</value>
      <webElementGuid>f05cecda-a8ae-49a2-b1a6-4c4659c1e213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
