<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_References</name>
   <tag></tag>
   <elementGuidId>40974fe2-3d64-4b79-ab2f-3636430da74a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='profile_group-1446521439.133_references']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2b27b791-c83e-46ab-81c5-67d829915c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>references</value>
      <webElementGuid>46f73848-8ddc-4c73-9776-2cb9c59fa091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>87</value>
      <webElementGuid>bf2583d2-f05d-465d-adff-faaa395ea945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-medium-field</value>
      <webElementGuid>d60f102b-3dd8-4ea1-8f03-08e019469008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446521439.133][references]</value>
      <webElementGuid>e78ff9b6-1ec0-4743-949a-da6e7b248eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446521439.133_references</value>
      <webElementGuid>c423293f-aac7-4702-a8bc-5ddb44e028fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Required here or by email to process request.</value>
      <webElementGuid>bc6398a4-efdc-4ed5-8359-7c103cc3b9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brad Benson</value>
      <webElementGuid>0c748422-7f44-4460-a09a-9702a10a4cd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1446521439.133_references&quot;)</value>
      <webElementGuid>6816ad1c-24ce-43c1-8855-fa283c6ae3d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='profile_group-1446521439.133_references']</value>
      <webElementGuid>bc443b3c-52fd-4bb1-ab19-124835474db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446521439.133']/div[6]/div[2]/textarea</value>
      <webElementGuid>eb53c092-1e1e-41e7-9e59-c38118a19fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='References*'])[1]/following::textarea[1]</value>
      <webElementGuid>4bab1951-9396-420c-9798-03c36cafc22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board of Directors*'])[1]/following::textarea[1]</value>
      <webElementGuid>55f6ff62-219e-4e31-a8ae-0362320e89ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year Founded'])[1]/preceding::textarea[1]</value>
      <webElementGuid>18c0be44-667a-47af-ba74-5a7b5db55574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brad Benson']/parent::*</value>
      <webElementGuid>fa1fd400-5a04-4bbe-be38-898bdaeabec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/textarea</value>
      <webElementGuid>b76248e1-7db7-4410-85f7-685d14cbf725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'profile[group-1446521439.133][references]' and @id = 'profile_group-1446521439.133_references' and @placeholder = 'Required here or by email to process request.' and (text() = 'Brad Benson' or . = 'Brad Benson')]</value>
      <webElementGuid>a32560a3-9312-4d02-b277-a2808f3b990f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
