<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_United States</name>
   <tag></tag>
   <elementGuidId>2cfc94da-0f52-4762-961a-b74e1fe178f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1448248787.895_recruit_countries'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c8be0f83-0a84-4a80-af62-fe8056ab7808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1448248787.895_recruit_countries</value>
      <webElementGuid>d04fe3d2-9e8c-4396-8e07-247685b32bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>4f72ab13-d69f-4734-908a-1f7e34aba2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1448248787.895][recruit_countries][]</value>
      <webElementGuid>2c77d57d-6a6a-4bae-a6cf-0f12bf23db62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>United States</value>
      <webElementGuid>b1d1ca08-5a49-4e36-9754-24c69143713f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1448248787.895&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1448248787.895_recruit_countries&quot;]</value>
      <webElementGuid>c7ff5e99-3717-4ecf-a869-5d425d035d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1448248787.895_recruit_countries'])[4]</value>
      <webElementGuid>0826ea19-d3de-4b6f-8eeb-56cdcfb48731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1448248787.895']/div/div[3]/div[4]/div/input</value>
      <webElementGuid>7c35c4ae-5bba-461b-ab7b-265e067cc815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div[3]/div[4]/div/input</value>
      <webElementGuid>9a23c2e9-8615-4528-b3e7-eb1f782ad414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1448248787.895_recruit_countries' and @type = 'checkbox' and @name = 'profile[group-1448248787.895][recruit_countries][]']</value>
      <webElementGuid>89d4323f-16c9-4c43-b99e-289bd4c3773c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
