<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxes_Languages</name>
   <tag></tag>
   <elementGuidId>ad1e58c3-d28f-4657-ae3c-3adb1db00d8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_group-1613448548.497_languages']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c9895f7-9968-4019-a771-9cc6b2bcb0d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_group-1613448548.497_languages</value>
      <webElementGuid>019ad954-5bad-4580-8441-9a6f4ff6d525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b01634c1-d510-4f00-bb64-2b106bb2a900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job[group-1613448548.497][languages][]</value>
      <webElementGuid>44216dd0-499a-46b0-ada7-4901562009b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>English is a native language</value>
      <webElementGuid>441ee2ab-10da-4715-b86c-12a3d8c84fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>457240ad-3a7b-48a5-b5c8-85cd188329a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1613448548.497&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;job_group-1613448548.497_languages&quot;]</value>
      <webElementGuid>173dacbb-64b5-4373-be69-57d74cf643dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_group-1613448548.497_languages']</value>
      <webElementGuid>d5e682a2-96d9-45a2-a8ea-8f84b32ec50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1613448548.497']/div[5]/div[2]/div/div/input</value>
      <webElementGuid>c50c2597-fcb3-45ec-a1f8-2d0a07557ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>4c49a6eb-c75b-4012-bf66-9b77ec1c5451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'job_group-1613448548.497_languages' and @type = 'checkbox' and @name = 'job[group-1613448548.497][languages][]']</value>
      <webElementGuid>17eca873-142a-4bd9-9d33-95e60ec9caf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
