<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxes_Cross-Cultural Experience</name>
   <tag></tag>
   <elementGuidId>243eed45-2c40-4527-acbe-340e788356bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_group-1613448548.497_cross-cultural_experience']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5791d2d-e055-4f96-994b-38f662008622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_group-1613448548.497_cross-cultural_experience</value>
      <webElementGuid>79b30626-d97c-4bee-8552-c07efb5c6027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f8eda1f-3aaf-4d6d-9927-306a48809a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job[group-1613448548.497][cross-cultural_experience][]</value>
      <webElementGuid>c7b02adc-fb04-4bf3-a4d4-46fbbd3295d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>(!) Not served in a culture other than my own</value>
      <webElementGuid>f2df8f74-7f68-47b5-98c4-8cc724124472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1613448548.497&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-small-checkbox&quot;]/div[1]/input[@id=&quot;job_group-1613448548.497_cross-cultural_experience&quot;]</value>
      <webElementGuid>2c8c0181-8fe4-493a-9331-a98c988d0806</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_group-1613448548.497_cross-cultural_experience']</value>
      <webElementGuid>367bc3e0-d989-43e8-911c-0e6cd73ebe90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1613448548.497']/div[4]/div[2]/div/div/input</value>
      <webElementGuid>44281c50-41c9-4e90-a010-0bb9ac37df8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>5bc28df9-fd41-492f-b34c-47c922def651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'job_group-1613448548.497_cross-cultural_experience' and @type = 'checkbox' and @name = 'job[group-1613448548.497][cross-cultural_experience][]']</value>
      <webElementGuid>39f246ef-7ab6-4a75-8411-e293b45671ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
