<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Terms and Conditions</name>
   <tag></tag>
   <elementGuidId>c502a1c3-2d7e-4deb-95da-08dd83893bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1456435706.801_terms_and_conditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>678d251d-2830-4cd9-a551-67144bf9cb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>terms_and_conditions</value>
      <webElementGuid>06a0915f-1bcc-4735-a256-758000828edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>156</value>
      <webElementGuid>bad0900c-f585-4369-84b8-579c97d97f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1456435706.801][terms_and_conditions]</value>
      <webElementGuid>8a530afc-9fcf-4551-94ec-7b625757d3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1456435706.801_terms_and_conditions</value>
      <webElementGuid>553c72ff-d4b9-4396-9210-3e36384e7006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>72337b43-e1f8-4b38-a64d-ee662bb27142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3a4f976c-f9fd-4292-a36b-e4d31fd15867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>checked</value>
      <webElementGuid>5edb47de-3fd6-4f12-818f-d7409653c710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1456435706.801_terms_and_conditions&quot;)</value>
      <webElementGuid>e4f63aef-6497-42ec-b117-a14196538629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1456435706.801_terms_and_conditions']</value>
      <webElementGuid>a8ee6159-ef82-4198-8caa-15e405af057c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1456435706.801']/div[4]/div[3]/input</value>
      <webElementGuid>f65f1856-1f48-4f10-b80b-7b27c2148517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[4]/div[3]/input</value>
      <webElementGuid>2e794a9b-c061-4c18-b6a8-96c8d154624c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'profile[group-1456435706.801][terms_and_conditions]' and @id = 'profile_group-1456435706.801_terms_and_conditions' and @type = 'checkbox' and @checked = 'checked']</value>
      <webElementGuid>c45caa50-6aa9-41dc-a9fe-f2f68c57a350</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
