<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Comments</name>
   <tag></tag>
   <elementGuidId>a06448fc-39bf-4fba-9e42-b002ab671720</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='profile_group-1597797207.546_comments:']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e9be981d-59e1-47b9-b2b4-3e472e871f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>comments:</value>
      <webElementGuid>04f1eaf8-07dc-4a23-875b-3f400d14ab1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>63</value>
      <webElementGuid>f1486c53-1dea-4499-965f-d79aa9599ab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-large-field</value>
      <webElementGuid>a6a228fb-fd71-4e3f-b50e-d0ba9bc8d54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1597797207.546][comments:]</value>
      <webElementGuid>c4eff92d-e59b-4d82-a3ae-a5e0aa9bbb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1597797207.546_comments:</value>
      <webElementGuid>bd0e2ec6-6a2d-4352-be6a-c77267ed9f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1597797207.546_comments:&quot;)</value>
      <webElementGuid>c5dd467b-dfb3-4882-9d38-c6f58b77720c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='profile_group-1597797207.546_comments:']</value>
      <webElementGuid>0b445c29-1981-4de3-bcce-6b1e71aedc43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1597797207.546']/div[5]/div[3]/textarea</value>
      <webElementGuid>e41a6635-59a2-4417-b6e4-2d786ddddaac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>c8011d98-c704-4ab9-9401-0f47ea780ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'profile[group-1597797207.546][comments:]' and @id = 'profile_group-1597797207.546_comments:']</value>
      <webElementGuid>9f381bac-0469-45ea-bc61-8c18da8dc328</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
