<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkboxes_Paid and Volunteer Positions</name>
   <tag></tag>
   <elementGuidId>a3b47da5-9e30-49b2-94af-b36f824cc326</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='job_group-1613449047.954_financial_support']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4dccc633-ba51-47f5-ac80-45d13a7b8085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_group-1613449047.954_financial_support</value>
      <webElementGuid>69acc2cf-58a7-4edb-a438-0da6b312a4c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1e9649bc-8dd6-4233-bee6-2fc2a25b9d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job[group-1613449047.954][financial_support][]</value>
      <webElementGuid>8d898c31-93d6-4cbc-a43a-16e2f596a7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Volunteer/self-supported position</value>
      <webElementGuid>fa4526de-782c-41f1-ade9-e9d86e2ac48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1613449047.954&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-medium-checkbox&quot;]/div[1]/input[@id=&quot;job_group-1613449047.954_financial_support&quot;]</value>
      <webElementGuid>f57aabad-c9a7-4809-8355-7eb8b9d35a4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='job_group-1613449047.954_financial_support']</value>
      <webElementGuid>6e3627dc-ff3e-499c-b0ae-db734a2acf3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1613449047.954']/div/div[2]/div/div/input</value>
      <webElementGuid>65f0727b-16b4-4e11-89db-4bb7aeed5cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[36]/div/div[2]/div/div/input</value>
      <webElementGuid>47db4ff6-9a6f-42d9-8500-cf040b5ea40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'job_group-1613449047.954_financial_support' and @type = 'checkbox' and @name = 'job[group-1613449047.954][financial_support][]']</value>
      <webElementGuid>def7cb97-c88d-485a-8edb-9758f815a99c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
