<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Housing</name>
   <tag></tag>
   <elementGuidId>adce27cc-3053-4983-824a-397ee74c4abe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='job_group-1613449047.954_housing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>aea2474e-a3bc-493a-8044-45fb88600114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>housing</value>
      <webElementGuid>baa80b5d-226b-4023-90a4-b00528f77ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>0cd9e25c-8a99-4232-a25c-ec0a3c58abb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-small-field</value>
      <webElementGuid>ca8e9bfa-88cb-421d-8e0f-cbf1aa1beab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>job[group-1613449047.954][housing]</value>
      <webElementGuid>dd54f3b5-c8dd-44a1-913e-3c87af829013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_group-1613449047.954_housing</value>
      <webElementGuid>dba0d1d2-3c37-4ae5-b20a-62ae6a1d3c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;job_group-1613449047.954_housing&quot;)</value>
      <webElementGuid>66193d85-f485-4c12-bb5f-965251d03868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='job_group-1613449047.954_housing']</value>
      <webElementGuid>656a562d-5ffb-47c8-a127-55a57e9f5629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1613449047.954']/div[4]/div[2]/textarea</value>
      <webElementGuid>bcc24853-0d59-4c7e-b200-89bfa382bcb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/textarea</value>
      <webElementGuid>20abeb87-aaa9-4925-8344-eac9e99657f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'job[group-1613449047.954][housing]' and @id = 'job_group-1613449047.954_housing']</value>
      <webElementGuid>2dd401ca-f66c-4b53-b083-970829d41b6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
