<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Missio Nexus</name>
   <tag></tag>
   <elementGuidId>b3526374-1fd6-4458-a277-b16bff13c77c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='registration_group-1446560994.446_memberships'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b79c437-95b5-4c7a-84cf-f0d8e7bd3eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1446560994.446_memberships</value>
      <webElementGuid>f18d1dd4-3bef-454f-8dfc-6faa4269d671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>821695be-415c-4ad7-ab4f-92ad5717c847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1446560994.446][memberships][]</value>
      <webElementGuid>35218591-48ce-4a97-acd6-9bfc8e4211ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Missio Nexus</value>
      <webElementGuid>daf8a884-fcd7-4671-9376-0a1ee47ce904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1446560994.446&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-checkbox mn-medium-checkbox&quot;]/div[2]/input[@id=&quot;registration_group-1446560994.446_memberships&quot;]</value>
      <webElementGuid>c75f9012-3782-4fd7-befa-7f1338ad398a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='registration_group-1446560994.446_memberships'])[2]</value>
      <webElementGuid>daa6cb67-7996-4431-a2ef-6bf7a9fd3561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446560994.446']/div[9]/div[2]/div/div[2]/input</value>
      <webElementGuid>f7458170-d2cc-4a54-aace-33b0bd30a138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div[2]/input</value>
      <webElementGuid>dc581a23-d188-4fb0-b63a-a13b8d614e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group-1446560994.446_memberships' and @type = 'checkbox' and @name = 'registration[group-1446560994.446][memberships][]']</value>
      <webElementGuid>ac030b04-3103-465d-b7ba-6342d940963e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
