<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Switch back to Chris Kosieracki</name>
   <tag></tag>
   <elementGuidId>ad8f479e-1389-449d-b125-97c4aaea019e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user_switching_switch_on > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='user_switching_switch_on']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9dbe010-3463-4819-b94f-2b7d717b8c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/login-here?action=switch_to_olduser&amp;nr=1&amp;_wpnonce=2345beaa04&amp;redirect_to=https%3A%2F%2Fjourney.missionnext.org%2Fdashboard</value>
      <webElementGuid>1a013bae-2944-4e2e-a2ad-982730968319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Switch back to Chris Kosieracki</value>
      <webElementGuid>4ac79f8d-ada3-4154-8610-918e4184f199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_switching_switch_on&quot;)/a[1]</value>
      <webElementGuid>c0873ef7-1a23-4dbc-9325-2bcadf5ebb4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='user_switching_switch_on']/a</value>
      <webElementGuid>b0d5de76-6486-4fe7-8ac6-ce43f3ed8264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Switch back to Chris Kosieracki')]</value>
      <webElementGuid>bbda3db5-daff-4b63-9e61-b3b9a13c38b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linkedin'])[1]/following::a[2]</value>
      <webElementGuid>c0f500b3-a2d5-4175-b0ca-b6208e42dd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Instagram'])[1]/following::a[3]</value>
      <webElementGuid>7fefb8ca-35b8-414d-8187-cafbc7e48cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Switch back to Chris Kosieracki']/parent::*</value>
      <webElementGuid>e1956444-1d07-4a0d-be5a-cde759e12f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/login-here?action=switch_to_olduser&amp;nr=1&amp;_wpnonce=2345beaa04&amp;redirect_to=https%3A%2F%2Fjourney.missionnext.org%2Fdashboard')]</value>
      <webElementGuid>71325fd7-edef-4cd8-9cdc-0593e6919775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/p/a</value>
      <webElementGuid>f576056a-0b3a-4f26-a2a3-3f7a6ed64625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/login-here?action=switch_to_olduser&amp;nr=1&amp;_wpnonce=2345beaa04&amp;redirect_to=https%3A%2F%2Fjourney.missionnext.org%2Fdashboard' and (text() = 'Switch back to Chris Kosieracki' or . = 'Switch back to Chris Kosieracki')]</value>
      <webElementGuid>618ae7fc-6826-4da5-bec6-eb20f54d1000</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
