<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MissionArmor</name>
   <tag></tag>
   <elementGuidId>31acbbbc-3b2c-41b9-865b-3ed479f2fa48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-77193 > a.elementor-sub-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/header/section[1]/div/div[2]/div/div/div/nav[2]/ul/li[2]/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e40896ec-d6bb-47ff-83d9-1b6d9b59dc25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionworks.global/missionarmor/</value>
      <webElementGuid>9767a72f-ecc1-40a9-9b9f-50a185d64c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-sub-item</value>
      <webElementGuid>99468fbd-c934-42d2-b1e1-1719936c5863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MissionArmor</value>
      <webElementGuid>52a5c472-24e1-42b1-99dd-9185f0c9706d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-1779905485692575-4&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-77193&quot;]/a[@class=&quot;elementor-sub-item&quot;]</value>
      <webElementGuid>4f9e8f48-10c4-4491-ac67-009c663c55b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-1779905485692575-4']/li[3]/a</value>
      <webElementGuid>0f7c8479-266e-422a-b98d-14c43156d4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MissionArmor')]</value>
      <webElementGuid>ea735c0a-d278-4249-8e30-79c410e5c5de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionLinked'])[1]/following::a[1]</value>
      <webElementGuid>0433f2ae-183d-4ff1-ae5e-483714cdeb12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coaching'])[1]/following::a[2]</value>
      <webElementGuid>b93909b7-01ff-456a-9b63-27b88c1145bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionExcellence'])[1]/preceding::a[1]</value>
      <webElementGuid>50644264-7a83-4250-b832-498926bc71be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[1]/preceding::a[2]</value>
      <webElementGuid>f7699c25-fcd6-4ee8-a77d-2a3e94d126c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MissionArmor']/parent::*</value>
      <webElementGuid>5562537d-2d74-4c46-8460-8d55e22d203a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://missionworks.global/missionarmor/')]</value>
      <webElementGuid>3b5fc01d-a192-4f7b-ace9-7cf698121cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[3]/a</value>
      <webElementGuid>af3fe483-612b-430d-8d20-e676dfae3723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionworks.global/missionarmor/' and (text() = 'MissionArmor' or . = 'MissionArmor')]</value>
      <webElementGuid>86e8b549-a091-4a9b-ba8b-9d7c0b8ed5fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
