<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_Assigned App</name>
   <tag></tag>
   <elementGuidId>3784361d-657f-46f7-b267-1a99edd42e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form[name=&quot;data_groups&quot;] > p > table > tbody > tr:nth-of-type(2) > td:nth-of-type(3)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1b541cb5-d6e1-4114-b3bc-b783fb7b7ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QuickStart</value>
      <webElementGuid>86800556-5e01-4eac-91aa-59ed3cc7f66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/table[1]/tbody[1]/tr[2]/td[2]/table[1]/tbody[1]/tr[3]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[1]/td[2]/span[@class=&quot;body&quot;]/div[1]/form[1]/p[1]/table[1]/tbody[1]/tr[2]/td[3]</value>
      <webElementGuid>8fa343df-5c46-49f0-83f1-4638d630fbe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::td[3]</value>
      <webElementGuid>a14518f0-d482-48f4-ab15-4751cb964c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App ID'])[2]/following::td[4]</value>
      <webElementGuid>60e396ea-1fc2-4edd-ae35-5c4635170c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[5]/preceding::td[1]</value>
      <webElementGuid>2df00299-3879-4519-a3b1-2e6812e97241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App ID'])[3]/preceding::td[2]</value>
      <webElementGuid>c27933a6-45a3-410f-80f0-a6ebf9612392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QuickStart']/parent::*</value>
      <webElementGuid>e3fe018e-c976-4b4c-be7c-11ae3fff3e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>7099453f-73f8-46db-9aef-7fce745f66b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'QuickStart' or . = 'QuickStart')]</value>
      <webElementGuid>e678f06c-a1c5-4703-8288-25a6d86ab0ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
