<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Education</name>
   <tag></tag>
   <elementGuidId>5c8aff4d-fdf3-4841-a39c-9006fc7feaad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.left.subscription-list > a.btn.btn-success</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/div/div[2]/div[2]/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>871d1951-22bd-48e7-8ce0-35245e98a46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>7eab3271-bae6-44e0-bca8-de825f5a9a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://education.missionnext.org/dashboard</value>
      <webElementGuid>ccb984c3-13c1-4591-b23c-c8acc889a9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Education</value>
      <webElementGuid>68fc5b6c-2f68-4dba-9e67-984652d0ee52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;dashboard-applications&quot;]/div[@class=&quot;col-md-12&quot;]/p[@class=&quot;left subscription-list&quot;]/a[@class=&quot;btn btn-success&quot;]</value>
      <webElementGuid>3184ac46-2f96-4012-82b5-0f64a36f0839</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/div/div[2]/div[2]/div/p/a</value>
      <webElementGuid>0bf858f5-69d4-47c9-87c7-305403718b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Education')])[5]</value>
      <webElementGuid>f325ebfa-3724-4db5-80ab-1976fedb57f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, The CCK TEST Education Partner'])[1]/following::a[1]</value>
      <webElementGuid>e967f6dc-4d92-427a-b890-a21b8832b89d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renew Now'])[1]/following::a[1]</value>
      <webElementGuid>4610646d-e75a-4d56-8694-0bdcda4e0360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inquiries0'])[1]/preceding::a[1]</value>
      <webElementGuid>af0320fb-333b-41b1-8498-8ae3fdb9b3c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorites0'])[1]/preceding::a[2]</value>
      <webElementGuid>c73dff0b-4b31-4d8b-97f8-1ce6414f54ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://education.missionnext.org/dashboard')]</value>
      <webElementGuid>177c261e-9a6c-4d3e-9af2-ebe951c42b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>5f2961af-2ecc-4075-8ce7-406ce5e8fc2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://education.missionnext.org/dashboard' and (text() = 'Education' or . = 'Education')]</value>
      <webElementGuid>3917bd56-eff1-49f2-b050-3233410ee40e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
