<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search Users</name>
   <tag></tag>
   <elementGuidId>e78a73ef-1b94-48e3-9a42-06407a965d7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#user-search-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='user-search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c5f522f-c53c-4638-9cce-52f134859377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>7b68e2bb-8d56-43da-adb2-7eab6d0fd20b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>user-search-input</value>
      <webElementGuid>32c1d11a-783a-4270-a041-d7f352474950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>662e6d2e-180b-4991-9549-d79aa2c20a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user-search-input&quot;)</value>
      <webElementGuid>43bbf0d3-c67e-4ca7-991f-6cf0baf0c55d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='user-search-input']</value>
      <webElementGuid>81f63320-46b1-47da-b0a3-5c9bbabb600f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wpbody-content']/div[3]/form/p/input</value>
      <webElementGuid>e5a9d446-0c22-411a-9dc2-d6fe2071ae37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/p/input</value>
      <webElementGuid>f48812c9-3f8c-4406-a8ac-be2e83da00ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'user-search-input' and @name = 's']</value>
      <webElementGuid>4ba55998-8547-4ad5-b8c0-ef76034c9f42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
