<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ministry Preferences_profilegroup-1446522088.64ministry_preferences</name>
   <tag></tag>
   <elementGuidId>cab76991-ef16-480e-9d2e-7134d0ac6d6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1446522088.64_ministry_preferences']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eaaa1bb9-3818-4bc2-a431-7cf49f198102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446522088.64_ministry_preferences</value>
      <webElementGuid>212aecbf-4f57-4763-a752-01bc8ab8e5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e0dc9358-550f-4b1c-87b0-ca920a145272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446522088.64][ministry_preferences][]</value>
      <webElementGuid>afe36e08-601f-4c15-b4dd-d62f49d0432a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Adult Men</value>
      <webElementGuid>940b7ea5-eb32-4934-a16c-3ab21890da18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1446522088.64&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1446522088.64_ministry_preferences&quot;]</value>
      <webElementGuid>cc578d0f-6613-474b-a064-b95137019ef5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1446522088.64_ministry_preferences']</value>
      <webElementGuid>693c89b3-3b54-49dc-a64e-66522ac5b09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446522088.64']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>bb30020e-f4cd-4147-893a-7997b1eaeef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>e1fabbc7-105d-4d95-adcb-684db54eab6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1446522088.64_ministry_preferences' and @type = 'checkbox' and @name = 'profile[group-1446522088.64][ministry_preferences][]']</value>
      <webElementGuid>c1cc683a-7aa3-4b2d-8100-f3596f85e4ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
