<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Need Specific IT Positions_profilegroup-1446522088.64need_specific_it_positions</name>
   <tag></tag>
   <elementGuidId>ee8e331b-26a7-41d9-ab2a-251504c4f4aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1446522088.64_need_specific_it_positions?']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a5b9c7a-2cfd-4cf5-b130-86b7aaa945a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dependant</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2328471f-e882-4ff4-8889-1fc2b7af60e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>need_specific_it_positions?</value>
      <webElementGuid>8d267e06-fd47-4113-a7f6-0cdf40b4a242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>175</value>
      <webElementGuid>e363a1fa-a7f7-4ac0-9513-4f69dc1ad9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1446522088.64][need_specific_it_positions?]</value>
      <webElementGuid>4b963a91-4a00-4768-993d-1da487beec88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1446522088.64_need_specific_it_positions?</value>
      <webElementGuid>dad52308-fc87-4bbf-b2e3-8e69898ba8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ad9ba40f-9caa-48f1-aae1-f657a79fd706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f6d07ce2-347e-4b4a-8769-e34e7de2c566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group-1446522088.64_need_specific_it_positions?&quot;)</value>
      <webElementGuid>3b05fe72-dca0-461c-ae15-5e177649c71c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1446522088.64_need_specific_it_positions?']</value>
      <webElementGuid>8c030092-15b8-4520-a5c6-661670454bb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1446522088.64']/div/div[3]/input[2]</value>
      <webElementGuid>115b64e5-538a-4ed5-b589-e80170f99bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input[2]</value>
      <webElementGuid>ce1b952a-0927-4f5b-bc49-79a3a9b53190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'profile[group-1446522088.64][need_specific_it_positions?]' and @id = 'profile_group-1446522088.64_need_specific_it_positions?' and @type = 'checkbox']</value>
      <webElementGuid>329f93fd-cb84-407b-ba85-050c296a5808</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
