<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username</name>
   <tag></tag>
   <elementGuidId>0117d647-920e-4542-9dab-b4d3e1465865</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registration_main_fields_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_main_fields_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5ee21bd-a3a3-4fbc-a3c8-9d87fafc363b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-input </value>
      <webElementGuid>122937f0-919e-4593-b615-b596f48d2bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_main_fields_username</value>
      <webElementGuid>c84e5e97-3bf2-4f33-a312-df5f6c84627f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[main_fields][username]</value>
      <webElementGuid>50ed5e0e-c1a1-41ec-93c4-08bb0ce581af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4ffaff2-0959-4fef-a5cc-06f413666dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6cee1202-867b-413c-a0db-217d86064bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_main_fields_username&quot;)</value>
      <webElementGuid>ec3a4658-6a0c-4503-90b4-5ee5096cca59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_main_fields_username']</value>
      <webElementGuid>27c13f94-ee19-4e4a-9c06-82a7c7ce6c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_fields']/div/div[2]/input</value>
      <webElementGuid>710c8bea-2a42-4210-b7a2-a4e2873ccaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>39dae7a3-e8d8-44a9-85b3-199e90b310ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_main_fields_username' and @name = 'registration[main_fields][username]' and @type = 'input']</value>
      <webElementGuid>31104c15-80af-4db4-9fef-b9c9e62f0546</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
