<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MissionConnexion</name>
   <tag></tag>
   <elementGuidId>56ce3e65-c6b3-4228-a468-b6cfb634ebdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='MissionConnexion']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.elementor-sub-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>90f19fd4-4bae-49a7-bd01-589ba7ffefe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://missionconnexion.global/</value>
      <webElementGuid>f9bd3157-1d79-43e4-96c3-6df0b8d3d3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-sub-item</value>
      <webElementGuid>e3bb1aa0-a8a1-466b-bca5-8f9e66c7ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MissionConnexion</value>
      <webElementGuid>d43e8ffb-d3df-4a96-b913-fb542f323763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sm-17799005104324214-2&quot;)/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-77187&quot;]/a[@class=&quot;elementor-sub-item&quot;]</value>
      <webElementGuid>3d3fed18-6aed-494b-b2ea-4306787b2f56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sm-17799005104324214-2']/li/a</value>
      <webElementGuid>2529b2ec-960e-416c-bbf9-b86a5815b005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MissionConnexion')]</value>
      <webElementGuid>9a380d51-4ee5-4805-a3e2-94ab62065b0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to content'])[1]/following::a[3]</value>
      <webElementGuid>03ff02b2-8206-4a9a-ba3b-b08f11913cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MIssionNext'])[1]/preceding::a[1]</value>
      <webElementGuid>3bd6680e-d11f-4a23-8544-f7b36ce68e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MissionGuide'])[1]/preceding::a[2]</value>
      <webElementGuid>207d74c6-f5d3-4e9f-b2d0-c6abca799a37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MissionConnexion']/parent::*</value>
      <webElementGuid>bb4ef3a8-cb75-4631-b311-04b6133ac849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://missionconnexion.global/')]</value>
      <webElementGuid>4a4cd5a1-a9d4-450d-8be9-476d892c68bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/li/a</value>
      <webElementGuid>21c4db96-5158-4a87-832b-172594501f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://missionconnexion.global/' and (text() = 'MissionConnexion' or . = 'MissionConnexion')]</value>
      <webElementGuid>f9b000d6-04d9-49f1-81ee-404cd08225ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
