<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Thank you for filling out our online form</name>
   <tag></tag>
   <elementGuidId>81f01e73-3599-4bee-ac0c-07e6f11a1843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-1075']/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.wp-block-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>25a12856-0267-4b6a-978a-76d8fa40cedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-heading</value>
      <webElementGuid>08992e13-f4a4-416c-a5d7-b71a3cb3f634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you for filling out our online form!</value>
      <webElementGuid>9c0d4c50-76d9-4420-a13d-9ce09e9b2c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-1075&quot;)/div[@class=&quot;entry-content clear&quot;]/h2[@class=&quot;wp-block-heading&quot;]</value>
      <webElementGuid>83f8d453-8011-4002-9449-5ee14845b059</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-1075']/div/h2</value>
      <webElementGuid>42b41095-ee9c-46c9-b0ed-e46c48e92705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Us'])[2]/following::h2[1]</value>
      <webElementGuid>511e2102-9f2e-43ca-98c9-f89f1180136e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACT US'])[1]/following::h2[1]</value>
      <webElementGuid>07407e98-1fab-43e1-875e-2e6ad96c898a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 1: COMPLETED – Filled out online form'])[1]/preceding::h2[1]</value>
      <webElementGuid>4f27655f-fb8f-4196-b62f-dfcb38dea183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Step 2:'])[1]/preceding::h2[1]</value>
      <webElementGuid>5a37e03e-b49b-452e-8402-151b62b6ec85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you for filling out our online form!']/parent::*</value>
      <webElementGuid>6d3e4aed-6f35-4df1-86be-ad275fc170a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>22a6550c-8b98-4d72-b276-74d7732bb628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Thank you for filling out our online form!' or . = 'Thank you for filling out our online form!')]</value>
      <webElementGuid>fb5e62e4-43e3-4edc-90a8-3ca2c8596d42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
