<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remember Me_wp-submit</name>
   <tag></tag>
   <elementGuidId>7f28549e-c9f1-4785-88fa-df8a650f60bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wp-submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wp-submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0891bf0-5404-47bd-aadf-422b4511bc0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>72817c53-d929-4519-b745-ba576d509e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wp-submit</value>
      <webElementGuid>b1d73c04-3a1c-40ba-8371-06660cf9c936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wp-submit</value>
      <webElementGuid>718fba0c-e3e5-4fed-9aa8-c09e81c52d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-primary button-large</value>
      <webElementGuid>f07e572d-f89f-4b9e-84a5-4235739c0649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log In</value>
      <webElementGuid>ef7c7399-efee-47e3-9606-694d7b96a488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp-submit&quot;)</value>
      <webElementGuid>0aad5222-67ea-4a58-a946-098d383e8c14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wp-submit']</value>
      <webElementGuid>95470da1-1306-4efb-bdf5-11d12881c5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/p[3]/input</value>
      <webElementGuid>eb152618-883e-4c9f-aab3-877c00c40be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]/input</value>
      <webElementGuid>de9ac82c-d021-46c6-8e58-3a990006e100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'wp-submit' and @id = 'wp-submit']</value>
      <webElementGuid>2958dae6-554f-4f39-8fd3-b51d5fe51fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
