<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CallingI have a clear call to missio_423c8d</name>
   <tag></tag>
   <elementGuidId>bc30f43d-1f91-463b-9d97-91671ab7dc6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input_3_39']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_3_39</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>827332eb-eb37-42c6-af5e-ab95b5456910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_39</value>
      <webElementGuid>ba6a8627-4d81-4cde-bf21-4e6c39935061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_3_39</value>
      <webElementGuid>9f7a2a5d-afac-4aad-85d8-f216472d3f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium gfield_select</value>
      <webElementGuid>c9b35666-d253-4f40-bbf5-2f95253d774d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cc807d0c-31fb-4b9a-984c-ab279ce39baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>66685cb7-a306-4322-aaba-58e5c6fd50a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Calling*I have a clear call to missions.I feel like God is calling me to a life of missions.</value>
      <webElementGuid>9f1c37f1-d974-4433-bef1-4d9e0701fafa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_3_39&quot;)</value>
      <webElementGuid>40733edc-294b-4a02-a05b-cc4e47677fe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input_3_39']</value>
      <webElementGuid>7a0766b9-37bc-4873-9a2a-972a4bfd0fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='field_3_39']/div/select</value>
      <webElementGuid>f924aea9-5eff-48bb-a663-0b0675575968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>cbc79d65-de0a-4894-9e40-3e28a02f7b0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/preceding::select[1]</value>
      <webElementGuid>bbd5875a-8d55-465e-ad08-57b1b52f6521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/select</value>
      <webElementGuid>99de2f84-1abd-47e2-bfea-5ce20ae0c6fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'input_39' and @id = 'input_3_39' and (text() = 'Calling*I have a clear call to missions.I feel like God is calling me to a life of missions.' or . = 'Calling*I have a clear call to missions.I feel like God is calling me to a life of missions.')]</value>
      <webElementGuid>2205fa71-d033-459c-a914-db6377bb7ace</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
