<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Source of financesDonations  raise f_07a00e</name>
   <tag></tag>
   <elementGuidId>fbbed3ff-13a3-4c76-952c-106343af1dbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='input_3_65']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input_3_65</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2af24676-8483-4a60-b9be-3ea29e99c5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>input_65</value>
      <webElementGuid>d15676dd-ddfd-45ba-8318-870918392f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input_3_65</value>
      <webElementGuid>c95a81fe-a12f-43f8-963d-bf394350301a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>medium gfield_select</value>
      <webElementGuid>64c7859b-6c00-4a4f-9ad1-595cffbe4774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>51cabcad-de5c-4f0d-8105-8a1f4baee27e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>25e61f99-42f9-4091-9751-d3240a0da793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Source of finances*Donations – raise financial support from churches &amp; individualsSelf-supported – using personal savings and incomeRaise business capital – start a self-supporting businessGet a job in country – earn a liveable salary from your professionAny of the above</value>
      <webElementGuid>bdbe985d-92b5-48d1-8b94-c3683829b1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input_3_65&quot;)</value>
      <webElementGuid>f8d92d5e-ddda-429a-9509-93e9df1b619e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='input_3_65']</value>
      <webElementGuid>84da2892-ff83-41d7-800c-3ac8cc1e4a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='field_3_65']/div/select</value>
      <webElementGuid>c5b7cae9-cd21-457b-8677-7df3bf0b8111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>c2b93895-a0f0-4ff3-98a9-19434127b9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tell us about your calling! (People group, country, religion)'])[1]/preceding::select[1]</value>
      <webElementGuid>b85b5a4a-ebaa-441e-bba1-23483864350f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='When would you be looking to go?'])[1]/preceding::select[1]</value>
      <webElementGuid>b3603400-c098-449e-80e1-61ff939dec9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/select</value>
      <webElementGuid>03883508-88ca-4ef6-8074-de63ad341779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'input_65' and @id = 'input_3_65' and (text() = 'Source of finances*Donations – raise financial support from churches &amp; individualsSelf-supported – using personal savings and incomeRaise business capital – start a self-supporting businessGet a job in country – earn a liveable salary from your professionAny of the above' or . = 'Source of finances*Donations – raise financial support from churches &amp; individualsSelf-supported – using personal savings and incomeRaise business capital – start a self-supporting businessGet a job in country – earn a liveable salary from your professionAny of the above')]</value>
      <webElementGuid>3d029786-665d-42d5-86c6-979e227d5798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
