<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization</name>
   <tag></tag>
   <elementGuidId>ef5f0585-f0eb-4b30-a773-f5430db704f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group1_organization_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#profile_group1_organization_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2071be0-ed36-4c5d-b028-c108f813a361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>organization_name</value>
      <webElementGuid>5ee04841-74a0-4b8a-8d27-3d35f92dbdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>3139eafe-18c4-4d72-847f-2b9fac076f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-large-field</value>
      <webElementGuid>314303ac-9a17-4672-91b3-b59887b78797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group1_organization_name</value>
      <webElementGuid>d49e0847-5493-43d7-be4a-efcd57c8c888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group1][organization_name]</value>
      <webElementGuid>5cb94866-5ed5-4b28-b606-1a69bd20a0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6202a635-6e7d-44d4-a43f-aac19f83609e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a9eac46-3ec5-4658-98de-5f49ec17832a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>The CCK TEST Education Partner</value>
      <webElementGuid>4ceb282d-4edf-46b7-bf9a-6560698883d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group1_organization_name&quot;)</value>
      <webElementGuid>3df438cc-0762-4495-9268-b1b26c743c04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group1_organization_name']</value>
      <webElementGuid>4bd35b25-62df-40a5-a7af-ce06c994cfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div/div[2]/input</value>
      <webElementGuid>29fac046-06e0-4beb-8d3c-4bcfd21677cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>777e623b-2795-42d7-918d-97d20e1d581d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group1_organization_name' and @name = 'profile[group1][organization_name]' and @type = 'input']</value>
      <webElementGuid>61684498-34bf-4203-9886-2bafa8147331</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
