<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization City</name>
   <tag></tag>
   <elementGuidId>ef8d5499-b9a6-42a3-80e9-ca47324d09c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_group1_school_city</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group1_school_city']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0c71991-49ac-47d5-bdb3-55bc616272eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>school_city</value>
      <webElementGuid>d8ea45ce-7b8c-4d8a-975e-f5f13bd73dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>5945cc6e-6c1a-49dc-a55a-6c88ecd7abff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-medium-field</value>
      <webElementGuid>3765f63e-bb7c-4b57-aaf9-77dec1bd23ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group1_school_city</value>
      <webElementGuid>59637aaf-093e-4413-98cf-d823f4bafe5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group1][school_city]</value>
      <webElementGuid>d963cbd9-94d8-4f9a-b68a-b26f8ebfa6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7569e77d-1d1b-4384-9c87-055228ad9d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9185789a-5345-481b-842f-c8c3453d29a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group1_school_city&quot;)</value>
      <webElementGuid>1fcfc978-ab6d-435f-9ad2-c30b2dd32cd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group1_school_city']</value>
      <webElementGuid>377d5beb-4092-468a-8703-a85763ed81b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[12]/div[3]/input</value>
      <webElementGuid>6e0e0a0b-6c3f-4100-b93d-c9ee3c8f1081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>86ac22f9-86c4-4f54-8c4d-1f8f28272bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group1_school_city' and @name = 'profile[group1][school_city]' and @type = 'input']</value>
      <webElementGuid>09fafe29-a71b-4d55-971c-cae2a293240c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
