<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization Phone</name>
   <tag></tag>
   <elementGuidId>7262b905-c3d4-4a75-be70-9ad67324b7a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#profile_group1_school_phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group1_school_phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d422f7e-3081-48a8-947e-9f291f4bec13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>school_phone</value>
      <webElementGuid>df9b978d-4fd5-4458-b091-a61a470b39a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>111</value>
      <webElementGuid>7a43400d-6586-4536-84a6-95e59a89a5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-medium-field</value>
      <webElementGuid>1791cf0e-3eb7-49fe-aed3-7cfe9920a1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group1_school_phone</value>
      <webElementGuid>636bcea5-0f59-4c1b-aa21-c03cda6b2e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group1][school_phone]</value>
      <webElementGuid>6d4fa357-0095-467e-950e-fa1ab84b020f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0491bf70-1b4b-4159-8515-34659816eeb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38d9f3cd-ccd3-4983-8ea1-af7e3d43c42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile_group1_school_phone&quot;)</value>
      <webElementGuid>f5687808-e49b-42d7-bf5a-aa4e83702c45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group1_school_phone']</value>
      <webElementGuid>f0a02b81-0f09-40ab-96ee-e72ca1e3d9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group1']/div[9]/div[2]/input</value>
      <webElementGuid>ac8c11a7-35a1-47db-8d02-4e40f61cbed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/input</value>
      <webElementGuid>ad41653e-c010-41f4-93dd-f3258db8e383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group1_school_phone' and @name = 'profile[group1][school_phone]' and @type = 'input']</value>
      <webElementGuid>e8666de9-c4a2-42a1-b3c1-6666f9c49e77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
