<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_AIMS</name>
   <tag></tag>
   <elementGuidId>fead7138-b9ce-4e7c-8c10-9e786cf30ad7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='registration_group-1464701251.989_memberships'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cfb12d19-4448-4c8b-9db5-a64a3edc94b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1464701251.989_memberships</value>
      <webElementGuid>2ba00ef4-8d4e-4ee5-8cc5-19b869a79084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6772397d-32f2-4994-b570-90e688c66d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1464701251.989][memberships][]</value>
      <webElementGuid>275e5971-e41a-4cda-98dd-d2dcdc214dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AIMS</value>
      <webElementGuid>9f3bfc32-8d4e-4abc-82d2-11bd93a17980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1464701251.989&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-checkbox mn-medium-checkbox&quot;]/div[3]/input[@id=&quot;registration_group-1464701251.989_memberships&quot;]</value>
      <webElementGuid>6d50b755-7339-4d84-b03e-656f5b1e27c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='registration_group-1464701251.989_memberships'])[3]</value>
      <webElementGuid>92fb4769-f018-45fc-a777-9cfe4706423b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1464701251.989']/div[5]/div[2]/div/div[3]/input</value>
      <webElementGuid>cef7120c-d56b-4387-8e6a-7cd320f00175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>92fdde0f-0b36-4e0e-933d-e07a9794a993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group-1464701251.989_memberships' and @type = 'checkbox' and @name = 'registration[group-1464701251.989][memberships][]']</value>
      <webElementGuid>093cf8d7-c12f-4f61-97a0-8dae500f62af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
