<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_None of the above</name>
   <tag></tag>
   <elementGuidId>fc6171ea-63e8-4380-ade7-22e71f5c24c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='registration_group-1464701251.989_memberships'])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb01c514-1bbf-498b-bec0-cf445fcbbbd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1464701251.989_memberships</value>
      <webElementGuid>b71798ba-b987-4c30-88c0-ee6baa565f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c0b2ca3e-f0c0-4ed9-922e-0ccd888b58aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1464701251.989][memberships][]</value>
      <webElementGuid>b7cdd011-2dd0-4e7c-9875-ff0b5e137ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>None of the above</value>
      <webElementGuid>54e6a78c-9e26-4419-ae8c-815c01d9ef9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1464701251.989&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-checkbox mn-medium-checkbox&quot;]/div[3]/input[@id=&quot;registration_group-1464701251.989_memberships&quot;]</value>
      <webElementGuid>b39511f3-3072-4516-85ea-70dd05ef9d91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='registration_group-1464701251.989_memberships'])[7]</value>
      <webElementGuid>ebc5d66c-8be6-40ad-80d7-5c2908526f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1464701251.989']/div[5]/div[2]/div[2]/div[3]/input</value>
      <webElementGuid>1c5cb534-e140-47b0-9aa3-4c9f79e43c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>097f5380-d41f-4f74-8267-8447bda15331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group-1464701251.989_memberships' and @type = 'checkbox' and @name = 'registration[group-1464701251.989][memberships][]']</value>
      <webElementGuid>ac41dd0b-fe6e-4ffa-8413-f442e78d7b7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
