<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Organization Full Name</name>
   <tag></tag>
   <elementGuidId>ebc2eaee-4fe3-49bc-ad96-1f102aa30994</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='registration_group-1464701251.989_agency_full_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>511bd932-106c-4a4e-9478-fef16ee7a7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-input mn-medium-field</value>
      <webElementGuid>b452971c-1bb3-41e9-9b5a-73c17d0c1076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>agency_full_name</value>
      <webElementGuid>ea31d81d-fab4-475d-b15f-8c1a256c9ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>0afdce4b-13eb-4b60-892e-b1e8402e5abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1464701251.989_agency_full_name</value>
      <webElementGuid>916b6caa-89be-4a41-bb48-187e286981ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1464701251.989][agency_full_name]</value>
      <webElementGuid>f2661d1c-c29c-4687-8771-088de4038838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>080287be-8467-473e-8022-fc9389c3202a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>963e3c1d-9311-44d5-9dac-569c541241a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group-1464701251.989_agency_full_name&quot;)</value>
      <webElementGuid>ee8c132e-b56f-4512-bfc1-14229134263e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='registration_group-1464701251.989_agency_full_name']</value>
      <webElementGuid>b330e8de-5eac-4377-a171-e0c7b49108d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1464701251.989']/div/div[2]/input</value>
      <webElementGuid>9b347088-8b5e-4dee-ac6c-2d7d65ffc89a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>d4b5cf6a-1e91-4d85-ad52-477bf9561c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'registration_group-1464701251.989_agency_full_name' and @name = 'registration[group-1464701251.989][agency_full_name]' and @type = 'input']</value>
      <webElementGuid>8fe3309f-9acb-41c6-af36-2991b1c2a076</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
