<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_References</name>
   <tag></tag>
   <elementGuidId>21cf91e0-de06-4b9e-9e41-f511547aa46b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='registration_group-1464701251.989_references']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2b3ab343-0782-4602-aa88-2f27d622feed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-text mn-medium-field</value>
      <webElementGuid>edf73ca7-8ca2-4529-bb4f-1e47766247ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>references</value>
      <webElementGuid>6df34109-9a9c-4fac-a9db-523797a92718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>8747afa4-27c9-4c89-8d74-1b62254eae87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1464701251.989][references]</value>
      <webElementGuid>43e38fde-8a47-4106-a41f-880baed3b697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1464701251.989_references</value>
      <webElementGuid>8776a4a4-124a-4988-945f-39658bdbdce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>References:</value>
      <webElementGuid>71af1143-4c68-4e94-baac-f28045b02e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group-1464701251.989_references&quot;)</value>
      <webElementGuid>e8f2de95-4993-4162-8446-888919b32652</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='registration_group-1464701251.989_references']</value>
      <webElementGuid>331b485c-aa40-4139-b210-ce3e7c241206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1464701251.989']/div[8]/div[2]/textarea</value>
      <webElementGuid>7429f04a-ce77-40a9-95b1-11db44a056ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/textarea</value>
      <webElementGuid>6aae7fa8-074a-4089-8556-e03e572238c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'registration[group-1464701251.989][references]' and @id = 'registration_group-1464701251.989_references' and @placeholder = 'References:']</value>
      <webElementGuid>e785cf85-cf27-48fe-a08b-8aa5a4000c31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
