<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description</name>
   <tag></tag>
   <elementGuidId>aaca1663-76fe-450d-a68c-f0963c2d3fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='registration_group-1464701251.989_srvc_agency_description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>23e2edcb-9c4d-4f42-bb5c-55a345c4c408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mn-text mn-large-field</value>
      <webElementGuid>073c5ad2-dd48-47fb-9cd6-7c302ffff9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>srvc_agency_description</value>
      <webElementGuid>bc6e9db6-e3ba-4fb8-84ee-2259416e899b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>58b58b01-8916-4bbd-9683-8a366fca27bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>registration[group-1464701251.989][srvc_agency_description]</value>
      <webElementGuid>d673c27d-80a1-452a-a29b-63ddfc5c6d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registration_group-1464701251.989_srvc_agency_description</value>
      <webElementGuid>c37a6bc7-651d-443b-aafb-7526f186a137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registration_group-1464701251.989_srvc_agency_description&quot;)</value>
      <webElementGuid>fcfac81a-9ffc-4e78-b6e7-a5a036f2f028</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='registration_group-1464701251.989_srvc_agency_description']</value>
      <webElementGuid>6d8a60c4-ac4f-4809-ab8f-7ab57b1444d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1464701251.989']/div[4]/div[2]/textarea</value>
      <webElementGuid>11baa296-d6dd-43c5-a4f0-2b86ea4af15a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4ad379c3-91be-4ba0-b938-b46b20346c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'registration[group-1464701251.989][srvc_agency_description]' and @id = 'registration_group-1464701251.989_srvc_agency_description']</value>
      <webElementGuid>eb120cbc-3204-4daa-affb-88a208388e19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
