<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IT Proficiencies</name>
   <tag></tag>
   <elementGuidId>dc486347-2995-4f90-a28c-1a73fb3c9a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1694660169.099_it_proficiencies']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d43bc6be-f991-4e14-9d8c-f87fdb864f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1694660169.099_it_proficiencies</value>
      <webElementGuid>69104a08-74b9-4fcf-9c77-dda6fc4f1b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>84c1974c-2aa0-4add-92d5-82e99998e276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1694660169.099][it_proficiencies][]</value>
      <webElementGuid>1bb857cc-faee-41bb-ae06-213050e2f293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Developer, Applications</value>
      <webElementGuid>5a466e39-6a08-4822-8ff8-e80fd8535ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1694660169.099&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1694660169.099_it_proficiencies&quot;]</value>
      <webElementGuid>cbb502e6-565d-46ef-b91b-48a83b2a9406</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1694660169.099_it_proficiencies']</value>
      <webElementGuid>6a2f68dd-01f2-4018-8cc3-9d642758782f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1694660169.099']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>340ba596-8573-485f-a887-1c0b6e219702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>febe765a-a2fb-4e1d-96b1-b3f76be90c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1694660169.099_it_proficiencies' and @type = 'checkbox' and @name = 'profile[group-1694660169.099][it_proficiencies][]']</value>
      <webElementGuid>4624f74f-0587-4c42-8bb7-671365762d5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
