<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IT Job Categories</name>
   <tag></tag>
   <elementGuidId>79954555-d44f-40c8-923f-b569f6ebfc01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1694660169.099_it_job_categories']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7c1743c-7ed8-44c2-8552-3567618ebdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1694660169.099_it_job_categories</value>
      <webElementGuid>6f9d2e91-c6cb-4f6c-bf75-48a17bbdf4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>50264f40-b539-4dd7-aff7-ec0e51dcb032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1694660169.099][it_job_categories][]</value>
      <webElementGuid>7ff9cb41-9412-483d-b1b9-cf4395db9bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TECHNICAL</value>
      <webElementGuid>ed482d3d-c9eb-4b2e-9d0f-318cdfa936f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1694660169.099&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1694660169.099_it_job_categories&quot;]</value>
      <webElementGuid>0389eeaa-3152-4cf6-821b-fdfbd2a02eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1694660169.099_it_job_categories']</value>
      <webElementGuid>d44a171f-bcd5-469c-aaaa-7bae0cb8ddfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1694660169.099']/div/div[2]/div/div/input</value>
      <webElementGuid>63b08b2e-381c-495b-a393-610ea2a5ce54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/div/div/input</value>
      <webElementGuid>bf50306b-2071-47f2-8429-5fc18c6bbc3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1694660169.099_it_job_categories' and @type = 'checkbox' and @name = 'profile[group-1694660169.099][it_job_categories][]']</value>
      <webElementGuid>361e0f7e-d4ec-4cfb-8aa0-911e31c1ce3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
