<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Computer Languages</name>
   <tag></tag>
   <elementGuidId>ebe6f1c3-2ad6-40ab-92e4-58efc07657b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='profile_group-1694660169.099_computer_languages']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b85c5636-a57d-4ed5-b7e3-39a33a203b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1694660169.099_computer_languages</value>
      <webElementGuid>391f616f-8356-4f41-b1c8-be343fe94b5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>94d5070a-9af9-4b3b-86cc-c6793e9f9aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1694660169.099][computer_languages][]</value>
      <webElementGuid>76567b19-7b61-4ecc-b19a-65538f325f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Assembly</value>
      <webElementGuid>8d3e17f0-38f9-4a8e-b856-3f54c74b5cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1694660169.099&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[1]/input[@id=&quot;profile_group-1694660169.099_computer_languages&quot;]</value>
      <webElementGuid>d2dea05f-58dc-4465-a4ed-ec3b926fa83a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='profile_group-1694660169.099_computer_languages']</value>
      <webElementGuid>5ad8ec6d-a250-4b0b-86fb-d2591517e5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1694660169.099']/div[3]/div[2]/div/div/input</value>
      <webElementGuid>07e4fde5-9090-4714-b30f-30b40ab5b5a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>802c5ed9-2d69-4cf3-82fd-719415801138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1694660169.099_computer_languages' and @type = 'checkbox' and @name = 'profile[group-1694660169.099][computer_languages][]']</value>
      <webElementGuid>48a749b2-6f52-4d1d-a6a7-608410117450</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
