<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Python</name>
   <tag></tag>
   <elementGuidId>9dea4990-987b-4347-9a9b-2cde11a67b33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='profile_group-1694660169.099_computer_languages'])[17]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad06c382-b013-4f97-9d11-62f755e2ab7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>profile_group-1694660169.099_computer_languages</value>
      <webElementGuid>35cc79ab-c705-4a1e-8f91-08e13ddca021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6448248a-c347-41b6-a85f-6e86af75e22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>profile[group-1694660169.099][computer_languages][]</value>
      <webElementGuid>1947ee64-5fe5-46b1-a0e3-8dfed11dbd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>R</value>
      <webElementGuid>c4736a03-e504-4fdf-aa65-a1e29aada788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-1694660169.099&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;mn-checkbox mn-large-checkbox&quot;]/div[9]/input[@id=&quot;profile_group-1694660169.099_computer_languages&quot;]</value>
      <webElementGuid>27798f0b-2f5c-4586-a2c7-e8d00ae4b790</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='profile_group-1694660169.099_computer_languages'])[18]</value>
      <webElementGuid>546f339b-aa2b-47d1-88b9-854ba3c3e79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='group-1694660169.099']/div[3]/div[2]/div[2]/div[9]/input</value>
      <webElementGuid>0c760b07-8783-4815-b5b7-d906f840f281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[9]/input</value>
      <webElementGuid>c698eb36-a975-431a-82ec-f4ea12c3e6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'profile_group-1694660169.099_computer_languages' and @type = 'checkbox' and @name = 'profile[group-1694660169.099][computer_languages][]']</value>
      <webElementGuid>56c87a43-41b2-44f1-9a7d-7ae4dbd32c58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
