<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_u_Ck8_4608</name>
   <tag></tag>
   <elementGuidId>d1a488a5-3f53-4f8b-bdd8-10c0e4f2ed37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_Ck8_4608</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='u_Ck8_4608']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f59753f-3965-4533-8d3f-c8d40cce20e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>u_Ck8_4608</value>
      <webElementGuid>b436c48f-8775-4ddf-9df2-3c96f736215b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_Ck8_4608</value>
      <webElementGuid>9d90307c-f24f-495d-9666-8a10f0b28756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>2af622d2-d1e3-4538-ad8b-b06d3695e9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> u-full-width</value>
      <webElementGuid>8134e7e4-73a6-4b7b-a64d-98fa57c03e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Your email address</value>
      <webElementGuid>c67df838-5e0f-4adf-be3b-fb99656c43b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67735d5e-2014-41fa-974c-a4e0d213c95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_Ck8_4608&quot;)</value>
      <webElementGuid>32f3e68e-b635-4ccf-b5f8-7879cd5c561f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Web Form Example/iframe_a hrefhttpsformsmarts.comformyxCan39_7a5cf4</value>
      <webElementGuid>74a69e88-5135-4b6c-a9d5-5c9e8723c5aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='u_Ck8_4608']</value>
      <webElementGuid>4fb92ec8-b7d7-4cdd-8c95-199a6f706acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='f']/input[8]</value>
      <webElementGuid>e74ed1d0-12fe-4d62-bea2-78bfd01274a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>6731b82e-460f-4c92-a646-42e73faa0ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'u_Ck8_4608' and @id = 'u_Ck8_4608' and @type = 'email' and @placeholder = 'Your email address']</value>
      <webElementGuid>c5dfa8a5-2657-4035-ac4d-6c3206a4bc48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
